### PR TITLE
r/kubernetes_cluster: allowing the Service Principal to be updated

### LINKED ISSUE #3239: AKS error when trying to upgrade cluster
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Provider version 1.24.

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Description
Trying to upgrade aks cluster from 1.11.5 -> 1.11.9. Receiving the following error:

containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id ''at path 'properties.addonProfiles.omsagent.config.logAnalyticsWorkspaceResourceID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."

Unsure if this happens on new cluster creation, only tried the upgrade.

### LINKED ISSUE #3375: Can't update service principal client secret
### Terraform (and AzureRM Provider) Version
`terraform` **v0.11.7**
`azurerm` **1.25.0**

### Affected Resource(s)
`azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "main" {
...
  service_principal {
    client_id     = "my-client-id"
    client_secret = "my-client-secret"
  }
...
}
```
### Expected Behavior
Client secret should be changed. I imagine terraform should do something equivalent to this: https://docs.microsoft.com/en-us/azure/aks/update-credentials#update-aks-cluster-with-new-credentials

By the way, following the steps in the link above and changing the service principal secret using the CLI works fine.

### Actual Behavior
Terraform tries change the service principal secret
```
  ~ azurerm_kubernetes_cluster.main
      service_principal.#:                        "1" => "1"
      service_principal.2995281661.client_id:     "client-id-here" => "client-id-here"
      service_principal.2995281661.client_secret: <sensitive> => <sensitive> (attribute changed)
```

And fails with:
```
* azurerm_kubernetes_cluster.main: Error creating/updating Managed Kubernetes Cluster "myCluster" (Resource Group "myResourceGroup"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.addonProfiles.omsagent.config.logAnalyticsWorkspaceResourceID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."
```

### Steps to Reproduce
1. Create cluster with terraform 
2. Go to Azure Portal, change your service principal client secret
3. Run `terraform plan` and try to apply it.

I have mentioned this in my other issue here https://github.com/terraform-providers/terraform-provider-azurerm/issues/2993 and also in AKS github issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/3239 where the author got the same error performing a different operation.

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR fixes both #3239 and #3375 by allowing the Service Principal to be updated - and also attempts to retrieve it from the state using either a Set (prior to 1.34) or a List (after 1.34)

In addition to ensure the state is consistent for nested fields this PR also updates the flatten functions to ensure that all fields within nested blocks are set

Fixes #3239
Fixes #3375

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Ignoring a couple of temporary AKS capacity tests (which passed on a retry) the tests pass:

Screenshot 2019-10-01 at 12 46 03

**Comment by tombuildsstuff** [comment]
Seems fine in state migrations from 1.33.1 -> this branch & 1.33.1 -> 1.34.0 -> this branch

**Comment by Bowbaq** [comment]
@tombuildsstuff this breaks for me locally. Running terraform apply, I get:
```
Error: rpc error: code = Unavailable desc = transport is closing
```

Running with `TF_LOG=debug` I get:
```
Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


Releasing state lock. This may take a few moments...
panic: interface conversion: interface {} is nil, not map[string]interface {}
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: goroutine 265 [running]:
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenAzureRmKubernetesClusterServicePrincipalProfile(0xc00097d550, 0xc000016460, 0x19, 0x3e7ece0, 0xc0009f1020)
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_kubernetes_cluster.go:1593 +0x370
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmKubernetesClusterRead(0xc000016460, 0x3e18720, 0xc00077a480, 0xc000016460, 0x0)
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_kubernetes_cluster.go:902 +0x163c
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0005d9500, 0xc0005ae230, 0x3e18720, 0xc00077a480, 0xc000795b00, 0xc0005ae230, 0x0)
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:455 +0x119
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000cc038, 0x4b95d80, 0xc000610000, 0xc0005ae140, 0xc0000cc038, 0xc000610000, 0xc001225ba8)
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:525 +0x3d7
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x42c4620, 0xc0000cc038, 0x4b95d80, 0xc000610000, 0xc0005ae0a0, 0x0, 0x4b95d80, 0xc000610000, 0xc000b3a000, 0x539a)
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3181 +0x23e
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000547500, 0x4be3780, 0xc000547800, 0xc00132c000, 0xc0006e4d20, 0x820f510, 0x0, 0x0, 0x0)
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:972 +0x470
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000547500, 0x4be3780, 0xc000547800, 0xc00132c000, 0x0)
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1252 +0xda6
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005e2020, 0xc000547500, 0x4be3780, 0xc000547800, 0xc00132c000)
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:691 +0x9f
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: created by github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-10-04T15:29:20.023-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:689 +0xa1
```

Applying using `1.34` seems to work fine. Our service principal config looks like this:
```
  service_principal {
    client_id     = module.k8s-principal.client_id
    client_secret = module.k8s-principal.client_secret
  }
```

We're using terraform 0.12

**Comment by tbsquare01** [comment]
@tombuildsstuff is the fix for #4356 expected in "~> 1.35.0" Azure provider?
AKS cluster is still destroying in "1.35.0", the plugin I am using for my deployment.

2019-11-28T23:08:02.1134262Z 
2019-11-28T23:08:02.1134390Z [0m[1mInitializing the backend...[0m
2019-11-28T23:08:02.1134505Z [0m[32m
2019-11-28T23:08:02.1134657Z Successfully configured the backend "azurerm"! Terraform will automatically
2019-11-28T23:08:02.1134837Z use this backend unless the backend configuration changes.[0m
2019-11-28T23:08:02.1134931Z 
2019-11-28T23:08:02.1135064Z [0m[1mInitializing provider plugins...[0m
2019-11-28T23:08:02.1135226Z - Checking for available provider plugins...
2019-11-28T23:08:02.3278343Z - Downloading plugin for provider "random" (hashicorp/random) 2.2.1...
2019-11-28T23:08:03.0505287Z - Downloading plugin for provider "azurerm" (hashicorp/azurerm) 1.37.0...
2019-11-28T23:08:05.1823490Z 

[0m[1mrandom_string.id_string: Refreshing state... [id=b0dyrs][0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Refreshing state... [id=/subscriptions/.../resourcegroups/myRG/providers/Microsoft.ContainerService/managedClusters/K8SAKS][0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Destroying... [id=/subscriptions/-.../resourcegroups/myRG/providers/Microsoft.ContainerService/managedClusters/K8SAKS][0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still destroying... [id=/subscriptions/-...erService/managedClusters/K8SAKS, 10s elapsed][0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still destroying... [id=/subscriptions/-...erService/managedClusters/K8SAKS, 20s elapsed][0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still destroying... [id=/subscriptions/-...erService/managedClusters/K8SAKS, 30s elapsed][0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still destroying... [id=/subscriptions/-...erService/managedClusters/K8SAKS, 50s elapsed][0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still destroying... [id=/subscriptions/-...erService/managedClusters/K8SAKS, 1m0s elapsed][0m[0m
[...]
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Destruction complete after 11m5s[0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Creating...[0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still creating... [10s elapsed][0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still creating... [21s elapsed][0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still creating... [31s elapsed][0m[0m
[0m[1mazurerm_kubernetes_cluster.aks_cluster: Still creating... [41s elapsed][0m[0m

**Comment by tombuildsstuff** [comment]
@tbsquare01 the AKS API has undergone a bunch of changes of late - as such at this time I'd recommend using version 1.37 of the Azure Provider instead

**Pull request merged**
