### PR TITLE
SQL Firewall Rules: support for `allow access to azure services`

### LINKED ISSUE #275: azurerm_sql_firewall_rule / azurerm_sql_server missing option for "Allow access to Azure service"s
_This issue was originally opened by @CryptonZylog as hashicorp/terraform#15925. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
Terraform v0.10.2

------------------

It appears that neither `azurerm_sql_firewall_rule` nor `azurerm_sql_server` support this switch available in the Azure Portal to "Allow access to Azure services" when managing firewall access for SQL Server resource.

It seems it could be added as part of `azurerm_sql_server` config?

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Adding a disclaimer about `allow access to azure services`

Fixes #275

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
> Do I read it right that Azure does not have anything like AWS' VPC Endpoints (yet) hence traffic to Azure's services has to go over the internet? 😮

VPC-esque functionality exists for some services (e.g. Redis and App Services) but are public by default for SQL / App Service / Redis / Key Vault afaik.

**Comment by wtfiwtz** [comment]
For SQL, if you use Express Route, there are two public IP addresses used.

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-vnet-service-endpoint-rule-overview

You can also add a "virtual network" to the SQL server through the portal or powershell.
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-vnet-service-endpoint-rule-powershell

**Comment by bostonmoto** [comment]
Hello @tombuildsstuff  with regards to the earlier OP and link to https://docs.microsoft.com/en-us/azure/sql-database/sql-database-vnet-service-endpoint-rule-powershell

I do not see any support for adding a vnet rule to an azure SQL server - Can we add support for this by any chance? Right now I have to manually add the virtual network rule from the console to allow my servers to talk to the Azure SQL in a secure manner.

**Comment by tombuildsstuff** [comment]
@bostonmoto would you mind opening a separate issue about this?

**Comment by bostonmoto** [comment]
No problem @tombuildsstuff I have done so here - https://github.com/terraform-providers/terraform-provider-azurerm/issues/955
Thanks!

**Pull request merged**
