### PR TITLE
allow up-to-two client certs

### PR DESCRIPTION
**Pull request by steve-hawkins**
This should address #1938

### CODE REVIEW

**Comment by steve-hawkins** [comment]
@katbyte thanks for the feedback, think that test should cover it, but please let me know

**Comment by katbyte** [comment]
@steve-hawkins,

You can run just one test with this command:
```
make fmt; make testacc TEST=./azurestack TESTARGS=-test.run=TestAccAzureStackStorageAccount_basic
```

or all tests starting with a pattern with this command:
```
make fmt; make testacc TEST=./azurestack TESTARGS=-test.run=TestAccAzureStackStorageAccount
```

**Comment by katbyte** [comment]
Tests pass:
screen shot 2018-09-19 at 10 39 06

**Comment by steve-hawkins** [comment]
thanks @katbyte for getting back so quickly

**Pull request merged**
