### PR TITLE
dependencies: updating to v43.1.0 of github.com/Azure/azure-sdk-for-go

### PR DESCRIPTION
**Pull request by tombuildsstuff**

### CODE REVIEW

**Comment by jrauschenbusch** [comment]
@tombuildsstuff When this PR is getting merged? I would like to use it to proceed with the Kusto SDK Upgrade and i do have a set of separate branches ready to extend the Kusto resources with some features (e.g. https://github.com/terraform-providers/terraform-provider-azurerm/issues/6854, https://github.com/terraform-providers/terraform-provider-azurerm/issues/6855)

**Comment by ArcturusZhang** [comment]
Could we hold this for a while since I will include keyvault 2019-09-01 in the v43.1.0? I believe it could be released in at most the next a few days...

**Comment by katbyte** [comment]
@jrauschenbusch - i think we'll be merging this within the next couple of days

**Comment by jrauschenbusch** [comment]
@tombuildsstuff @katbyte https://github.com/Azure/azure-sdk-for-go/releases/tag/v43.1.0 is now released. So imho there is no blocker anymore to get this PR updated and merged.

**Comment by tombuildsstuff** [comment]
👋 from our side we'll look to update/merge this once 2.14 has been released later today 👍

**Pull request merged**
