### PR TITLE
exclude app_service_environment_id from update when empty

### LINKED ISSUE #5884: Error creating/updating App Service Plan (Message="Property id '' at path 'properties.hostingEnvironmentProfile.id' is invalid)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Hello,
Since today terraform refuses to deploy our .NET core web application to azure using terraform. Everything worked fine yesterday, we didn't change anything.

### Relevant terraform config

```
resource "azurerm_resource_group" "rgnetwork" {
    name = var.ResourceGroupNameNetwork
    location = "West europe"
}

resource "azurerm_app_service_plan" "asp" {
    name = var.asp-name
    resource_group_name = azurerm_resource_group.rg.name
    location = azurerm_resource_group.rg.location
    kind = "Windows"

    sku {
        size = var.asp-sku-size
        tier = var.asp-sku-tier
    }
}
```

### Debug Output

Message="Property id '' at path 'properties.hostingEnvironmentProfile.id' is invalid
https://gist.github.com/woeterman94/8abb5a9706c8cc101bacd07f1330905d

### Expected Behavior

Create / update the resource

### Actual Behavior

The step crashed.

(same issue as : https://github.com/hashicorp/terraform/issues/24209 ? )

### PR DESCRIPTION
**Pull request by jackofallops**
Fixes #5884

### CODE REVIEW

**Comment by jackofallops** [comment]
Closing in favour of #5910

**Comment by jackofallops** [comment]
Re-opening to review as 5910 had unseen side effects.

**Comment by woeterman94** [comment]
Will this fix be applied to all Terraform versions?

**Comment by jackofallops** [comment]
Hi @woeterman94 
It will be released with the next point release of the provider, I'm afraid it's not possible to add it to already released versions.
Thanks,
Ste

**Comment by woeterman94** [comment]
Can you please clarify. As you are talking about the "provider release".  Will this issue be fixed in Terraform 1.44?

**Pull request merged**
