### PR TITLE
Removed ForceNew=true on the sku_tier parameter definition

### PR DESCRIPTION
**Pull request by blame19**
Addresses [#7530](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7530)

### CODE REVIEW

**Comment by djsly** [comment]
@jackofallops is this something we could expect the azurerm folks to tackle if you think its a bit more complex then just removing the forced flag ?

From an SDK point of view, it seems that they are simply accepting update in place.

**Comment by jackofallops** [comment]
> @jackofallops is this something we could expect the azurerm folks to tackle if you think its a bit more complex then just removing the forced flag ?
> 
> From an SDK point of view, it seems that they are simply accepting update in place.

@djsly - I suspect this is probably the case, but don't like to assume.  The flag is quite likely just that, and has little or no impact on the operation of the cluster, but will need working into the `update` func, which is somewhat more involved than most.  I can't commit to when we'd be able to look at this, but we can take it on if @blame19 feels it's more than they're comfortable with.

**Comment by blame19** [comment]
Just a small update on this. 
I went ahead and tried the custom provider without the forceNew tag on the sku_tier. 
The tag per se works as intended, 
image
Yet according to terraform plan the cluster should be recreated:
image
Needless to say, I didn't change my ssh public key between runs. There might be something here I'm not aware of regarding the sku_tier upgrade.

@jackofallops would you happen to have any insight on that?

**Comment by jackofallops** [comment]
Hi @blame19 
The plan doesn't actually make any changes. It just shows what the expected output will be without interacting with the service. Removing the `ForceNew` flag from a parameter means that the plan expects the `update` function to deal with change to the value.  The `update` function does not currently send any value for that parameter, so the `sku_tier` won't actually be changed, and the result will be an inconsistent state after an apply.  Does the above make sense?

Microsoft have requested we take a look at what's involved in supporting this for one of their customers, so I'm investigating it today.

**Comment by jackofallops** [comment]
Update: Since this change is on the `master` branch of your fork I'm not able to safely push changes to your copy so I've created a new branch and PR'd from there. Since you started the work, I'll add you as a co-author when this is merged, but I'll be closing this PR as a result.
Thanks for the contribution.

**Pull request closed without merging**
