### PR TITLE
Upgrade Go-SDK version to v55.2

### PR DESCRIPTION
**Pull request by yupwei68**
Upgrade Go-SDK version to v55.2 for fixing postgresql flexible server breaking change

### CODE REVIEW

**Comment by timja** [comment]
conflicts @yupwei68

**Comment by yupwei68** [comment]
Hi @timja Thanks. Please continue reviewing.

**Review by timja — APPROVED** [review]
Code changes look good to me, anyone able to run the tests?

**Review by katbyte — APPROVED** [review]
LGTM 🚀

**Pull request merged**
