### PR TITLE
r/storage_queue: switching to use SharedKey for auth

### LINKED ISSUE #3925: `azurerm_storage_share` - enabling firewall on storage account makes the request `not authorized`
After upgrading to 1.32.0 refreshing an existing storage share fails with the following error: 

`Error retrieving File Share "XYZ" (Account "XYZ" / Resource Group "RG"): shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:xxx\nTime:xxx</Message></Error>" error: invalid character 'ï' looking for beginning of value.`

To reproduce the issue, apply the following config:

```
resource "azurerm_resource_group" "test" {
  name     = "azuretest"
  location = "West Europe"
}

resource "azurerm_storage_account" "test" {
  name                     = "azureteststorage"
  resource_group_name      = "${azurerm_resource_group.test.name}"
  location                 = "${azurerm_resource_group.test.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "testshare" {
  name                 = "sharename"
  storage_account_name = "${azurerm_storage_account.test.name}"
  quota                = 50
}

```
After the initial terraform apply, when you attempt to do another plan it will fail with the above error.

`Terraform v0.11.11`

### LINKED ISSUE #3939: Error while creating storage account
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.3
+ provider.azurerm v1.32.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

`
variable "storage_name" {}
variable "region" {}
variable "resource_group_name" {}
variable "environment" {}
variable "usage" {}
variable "dependencies" {
  type = list(string)
}

resource "null_resource" "dependency_getter" {
  triggers = {
    my_dependencies = join(",", var.dependencies)
  }
}

# Generate random text for a unique name
resource "random_id" "randomId" {
  keepers = {
    # Generate a new ID only when a new resource group is defined
    resource_group = var.resource_group_name
  }
  byte_length = 8
}

resource "azurerm_storage_account" "stgacc" {
  name = "diag${random_id.randomId.hex}"
  resource_group_name = var.resource_group_name
  location = var.region
  account_tier = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment = var.environment
  }

  depends_on = [null_resource.dependency_getter]
}

resource "azurerm_storage_account" "stgaccount" {
  name = var.storage_name
  resource_group_name = var.resource_group_name
  location = var.region
  account_tier = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment = var.environment
  }

  depends_on = [null_resource.dependency_getter]
}
`
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Terraform successful creation statement.

### Actual Behavior

Error: Error reading queue properties for AzureRM Storage Account "diag5d01f638b17d3d58": queues.Client#SetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:4554aa06-9003-00dc-7bb2-43c9be000000\nTime:2019-07-26T13:01:08.2516744Z</Message></Error>" error: invalid character 'ï' looking for beginning of value

Error: Error reading queue properties for AzureRM Storage Account "tboxfkartstorage": queues.Client#SetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:df5abaf5-5003-0010-03b2-43d411000000\nTime:2019-07-26T13:00:58.3772146Z</Message></Error>" error: invalid character 'ï' looking for beginning of value

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The resources are created and visible in the azure portal with proper configuration. But the script ends without success message.

### References

* #0000

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR fixes a couple of bugs around Storage Queues:

1. Switches to using SharedKey for authentication rather than AzureAD - since apparently the Azure Storage API's require an additional permission (on top of Owner/Contributor) to access the Storage API's (and [which can't be configured at the root if a DataBricks cluster is provisioned](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#determine-resource-scope))
2. The Environment wasn't being set correctly for the Storage Queues API, such that this defaulted to Azure Public

Unfortunately I'm unable to reproduce #3939, but I believe this should fix it.

Fixes #3939
Fixes #3925

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Requires vendoring https://github.com/tombuildsstuff/giovanni/pull/4

**Comment by tombuildsstuff** [comment]
Tests look good 👍

**Comment by invidian** [comment]
This PR is actually misleading, since it switches storage_queue to use SharedKey**Lite**, not `SharedKey`.

**Comment by tombuildsstuff** [comment]
@invidian we're aware and looking into this, in this case it's used as an abbreviation since it appeared that SharedKey authentication was superflurious

**Pull request merged**
