### PR TITLE
Added Virtual Network Integration to the API Management service

### PR DESCRIPTION
**Pull request by joranm**
- Added the virtual_network_type property which allows None, Internal or External

- Added virtual_network_configuration object with property subnet_id which references the subnet to integrate with.

See https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet for details regarding API Management with Vnet integration

### CODE REVIEW

**Comment by joranm** [comment]
Hi @katbyte, I've found the issue why the tests were failing. Fixed the issue by adding additional checks if the virtual_network_configuration object is present. Additionally I've found that the Virtual Network Type will always return None from Azure. So I've added this as the default value of the property.

**Comment by joranm** [comment]
Hi @katbyte, I've found that if the additional_location object is present, the virtual_network_configuration should also be present to make this work. Otherwise is reverse to the "default" virtual_network_configuration in the first location (which fails). This requires some rework and testing from my side which I will try to perform this week.

**Comment by joranm** [comment]
@tombuildsstuff and @katbyte, 

I've 
- [ ] added the virtual_network_configuration to the additional locations.
- [ ] added the private_ip_addresses to service properties and additional_locations

**Comment by katbyte** [comment]
Thanks for the updates @joranm,

I am still getting an error on our CI server, different this time however 😅 

```
------- Stdout: -------
=== RUN   TestAccAzureRMApiManagement_complete
=== PAUSE TestAccAzureRMApiManagement_complete
=== CONT  TestAccAzureRMApiManagement_complete
--- FAIL: TestAccAzureRMApiManagement_complete (2173.23s)
	testing.go:599: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Error applying: 2 error(s) occurred:
		
		* azurerm_subnet.test1 (destroy): 1 error(s) occurred:
		
		* azurerm_subnet.test1: Error deleting Subnet "subnet-1260518037164007063" (VN "acctest-vnet-1260518037164007063" / Resource Group "acctestRG-1260518037164007063"): network.SubnetsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet subnet-1260518037164007063 is in use by /subscriptions/*******/providers/Microsoft.ApiManagement/service?vnetResourceGuid=8c4a597c-2d13-44ef-a935-80ae09872e1e&subnet=subnet-1260518037164007063&api-version=2016-07-07 and cannot be deleted." Details=[]
		* azurerm_subnet.test2 (destroy): 1 error(s) occurred:
		
		* azurerm_subnet.test2: Error deleting Subnet "subnet-1260518037164007063" (VN "acctest-vnet-1260518037164007063" / Resource Group "acctestRG2-1260518037164007063"): network.SubnetsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet subnet-1260518037164007063 is in use by /subscriptions/*******/providers/Microsoft.ApiManagement/service?vnetResourceGuid=d443303e-9acf-4b5b-8704-ba1ce8531379&subnet=subnet-1260518037164007063&api-version=2016-07-07 and cannot be deleted." Details=[]
		
		State: azurerm_resource_group.test1:
		  ID = /subscriptions/*******/resourceGroups/acctestRG-1260518037164007063
		  provider = provider.azurerm
		  location = westeurope
		  name = acctestRG-1260518037164007063
		  tags.% = 0
		azurerm_resource_group.test2:
		  ID = /subscriptions/*******/resourceGroups/acctestRG2-1260518037164007063
		  provider = provider.azurerm
		  location = eastus2
		  name = acctestRG2-1260518037164007063
		  tags.% = 0
		azurerm_subnet.test1:
		  ID = /subscriptions/*******/resourceGroups/acctestRG-1260518037164007063/providers/Microsoft.Network/virtualNetworks/acctest-vnet-1260518037164007063/subnets/subnet-1260518037164007063
		  provider = provider.azurerm
		  address_prefix = 10.0.0.0/24
		  ip_configurations.# = 0
		  name = subnet-1260518037164007063
		  resource_group_name = acctestRG-1260518037164007063
		  route_table_id = 
		  service_endpoints.# = 0
		  virtual_network_name = acctest-vnet-1260518037164007063
		
		  Dependencies:
		    azurerm_resource_group.test1
		    azurerm_virtual_network.test1
		azurerm_subnet.test2:
		  ID = /subscriptions/*******/resourceGroups/acctestRG2-1260518037164007063/providers/Microsoft.Network/virtualNetworks/acctest-vnet-1260518037164007063/subnets/subnet-1260518037164007063
		  provider = provider.azurerm
		  address_prefix = 10.0.0.0/24
		  ip_configurations.# = 0
		  name = subnet-1260518037164007063
		  resource_group_name = acctestRG2-1260518037164007063
		  route_table_id = 
		  service_endpoints.# = 0
		  virtual_network_name = acctest-vnet-1260518037164007063
		
		  Dependencies:
		    azurerm_resource_group.test2
		    azurerm_virtual_network.test2
		azurerm_virtual_network.test1:
		  ID = /subscriptions/*******/resourceGroups/acctestRG-1260518037164007063/providers/Microsoft.Network/virtualNetworks/acctest-vnet-1260518037164007063
		  provider = provider.azurerm
		  address_space.# = 1
		  address_space.0 = 10.0.0.0/16
		  dns_servers.# = 0
		  location = westeurope
		  name = acctest-vnet-1260518037164007063
		  resource_group_name = acctestRG-1260518037164007063
		  subnet.# = 1
		  subnet.2876441382.address_prefix = 10.0.0.0/24
		  subnet.2876441382.id = /subscriptions/*******/resourceGroups/acctestRG-1260518037164007063/providers/Microsoft.Network/virtualNetworks/acctest-vnet-1260518037164007063/subnets/subnet-1260518037164007063
		  subnet.2876441382.name = subnet-1260518037164007063
		  subnet.2876441382.security_group = 
		  tags.% = 0
		
		  Dependencies:
		    azurerm_resource_group.test1
		azurerm_virtual_network.test2:
		  ID = /subscriptions/*******/resourceGroups/acctestRG2-1260518037164007063/providers/Microsoft.Network/virtualNetworks/acctest-vnet-1260518037164007063
		  provider = provider.azurerm
		  address_space.# = 1
		  address_space.0 = 10.0.0.0/16
		  dns_servers.# = 0
		  location = eastus2
		  name = acctest-vnet-1260518037164007063
		  resource_group_name = acctestRG2-1260518037164007063
		  subnet.# = 1
		  subnet.2876441382.address_prefix = 10.0.0.0/24
		  subnet.2876441382.id = /subscriptions/*******/resourceGroups/acctestRG2-1260518037164007063/providers/Microsoft.Network/virtualNetworks/acctest-vnet-1260518037164007063/subnets/subnet-1260518037164007063
		  subnet.2876441382.name = subnet-1260518037164007063
		  subnet.2876441382.security_group = 
		  tags.% = 0
		
		  Dependencies:
		    azurerm_resource_group.test2
FAIL
```

**Comment by joranm** [comment]
Hi @katbyte, the dependency between the API Management Service and the subnet/virtual network is not in place. The destroy action for the virtual network/subnet is requested before the API Management Service is destroyed. Do you have an example how to accomplish this? @steve-hawkins @tombuildsstuff

**Comment by steve-hawkins** [comment]
Hi @joranm, at a guess this is probably due to the API Manager still reliant on classic parts, there is a note in the [docs when connecting to a VNET](https://docs.microsoft.com/en-gb/azure/api-management/api-management-using-with-vnet#a-nameenable-vpn-aenable-vnet-connection):-

image

This is further explained in the [FAQ](https://docs.microsoft.com/en-gb/azure/api-management/api-management-faq#why-do-we-require-a-dedicated-subnet-in-resource-manager-style-vnets-when-api-management-is-deployed-into-them) section

@tombuildsstuff I'm pretty sure this has been addressed in other areas of this provider, I just can't remember where?

**Comment by joranm** [comment]
Hi @tombuildsstuff , thanks for your help for so far!

If in the end of Januari the `2019-01-01` is release, the AZURE GO SDK needs to be updated, and the we can fix this right?

**Comment by katbyte** [comment]
@joranm, yep! However that all depends on how easy it is to upgrade the SDK, right now a couple issues are blocked on the SDK being fixed so we can move to `v24.0.0`

**Comment by joranm** [comment]
There is some movement in the REST API Spec https://github.com/Azure/azure-rest-api-specs/issues/4409 
What are the next steps for this PR?

**Comment by katbyte** [comment]
@joranm,

We have updated the sdk [quite recently](#2886) and it looks like it is now in the [`2018-06-01-preview` ](https://github.com/Azure/azure-sdk-for-go/tree/ca4654c50e30248fa542c1f0dd07fbde21d9b9a2/services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement) api.

So we could switch over to that API version now provided it doesn't break anything 🙂

**Comment by joranm** [comment]
Hi @katbyte , what do you expect from me?

**Comment by tombuildsstuff** [comment]
@joranm taking a look into this I believe we should be able to run the tests for this once the fix for #2945 has been merged, I'm looking into this at the moment but there's nothing needed from your side at the moment :)

**Comment by tombuildsstuff** [comment]
hey @joranm 

Just to give an update here: since we've had to downgrade to API version `2018-01-01` to work around the breaking API change - as such this PR's blocked on support for the API version `2019-01-01` being available [in the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go/tree/master/services/apimanagement) - which is being tracked in [the Rest API Specs ticket mentioned above](https://github.com/Azure/azure-rest-api-specs/issues/4409).

Rather than leaving this PR open stagnant until that's available (which I've just asked for an update in the issue) - I'm going to assign this to the 'blocked' milestone and temporarily close this PR for the moment. When the other issue's closed (and the SDK is available) we'll re-open this PR and get support for this functionality merged.

Thanks!

**Comment by keero** [comment]
Seems like the [dependent ticket](https://github.com/Azure/azure-rest-api-specs/issues/4409) has been resolved. When will this PR be reopened again?

**Comment by tombuildsstuff** [comment]
👋 

As @keero has mentioned the upstream issue's been fixed: https://github.com/Azure/azure-rest-api-specs/issues/4409 - once the SDK's been updated #3335 we should be able to go to the new version of the API Management API and look to add support for this

Thanks!

**Comment by katbyte** [comment]
#3335 has been merged so this is no unblocked!

**Comment by tombuildsstuff** [comment]
hey @joranm 

Sorry for the bad news - it looks like the new SDK upgrade (in #3446) is still blocked, this time on: https://github.com/Azure/azure-rest-api-specs/pull/6065

Once that's fixed, we'll circle back and fix this PR up - but for the moment as this is blocked on the external/upstream issue I'm going to temporarily re-close this PR, once that's been fixed we'll re-open this and fix this up / take another look 👍 

Thanks!

**Pull request closed without merging**
