### PR TITLE
Dependencies: upgrade `network` to `2020-07-01`

### PR DESCRIPTION
**Pull request by favoretti**
upgrade `network` to `2020-07-01`

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍 - this'll want manual testing of the network connection monitor and thought about the migration path though, but the latter can be done separately.

**Comment by tombuildsstuff** [comment]
Looks like there's a breaking behavioural change for Application Gateway's in this new API version:

```
------- Stdout: -------
=== RUN   TestAccApplicationGateway_zones
=== PAUSE TestAccApplicationGateway_zones
=== CONT  TestAccApplicationGateway_zones
testing.go:620: Step 1/2 error: Error running apply:
Error: creating/updating Application Gateway: (Name "acctestag-210302093527636647" / Resource Group "acctestRG-210302093527636647"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ZonalApplicationGatewayCannotReferenceNoZonePublicIp" Message="Zonal Application Gateway /subscriptions/*******/resourceGroups/acctestRG-210302093527636647/providers/Microsoft.Network/applicationGateways/acctestag-210302093527636647 with zones 1, 2 cannot reference a non-zonal public ip /subscriptions/*******/resourceGroups/acctestRG-210302093527636647/providers/Microsoft.Network/publicIPAddresses/acctest-pubip-210302093527636647-standard. The IP should use all zones used by the Application Gateway." Details=[]
on config335560111/terraform_plugin_test.tf line 52, in resource "azurerm_application_gateway" "test":
52: resource "azurerm_application_gateway" "test" {
--- FAIL: TestAccApplicationGateway_zones (136.27s)
FAIL
```

**Comment by favoretti** [comment]
It seems it's broken in general. `azurerm_public_ip` when switched from `zones` being `SchemaSingleZone` to either `SchemaMultipleZones` or `SchemaZones` simply ignores the zones you give it and creates an IP address in 3 zones (at least for `eastus2`). Hence so far I don't see a way to make this play nicely with each other :(

**Comment by favoretti** [comment]
@tombuildsstuff looks like network package was downgraded to 2020-07-01 in the latest SDK that we're using, should I try that one instead?

**Comment by katbyte** [comment]
sorry, mistakenly closed it due to slow browser rendering 🤦‍♀️  - @favoretti, its worth a try but theres no guarantee that version won't have the same issue

**Comment by favoretti** [comment]
@katbyte np. Minor pain to try. Will give it a shot.

**Comment by favoretti** [comment]
@tombuildsstuff @katbyte Looks like `TestAccApplicationGateway_zones` passes on `2020-07-01`, there's a regression in master introduced by #11270 in `azurerm_public_ip` datasource, I've added a fix for it here as well, will re-run those 2 tests separately after complete suite is done.

**Pull request merged**
