### PR TITLE
New resource `azurerm_mssql_server_extended_auditing_policy` 

### PR DESCRIPTION
**Pull request by yupwei68**
Extend: https://github.com/terraform-providers/terraform-provider-azurerm/pull/7793
Fix: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7486
  https://github.com/terraform-providers/terraform-provider-azurerm/issues/6906
https://github.com/terraform-providers/terraform-provider-azurerm/issues/8437

=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_basic
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_basic
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_basic
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_basic (195.94s)
=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_requiresImport
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_requiresImport
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_requiresImport
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_requiresImport (244.87s)
=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_complete
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_complete
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_complete
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_complete (175.96s)
=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_update
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_update
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_update
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_update (280.84s)
=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall (290.78s)
PASS

Process finished with exit code 0

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @yupwei68, this is looking good but I'm seeing issues with `TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall`. Terraform wants to update `storage_endpoint`.
```
storage_endpoint:  "" => "https://unlikely23exst2acctaae1z.blob.core.windows.net/"
```

It looks like we'll want to wait for a specific state as the resource goes down when updating the `storage_endpoint`.

```
"state": "Disabled",
"storageEndpoint": "",
```

and then comes back up later down the line
```
"state": "Enabled",
"storageEndpoint": "faketesturl",
```

Terraform doesn't catch it though so we should add a WaitforState and make sure the resource is `Enabled` before passing it on to the read method.

**Comment by yupwei68** [comment]
@mbfrahry Sorry, I forgot the server auditing creation is async, I'll change it.

**Comment by yupwei68** [comment]
@mbfrahry Thanks for your comments. I've retested them. Please continue reviewing

=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_basic
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_basic
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_basic
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_basic (325.85s)
=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_requiresImport
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_requiresImport
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_requiresImport
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_requiresImport (259.68s)
=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_complete
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_complete
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_complete
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_complete (357.87s)
=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_update
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_update
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_update
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_update (650.06s)
=== RUN   TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall
=== PAUSE TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall
=== CONT  TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall
--- PASS: TestAccAzureRMMsSqlServerExtendedAuditingPolicy_storageAccBehindFireWall (454.10s)
PASS

Process finished with exit code 0

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks @yupwei68

**Pull request merged**
