### PR TITLE
App Service Plan: support for attaching to an App Service Environment

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Unfortunately as we don't support creating App Service Environments in Terraform yet (they take 1.5-2 hours to provision) - I can't add a test for this behaviour at the current time.. 

I've got a branch with some initial scaffolding for App Service Environments, but testing it is kind of painful - but I'd hope that we should be able to add support for this in the near future, when we do - I'll be sure to add some tests for this retroactively

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Manual confirmation that attaching to a V1 App Service Environment works ✅

**Comment by tombuildsstuff** [comment]
App Service Plan Resource tests pass:

screen shot 2018-02-16 at 16 29 11

App Service Plan Data Source tests pass:

```
$ acctests azurerm TestAccDataSourceAzureRMAppServicePlan_
=== RUN   TestAccDataSourceAzureRMAppServicePlan_basic
--- PASS: TestAccDataSourceAzureRMAppServicePlan_basic (89.57s)
=== RUN   TestAccDataSourceAzureRMAppServicePlan_complete
--- PASS: TestAccDataSourceAzureRMAppServicePlan_complete (65.87s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	155.471s
```

**Comment by tombuildsstuff** [comment]
Fixes #712

**Comment by davidlbyrne** [comment]
I have started to create IaC with terraform and we have been hung up on the Azure ASE integration. 

When I don't specify the key for maximum_number_of_workers I get this error: 
azurerm_app_service_plan.ilbase-plan: 
Status=400 Code="BadRequest" Message="NumberOfWorkers is invalid."

When I add it into the properties block: 
azurerm_app_service_plan.ilbase-plan: properties.0: invalid or unknown key: maximum_number_of_workers

Maybe I don't understand how this is supposed to work. Any help would be greatly appreciated.

**Pull request merged**
