### PR TITLE
Update `azurerm_linux|windows_virtual_machine` - enable update for `proximity_placement_group_id`

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/11515

### CODE REVIEW

**Comment by katbyte** [comment]
could we fix this build up?
```
	[Step 4/5] # github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute_test [github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.test]
[16:27:32]	[Step 4/5] ./linux_virtual_machine_resource_scaling_test.go:112:28: undefined: resource
[16:27:32]	[Step 4/5] ./linux_virtual_machine_resource_scaling_test.go:134:28: undefined: resource
[16:27:32]	[Step 4/5] ./windows_virtual_machine_resource_scaling_test.go:128:28: undefined: resource
[16:27:32]	[Step 4/5] ./windows_virtual_machine_resource_scaling_test.go:154:28: undefined: resource
[16:28:20]	[Step 4/5] Process exited with code 2
```

**Comment by ArcturusZhang** [comment]
Hi @katbyte sorry for the delay of response. I have fixed the compile errors in the test cases. Please have a look again

**Comment by katbyte** [comment]
thanks, running the tests for this there are a lot of failures.. could we possibly fix some of them up so its more apparent if this is causing any issues?

image


thanks

**Comment by ArcturusZhang** [comment]
The failed test cases does not have assigned the ppg attribute, and the only thing changed in this PR is the update function for ppg, therefore I assume those should be irrelevant.

**Comment by ArcturusZhang** [comment]
Just checked TC, those test cases have been failing on master branch

**Review by katbyte — APPROVED** [review]
notes, i'd still like those tests to get fixed up so future PRs are more easily checked - changes LGTM ✅

**Pull request merged**
