### PR TITLE
Use BlobContainersClient for blob container operations

### PR DESCRIPTION
**Pull request by DSakura207**
The pull request replaces custom storage blob container client `giovanni` with the one from Azure Go SDK.
Functions and tests are duplicated from `giovanni` for generating and parsing ID for a blob container, to ensure backward compatibility. Several local functions are added to container resource file to limit changes to local file.

Also `testAccAzureRMStorageContainer_basicAzureADAuth` is changed since the provider blocks are duplicated. `strings.Replace` looks dirty, so I am open to any suggestion to avoid it. 

With those effort, #2977 is possible to fix and containers could have immutability policy and legal holds.

Last but not least, thank you @tombuildsstuff for the custom storage client. It is a great work.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hi @DSakura207 

Thanks for this PR.

Taking a look through whilst on the whole the code for this looks pretty good, unfortunately due to the way the Azure Storage API's (and Storage Permissions work) this approach isn't going to work for most users.

At this point in time Azure Storage supports two different methods for authentication - using the (Shared) Access Key and AzureAD authentication - where this PR now only supports authenticating using AzureAD authentication ([configured here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/6147/files#diff-4ba1726ed3c7657eea626dfc5eaf61c2R49)).

Whilst at first glance this sounds like it should be fine - unfortunately the rollout of the new Azure Storage Permissions has been done in such a way it's caused a large amount of user confusion; such that when we previously defaulted to using AzureAD authentication for Storage and it turns out that most users don't have this permission enabled by default.

After a ton of investigation into this, it appears the way the new Storage Permissions have been rolled out is inconsistent, insofar as new Role Assignments (for say Contributor/Owner) also get assigned the new Storage Permissions - however older/existing Role Assignments at these same permissions do not. Ultimately this meant that when we defaulted to AzureAD authentication last time this caused a considerable amount of confusion amongst users since this differentiation was unclear.

Fundamentally there are 3 main differences between the Storage Data Plane & Storage Resource Manager API's of note here:

* The Resource Manager API's only support authenticating using AzureAD (and not Shared Key authorization)
* The Resource Manager API's don't support managing Blobs (amongst other functionality) - and likely won't anytime soon, since ARM has a 4MB payload limit
* The Identifiers for the Storage Resources are different between the two - for example: `https://{account}.blob.{domain}/{container}` and `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}/blobServices/default/containers/{containerName}`.

Ultimately I believe we're going to have to continue using the Giovanni SDK (since we need Shared Key authorization) for the foreseeable future. However to be able to fix #2977 requires using the Resource Manager API's - as such I believe we need to take a slightly different approach here.

Perhaps the best way to get this working would be a wrapper around Giovanni/the Resource Manager API's that conditionally calls them, but maintains the Data Plane ID's - WDYT?

Thanks!

**Comment by DSakura207** [comment]
Hello @tombuildsstuff ,

Thank you for the reply. I replaced blob container client because when Terraform runs on Azure Pipelines (Microsoft's CI/CD service) hosted agent, `resourceArmStorageContainerRead` returns 403 error when used 2.1.0 provider. When I switched to `BlobContainersClient` it succeeded.

After a second thought, it maybe caused by the role assignment you said. However the fun is that it succeeded when I run it locally with the same service principal but manually created secret.

A wrapper seems to be the solution. Let me see what I can do.

**Comment by DSakura207** [comment]
Added wrapper and retry, rebased onto newest master, and fixed lint errors.

Now the client does:
- When storage is not set to authenticate with Azure AD
  - Use giovanni for all actions.
  - When an action failed, try to use Azure client to do the same thing.
- When storage is set to authenticate with Azure AD
  - Only uses Azure client.

Hopefully this is okay, since I have to repeat some code for the retry operation.

**Comment by DSakura207** [comment]
@tombuildsstuff can you review code please?

**Comment by tombuildsstuff** [comment]
hey @DSakura207

Thanks for this PR - apologies for the delayed review here.

I've recently opened #9314 which adds a shim layer to the Storage Data Plane resources (Container, File Share, Queues, Tables) - which will allow users to opt to use either the Data Plane or the Resource Manager API, depending on the permissions available.

As a part of that work I've also looked to implement the Resource Manager shim for these resources - unfortunately it appears that the Resource Manager API is missing a significant amount of functionality present in the Data Plane API.

Ultimately this means at this time only the Containers functionality can be switched over to the Resource Manager API - since this is the only one of the 4 which contains the same functionality in both API's. I've raised these issues with Microsoft and they'll be run down internally - when this is available we should be able to implement the resource manager toggle for these resources.

As such, whilst I'd like to thank you for this contribution - and apologies for the delayed review time here - I'm going to close this PR in favour of #9314, which once merged enables us to support this functionality via a Feature Toggle, meaning users can move across gradually rather than introducing a breaking permissions change here.

Thanks!

**Pull request closed without merging**
