### PR TITLE
:pencil: Update postgresql_server doc to fit new layout

### PR DESCRIPTION
**Pull request by bgauduch**
* Move the storage config outside of deprecated storage_profile block
* Updated properties values to boolean in exemple for `geo_redundant_backup` and `ssl_enforcement`

### CODE REVIEW

**Comment by danryc** [comment]
it loks like duplicate to: #6670

**Comment by danryc** [comment]
but thanks to you I have discovered this issue also in another documents: #6685

**Comment by bgauduch** [comment]
Yeah sorry @danryc did a quick search but didn't see #6670 before opening this one 😅 

From what I can see, #6670 miss the documentation update on the `ssl_enforcement_enabled`field, but you did it on #6685 so it's all good !

**Comment by danryc** [comment]
Yep, I forgot about updating Argument Reference section also and your PR remind me about that :) Additionally I also found that related documents have Example Usage section that needs correction. Thank you!

**Comment by jackofallops** [comment]
Closing as covered more comprehensively in #6685

**Comment by bgauduch** [comment]
@danryc all good then 👌
You are welcome !

Thx @jackofallops for closing this PR 👍

**Comment by jackofallops** [comment]
> @danryc all good then 👌
> You are welcome !
> 
> Thx @jackofallops for closing this PR 👍

Thank you for the contribution efforts 😄

**Pull request closed without merging**
