### PR TITLE
`azurerm_mssql_database ` - error when secondary database uses `max_size_gb`

### PR DESCRIPTION
**Pull request by aristosvo**
@katbyte I introduced a bug in #11286 :(

Because `max_size_gb` is `Computed`, `GetOk("max_size_gb")` is not empty in a second run. I added `HasChange("max_size_gb")` as an extra check before I throw an error to fix it.

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @aristosvo! Can we confirm this fix through a test? We want to make sure that this change is broken in the current version of the provider and that it'll be fixed in the next version of the provider.

**Comment by aristosvo** [comment]
Sure! I had a hard time reproducing the issue in the first place, but I'll try!!

**Comment by aristosvo** [comment]
@mbfrahry how can I make sure a certain version in the test? When I do a `make build` the latest version from master is used (it seems at least that way)

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for getting this written out into a test!

**Pull request merged**
