### PR TITLE
refactor: updating the remaining importers to use Plugin SDKv2 wrappers

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR updates the remaining importers to use the Plugin SDKv2 wrapper for importers - meaning that these changes are scoped to that package

### CODE REVIEW

**Review by favoretti — APPROVED** [review]
Awesome, thank you! 👍🏻

**Review by katbyte — APPROVED** [review]
LGTM 👍

**Comment by favoretti** [comment]
Lint's not happy?

**Comment by tombuildsstuff** [comment]
@favoretti fixed locally, just waiting for the linter to confirm 👍

**Pull request merged**
