### PR TITLE
azurerm_ssh_public_key: Support generating ssh key pair

### LINKED ISSUE #11823: Support for generating ssh key pair in azurerm_ssh_public_key
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current implementation of `azurerm_ssh_public_key` doesn't support generating a key. Azure API lets you generate a key pair that includes:

* public key resource
* private key (azure doesn't store this, but the API returns it)

I'm not sure exactly how to deal with the private key. Can it be exported as an attribute and stored in state?

### New or Affected Resource(s)

* azurerm_ssh_public_key

### Potential Terraform Configuration

```hcl
resource "azurerm_ssh_public_key" "example" {
  name                = "example"
  resource_group_name = "example"
  location            = "West Europe"
  generate_key        = true
}
```

### References

* #9822
* https://docs.microsoft.com/en-us/rest/api/compute/sshpublickeys/generatekeypair

### PR DESCRIPTION
**Pull request by AliAllomani**
Fixes #11823

```
make acctests SERVICE="compute" TESTARGS="-run=TestAccSshPublicKey_Generate"
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/compute -run=TestAccSshPublicKey_Generate -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/05/23 02:51:24 [DEBUG] not using binary driver name, it's no longer needed
2021/05/23 02:51:25 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccSshPublicKey_Generate
=== PAUSE TestAccSshPublicKey_Generate
=== CONT  TestAccSshPublicKey_Generate
--- PASS: TestAccSshPublicKey_Generate (117.37s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute     120.434s
```
```
make acctests SERVICE="compute" TESTARGS="-run=TestAccSshPublicKey_CreateUpdate"
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/compute -run=TestAccSshPublicKey_CreateUpdate -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/05/23 02:47:59 [DEBUG] not using binary driver name, it's no longer needed
2021/05/23 02:47:59 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccSshPublicKey_CreateUpdate
=== PAUSE TestAccSshPublicKey_CreateUpdate
=== CONT  TestAccSshPublicKey_CreateUpdate
--- PASS: TestAccSshPublicKey_CreateUpdate (168.47s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute     171.252s
```

### CODE REVIEW

**Comment by magodo** [comment]
@AliAllomani Thank you for this PR!

Adding a hypothetic property `generate_key_pair` works for creation, whilst it doesn't work for importing use cases, where your acctest is persumably failing if adding a `ImportStep` check. As you have already mentioned in this [comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/11823#issuecomment-846486413), the functionality can be met by using the `tls_private_key` resource, so I would prefer to that solution.

**Comment by AliAllomani** [comment]
@magodo Yeah that makes sense.

@amasover Can you think of a use-case where generating the key pair by azure would have a benefit over generating it by another resource such tls_private_key ?

**Comment by amasover** [comment]
I'll admit in advance, the use case I had in mind is a little odd.

I want to generate a valid public key, but I don't want to have to care about the private key.

Specifically I want a virtual machine with only the `AADSSHLoginForLinux` extension installed. But in order to set up a VM with password login turned off, I need to supply an SSH public key for login. The thing is, I never intend to login to this machine with the supplied public key, since I'll always be using Azure AD SSH login.

If I could have Azure generate a public key, then I don't necessarily have to store the private key in my Terraform state (basically, I don't need the private key at all, so why worry about protecting it?)

But even if we merge this PR, as long as `private_key` is an exported attribute, I'd be back in the same boat.

I think @magodo is definitely correct that adding this as-is would break imports. If this functionality is something we want, then I wonder if something like this would work:

* Don't have a `generate_key_pair` flag, instead decide to generate based on whether `public key is supplied`
* Maybe don't output `private_key`? Not sure if there are other use cases where you do want a `private_key` output (but don't want to use the `tls_private_key` resource to get it).

I tested out removing `generate_key_pair` on a branch, and imports do work fine (though Update step would probably need some attention).

@AliAllomani thank you very much for your effort in putting this PR together, and please accept my apologies if this doesn't end up going anywhere. I don't think I had fully thought everything through when I created the issue.

**Comment by amasover** [comment]
Sounds good @AliAllomani, I will go ahead and close the corresponding issue.

**Pull request closed without merging**
