### PR TITLE
`azurerm_key_vault_certificate_data`: Support certificate bundles and add support for ECDSA keys

### LINKED ISSUE #10909: Error: decoding certificate ("xyz"): pkcs12: expected exactly two safe bags in the PFX PDU
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_key_vault_certificate_data`

### Terraform Configuration Files

```hcl
data "azurerm_key_vault" "xxx" {
  name                = "xxx" 
  resource_group_name = "mygroup"
}

data "azurerm_key_vault_certificate_data" "xyz" {
  name         = "xyz"
  key_vault_id = data.azurerm_key_vault.xxx.id
}
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by favoretti**
Potentially fixes #10909

### CODE REVIEW

**Comment by favoretti** [comment]
At least I haven't broken current acceptance test :)
```
$ TF_ACC=1 go test -v ./azurerm/internal/services/keyvault -timeout=1000m -run='TestAccDataSourceKeyVaultCertificateData_basic'
2021/05/26 21:33:43 [DEBUG] not using binary driver name, it's no longer needed
2021/05/26 21:33:43 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccDataSourceKeyVaultCertificateData_basic
=== PAUSE TestAccDataSourceKeyVaultCertificateData_basic
=== CONT  TestAccDataSourceKeyVaultCertificateData_basic
--- PASS: TestAccDataSourceKeyVaultCertificateData_basic (343.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/keyvault	344.729s
```

Will work on adding tests for new use-cases shortly.

**Comment by favoretti** [comment]
```
$ TF_ACC=1 go test -v ./azurerm/internal/services/keyvault -timeout=1000m -run='TestAccDataSourceKeyVaultCertificateData'
2021/05/26 23:08:16 [DEBUG] not using binary driver name, it's no longer needed
2021/05/26 23:08:16 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccDataSourceKeyVaultCertificateData_basic
=== PAUSE TestAccDataSourceKeyVaultCertificateData_basic
=== RUN   TestAccDataSourceKeyVaultCertificateData_ecdsa_PFX
=== PAUSE TestAccDataSourceKeyVaultCertificateData_ecdsa_PFX
=== RUN   TestAccDataSourceKeyVaultCertificateData_ecdsa_PEM
=== PAUSE TestAccDataSourceKeyVaultCertificateData_ecdsa_PEM
=== RUN   TestAccDataSourceKeyVaultCertificateData_rsa_bundle_PEM
=== PAUSE TestAccDataSourceKeyVaultCertificateData_rsa_bundle_PEM
=== RUN   TestAccDataSourceKeyVaultCertificateData_rsa_single_PEM
=== PAUSE TestAccDataSourceKeyVaultCertificateData_rsa_single_PEM
=== RUN   TestAccDataSourceKeyVaultCertificateData_rsa_bundle_PFX
=== PAUSE TestAccDataSourceKeyVaultCertificateData_rsa_bundle_PFX
=== CONT  TestAccDataSourceKeyVaultCertificateData_basic
=== CONT  TestAccDataSourceKeyVaultCertificateData_rsa_single_PEM
=== CONT  TestAccDataSourceKeyVaultCertificateData_ecdsa_PEM
=== CONT  TestAccDataSourceKeyVaultCertificateData_rsa_bundle_PFX
=== CONT  TestAccDataSourceKeyVaultCertificateData_rsa_bundle_PEM
=== CONT  TestAccDataSourceKeyVaultCertificateData_ecdsa_PFX
--- PASS: TestAccDataSourceKeyVaultCertificateData_ecdsa_PFX (330.67s)
--- PASS: TestAccDataSourceKeyVaultCertificateData_rsa_bundle_PEM (361.86s)
--- PASS: TestAccDataSourceKeyVaultCertificateData_ecdsa_PEM (362.05s)
--- PASS: TestAccDataSourceKeyVaultCertificateData_basic (362.23s)
--- PASS: TestAccDataSourceKeyVaultCertificateData_rsa_bundle_PFX (363.32s)
--- PASS: TestAccDataSourceKeyVaultCertificateData_rsa_single_PEM (366.27s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/keyvault	367.696s
```

**Comment by favoretti** [comment]
image
TC is a happy camper too.

**Review by katbyte — APPROVED** [review]
Thanks @favoretti - LGTM 👍

**Pull request merged**
