### PR TITLE
Update default value for allow_blob_public_access of azurerm_storage_account

### PR DESCRIPTION
**Pull request by neil-yechenwei**
fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/8187

### CODE REVIEW

**Comment by waynejnicklin** [comment]
This still seems to be an issue. I have allow_blob_public_access set to false in my infrastructure pipelines, and it deploys with "no change" and leaves it set to true when I check the storage account in the portal.

**Comment by neil-yechenwei** [comment]
Maybe there is some latency in Azure Portal. Seems all related test cases passed from my side after updated code.

**Comment by waynejnicklin** [comment]
I don't think it's a latency issue, I deployed weeks ago and it still hasn't changed! But I deployed the change into an existing storage account which had public blob access enabled... and it left it enabled. Maybe when deploying a new clean storage account, it works, but certainly trying to change an existing one doesn't.

**Comment by neil-yechenwei** [comment]
@waynejnicklin , maybe I missed something. Could you have a try with this PR since I just updated this PR? If you still encountered same issue, please let me know. Thanks.

**Comment by waynejnicklin** [comment]
Yes sure thank you :-)

**Comment by kevinharing** [comment]
What is taking so long to complete this?

**Comment by tombuildsstuff** [comment]
Closing in favour of #12689

**Pull request closed without merging**
