### PR TITLE
`azurerm_storage_account` `blob_properties` enhancement

### PR DESCRIPTION
**Pull request by yupwei68**
Fix:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/8268
https://github.com/terraform-providers/terraform-provider-azurerm/issues/7722
https://github.com/terraform-providers/terraform-provider-azurerm/issues/6627

=== RUN   TestAccAzureRMStorageAccount_blobProperties
=== PAUSE TestAccAzureRMStorageAccount_blobProperties
=== CONT  TestAccAzureRMStorageAccount_blobProperties
--- PASS: TestAccAzureRMStorageAccount_blobProperties (625.53s)
=== RUN   TestAccAzureRMStorageAccount_blobPropertiesWithSoftDeleteContainerEnabled
=== PAUSE TestAccAzureRMStorageAccount_blobPropertiesWithSoftDeleteContainerEnabled
=== CONT  TestAccAzureRMStorageAccount_blobPropertiesWithSoftDeleteContainerEnabled
--- PASS: TestAccAzureRMStorageAccount_blobPropertiesWithSoftDeleteContainerEnabled (564.82s)

### CODE REVIEW

**Comment by aristosvo** [comment]
Did you by any chance read the conversation I had with @tombuildsstuff about this functionality on Slack? He mentioned we (probably) need a toggle between data plane API and resource manager APIs (or in any case some kind of check if the right permissions are available) for managing the storage accounts with proper warnings and/or to not break backwards compatibility.

Is that problem already solved?

**Comment by yupwei68** [comment]
@aristosvo However, Blob Service always uses mgmt plan. It should not exist problems for the enhancement of mgmt plan.

**Comment by yupwei68** [comment]
All regression tests have passed.

**Comment by tombuildsstuff** [comment]
@yupwei68 taking a quick look through this is missing the integration tests we discussed - could we add those too?

**Comment by tombuildsstuff** [comment]
@yupwei68 actually taking a look through unfortunately this approach won't work for existing users, as @aristosvo has mentioned above, so this'll likely need to wait for the storage shim as we've discussed previously?

**Comment by yupwei68** [comment]
@tombuildsstuff  The integration test means that when soft-delete enabled, we do a create , delete and create again for container? As for blob service, blobService always uses mgmt plan BlobServicesClient, we have not changed the client, it doesn't users, right?

**Comment by yupwei68** [comment]
Add container soft-delete test.
=== RUN   TestAccAzureRMStorageAccount_containerSoftDelete
=== PAUSE TestAccAzureRMStorageAccount_containerSoftDelete
=== CONT  TestAccAzureRMStorageAccount_containerSoftDelete
--- PASS: TestAccAzureRMStorageAccount_containerSoftDelete (222.21s)

**Comment by yupwei68** [comment]
I've merged the master branch. Please continue reviewing. 
=== RUN   TestAccAzureRMStorageAccount_blobProperties
=== PAUSE TestAccAzureRMStorageAccount_blobProperties
=== CONT  TestAccAzureRMStorageAccount_blobProperties
--- PASS: TestAccAzureRMStorageAccount_blobProperties (545.93s)
=== RUN   TestAccAzureRMStorageAccount_containerSoftDelete
=== PAUSE TestAccAzureRMStorageAccount_containerSoftDelete
=== CONT  TestAccAzureRMStorageAccount_containerSoftDelete
--- PASS: TestAccAzureRMStorageAccount_containerSoftDelete (192.18s)
=== RUN   TestAccAzureRMStorageAccount_blobSoftDelete
=== PAUSE TestAccAzureRMStorageAccount_blobSoftDelete
=== CONT  TestAccAzureRMStorageAccount_blobSoftDelete
--- PASS: TestAccAzureRMStorageAccount_blobSoftDelete (205.95s)

**Comment by yupwei68** [comment]
Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/9020

**Comment by Nordes** [comment]
Hi here, does anyone knows when this will be merged and released within the main branch?

**Comment by tombuildsstuff** [comment]
@yupwei68 is there any update from the Service Team on the permissions issues we've previously raised?

**Comment by drr1217** [comment]
@yupwei68 This looks great! Do you know when this will be released for general use?

**Comment by dhensby** [comment]
Looks like this needs a rebase as `container_delete_retention_policy` has been merged in a separate PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/11131

**Comment by yupwei68** [comment]
close for https://github.com/terraform-providers/terraform-provider-azurerm/pull/11301

**Pull request closed without merging**
