### PR TITLE
Parallelize acceptance tests

### PR DESCRIPTION
**Pull request by katbyte**

### CODE REVIEW

**Comment by metacpp** [comment]
Code changes LGTM.

**Comment by katbyte** [comment]
@metacpp,

same command as before:

```shell
[11:39:06] kt@snowbook:~/hashi/..3../terraform-providers/terraform-provider-azurerm$ make testacc TEST=./azurerm TESTARGS=-test.run=TestAccAzureRMPublicIpStatic_basic
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccAzureRMPublicIpStatic_basic -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMPublicIpStatic_basic
=== PAUSE TestAccAzureRMPublicIpStatic_basic
=== RUN   TestAccAzureRMPublicIpStatic_basic_withDNSLabel
=== PAUSE TestAccAzureRMPublicIpStatic_basic_withDNSLabel
=== RUN   TestAccAzureRMPublicIpStatic_basic_defaultsToIPv4
=== PAUSE TestAccAzureRMPublicIpStatic_basic_defaultsToIPv4
=== RUN   TestAccAzureRMPublicIpStatic_basic_withIPv4
=== PAUSE TestAccAzureRMPublicIpStatic_basic_withIPv4
=== CONT  TestAccAzureRMPublicIpStatic_basic
=== CONT  TestAccAzureRMPublicIpStatic_basic_withIPv4
=== CONT  TestAccAzureRMPublicIpStatic_basic_defaultsToIPv4
=== CONT  TestAccAzureRMPublicIpStatic_basic_withDNSLabel
--- PASS: TestAccAzureRMPublicIpStatic_basic_withDNSLabel (102.06s)
--- PASS: TestAccAzureRMPublicIpStatic_basic_defaultsToIPv4 (104.27s)
--- PASS: TestAccAzureRMPublicIpStatic_basic (104.68s)
--- PASS: TestAccAzureRMPublicIpStatic_basic_withIPv4 (108.96s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	109.399s
[11:41:09] kt@snowbook:~/hashi/..3../terraform-providers/terraform-provider-azurerm$
```

**Comment by metacpp** [comment]
`go test -json` seems to be the only way to attach test case name info to each line of output, which should be useful for grouping processing even if `TF_LOG=INFO`.

**Comment by katbyte** [comment]
Teamcity tests look good too 👍

**Pull request merged**
