### PR TITLE
dependencies - Update azure-sdk-for-go to v46.0.0

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Also update the api-version in network to 2020-06-01 to fix the WAF issue.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Running the tests it appears there's breaking changes in Compute here, will dig in next week

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
Looks like there's a breaking change here for API Management:

```
------- Stdout: -------
=== RUN   TestAccAzureRMApiManagementLogger_basicEventHub
=== PAUSE TestAccAzureRMApiManagementLogger_basicEventHub
=== CONT  TestAccAzureRMApiManagementLogger_basicEventHub
TestAccAzureRMApiManagementLogger_basicEventHub: testing.go:684: Step 0 error: errors during apply:
Error: creating Logger "acctestapimnglogger-200904145153015799" (Resource Group "acctestRG-200904145153015799" / API Management Service "acctestAM-200904145153015799"): apimanagement.LoggerClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="Validation failed for logger-id 'acctestapimnglogger-200904145153015799'. Exception Received 'An error occurred during communication with 'N/A'. Check the connection information, then retry.'"
(source code not available)
--- FAIL: TestAccAzureRMApiManagementLogger_basicEventHub (2505.68s)
FAIL
```

It also appears the Networking API upgrade breaks both Virtual Hubs and Virtual Network Connections - as such we'll need to downgrade this back to 2020-05 and wait for the fix to be merged.

**Comment by tombuildsstuff** [comment]
👋🏼

Thinking about this, since SDKv46 appears to be broken in multiple different ways here, I'm going to close this PR for the moment, since this is otherwise going to end up with merge conflicts as other items get merged. Once the PR to fix the 2020-05 Swagger has been fixed, we can upgrade the SDK to that without upgrading the Networking API version and then upgrade the Networking API at a later days when there's a working version of this API.

Thanks!

**Comment by ArcturusZhang** [comment]
Well, this test could pass on my side, maybe it just panics occasionally...
image
I will dig further into the other problems in apimanagement

**Pull request closed without merging**
