### PR TITLE
r/monitor_diagnostic_setting: adding validation/ensuring the casing of the resource id's

### LINKED ISSUE #9913: Unable to import azurerm_monitor_diagnostic_setting cleanly
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/azurerm v2.40.0

```

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "0.14.2"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.40.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

resource "azurerm_resource_group" "main" {
  name     = "diagnostictest-rg"
  location = "westeurope"
}

resource "azurerm_log_analytics_workspace" "main" {
  name                = "diagnostictest-log"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "PerGB2018"
}

data "azurerm_subscription" "current" {
}

resource "azurerm_key_vault" "main" {
  name                       = "diagnostictest-kv"
  location                   = azurerm_resource_group.main.location
  resource_group_name        = azurerm_resource_group.main.name
  sku_name                   = "standard"
  tenant_id                  = data.azurerm_subscription.current.tenant_id
  soft_delete_enabled        = true
  soft_delete_retention_days = 7
  purge_protection_enabled   = false

}

#resource "azurerm_monitor_diagnostic_setting" "vault" {
#  name                       = "diagnostictest-setting"
#  target_resource_id         = azurerm_key_vault.main.id
#  log_analytics_workspace_id = azurerm_log_analytics_workspace.main.id
#
#  log {
#    category = "AuditEvent"
#
#    retention_policy {
#      enabled = false
#    }
#  }
#
#  metric {
#    category = "AllMetrics"
#    retention_policy {
#      enabled = false
#    }
#  }
#}

```

### Debug Output

Can be provided upon request

### Panic Output

No crash experienced

### Expected Behaviour

After import of manually created diagnostic setting, terraform plan should not show any changes.

### Actual Behaviour

Terraform wants to destroy and recreate the resource due to case difference in `log_analytics_workspace_id` making import fairly pointless.

```
azurerm_resource_group.main: Refreshing state... [id=/subscriptions/<subscription id>/resourceGroups/diagnostictest-rg]
azurerm_log_analytics_workspace.main: Refreshing state... [id=/subscriptions/<subscription id>/resourceGroups/diagnostictest-rg/providers/Microsoft.OperationalInsights/workspaces/diagnostictest-log]
azurerm_key_vault.main: Refreshing state... [id=/subscriptions/<subscription id>/resourceGroups/diagnostictest-rg/providers/Microsoft.KeyVault/vaults/diagnostictest-kv]
azurerm_monitor_diagnostic_setting.vault: Refreshing state... [id=/subscriptions/<subscription id>/resourceGroups/diagnostictest-rg/providers/Microsoft.KeyVault/vaults/diagnostictest-kv|diagnostictest-setting]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_monitor_diagnostic_setting.vault must be replaced
-/+ resource "azurerm_monitor_diagnostic_setting" "vault" {
      ~ id                         = "/subscriptions/<subscription id>/resourceGroups/diagnostictest-rg/providers/Microsoft.KeyVault/vaults/diagnostictest-kv|diagnostictest-setting" -> (known after apply)
      ~ log_analytics_workspace_id = "/subscriptions/<subscription id>/resourcegroups/diagnostictest-rg/providers/microsoft.operationalinsights/workspaces/diagnostictest-log" -> "/subscriptions/<subscription id>/resourceGroups/diagnostictest-rg/providers/Microsoft.OperationalInsights/workspaces/diagnostictest-log" # forces replacement
        name                       = "diagnostictest-setting"
        # (1 unchanged attribute hidden)

      - log {
          - category = "AuditEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      + log {
          + category = "AuditEvent"
          + enabled  = true

          + retention_policy {
              + enabled = false
            }
        }

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      + metric {
          + category = "AllMetrics"
          + enabled  = true

          + retention_policy {
              + enabled = false
            }
        }

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Steps to Reproduce

1. `terraform apply -auto-approve`
2. Manually configure diagnostics via the portal with the same name and destination workspace as expected by the commented out config
3. Uncomment azurerm_monitor_diagnostic_setting resource
4. `terraform import azurerm_monitor_diagnostic_setting.vault "/subscriptions/<your subscription id>/resourceGroups/diagnostictest-rg/providers/Microsoft.KeyVault/vaults/diagnostictest-kv|diagnostictest-setting"`
5. `terraform plan`

### Important Factoids

This scenario is representative of a real case where we manually configured some diagnostics after realising they were missing in prod setup, then I've now spent the time working out the correct terraform config to manage this properly and would like to import the config.

I have two workarounds for the issue;
1. Delete the diagnostics manually before running terraform (mild pita with the quantity of diagnostics I'm adding, bit no worse than importing all the resources at the end of the day).
2. Allow terraform to recreate, the new resource gets the casing expected by the provider... I naïvely assume the short time under recreation this will not lead to any lost logs.

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Fixes #9913

### CODE REVIEW

**Review by manicminer — APPROVED** [review]
LGTM 👍

**Comment by kinzleb** [comment]
After I upgraded from 2.41.0 to 2.42.0 I'm now getting a difference detected every time I generate a plan -- it looks like differences in character casing of the value for log_analytics_workspace_id is causing it.  Is it possible this change introduced that?

**Comment by kinzleb** [comment]
Interesting... I read through what this change is fixing and it seemed to cause the problem it was intended to fix in my situation.  I manually created the Log Analytics Workspace using the portal and am using the data source for azurerm_log_analytics_workspace to get the ID of it, I'm then using that ID for the log_analytics_workspace_id attribute when creating a resource of type azurerm_monitor_diagnostic_setting and am seeing the behavior where it detects a difference every time I 'terraform plan/apply' because of the casing.  Same is true for a azurerm_kubernetes_cluster resource where I'm also using that ID for the oms_agent.log_analytics_workspace_id.

**Comment by sharebear** [comment]
@kinzleb Have you seen #10116? Sounds like that would be the right place to follow for a fix

**Comment by kinzleb** [comment]
> @kinzleb Have you seen #10116? Sounds like that would be the right place to follow for a fix

That's exactly my issue, thanks for pointing that out @sharebear !

**Pull request merged**
