### PR TITLE
Support for `high_availability` in `azurerm_postgresql_flexible_server`

### PR DESCRIPTION
**Pull request by yupwei68**
Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/12200

### CODE REVIEW

**Comment by manicminer** [comment]
Thanks @yupwei68, this is looking good. I'm getting a test failure with `TestAccPostgresqlflexibleServer_completeUpdate`, could you take a look? I'm not sure if the API is slow to reflect, or if `GeoRedundantBackup` is not being set correctly in step 3.

```
        testcase.go:89: Step 3/4 error: After applying this test step, the plan was not empty.
            stdout:
            
            
            Terraform used the selected providers to generate the following execution
            plan. Resource actions are indicated with the following symbols:
              ~ update in-place
            
            Terraform will perform the following actions:
            
              # azurerm_postgresql_flexible_server.test will be updated in-place
              ~ resource "azurerm_postgresql_flexible_server" "test" {
                  ~ geo_redundant_backup_enabled  = true -> false
                    id                            = "/subscriptions/*******/resourceGroups/acctestRG-postgresql-210715130725431885/providers/Microsoft.DBforPostgreSQL/flexibleServers/acctest-fs-210715130725431885"
                    name                          = "acctest-fs-210715130725431885"
                    tags                          = {
                        "ENV" = "Stage"
                    }
                    # (13 unchanged attributes hidden)
            
                    # (1 unchanged block hidden)
                }
            
            Plan: 0 to add, 1 to change, 0 to destroy.
    --- FAIL: TestAccPostgresqlflexibleServer_completeUpdate (1861.10s)
```

**Comment by yupwei68** [comment]
Thanks @manicminer . It used to pass. But now I can reproduce this problem. I'm tracking this with the service team.

**Comment by yupwei68** [comment]
Hi @manicminer , the service said that `geoReduntBackup` is not ready for releasing. So I've removed this field in this PR

**Review by manicminer — APPROVED** [review]
LGTM, thanks @yupwei68 👍 

Screenshot 2021-07-17 at 00 46 14

**Pull request merged**
