### PR TITLE
azurerm_data_factory_dataset_delimited_text: Add `compression_type`

### LINKED ISSUE #9980: Support for compression type in azurerm_data_factory_dataset_delimited_text
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The DelimitedText dataset on Azure supports has a compression type setting (see also https://docs.microsoft.com/en-us/azure/data-factory/format-delimited-text#dataset-properties).
As far as I can see in the documentation and also the source code of the resource implementation, this is currently not supported by azurerm_data_factory_dataset_delimited_text.

### New or Affected Resource(s)

* azurerm_data_factory_dataset_delimited_text 

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.microsoft.com/en-us/azure/data-factory/format-delimited-text#dataset-properties

### PR DESCRIPTION
**Pull request by brunhil**
Fixes #9980 

Add parsers and validators for data-set and this resource. Follow on PR will update other DataSet resources to use the new parser

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the PR @brunhil - looks good except we have one failing test:

```
------- Stdout: -------
=== RUN   TestAccAzureRMDataFactoryDatasetDelimitedText_http_update
=== PAUSE TestAccAzureRMDataFactoryDatasetDelimitedText_http_update
=== CONT  TestAccAzureRMDataFactoryDatasetDelimitedText_http_update
    testing.go:684: Step 2 error: Check failed: Check 7/7 error: azurerm_data_factory_dataset_delimited_text.test: Attribute 'compression_level' expected "Optimal", got ""
--- FAIL: TestAccAzureRMDataFactoryDatasetDelimitedText_http_update (141.91s)
FAIL
``
once thats fixed this'll be good tomerge!

**Review by katbyte — APPROVED** [review]
Thanks @brunhil - LGTM aside from the merge conflict to address

**Comment by brunhil** [comment]
@katbyte - merge conflict should be resolved! I love the new test framework by the way! Super verbose and easy to understand what you're testing 😄

**Comment by katbyte** [comment]
:D

**Pull request merged**
