### PR TITLE
New Resource: `azurerm_data_factory_dataset_snowflake ` 

### PR DESCRIPTION
**Pull request by orestiskats19**
New Resource for Snowflake table in data factory service: `azurerm_data_factory_dataset_snowflake`.
Resolves issue #11051 .

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @orestiskats19! This PR is looking really good. I have a couple of asks from you and then we can merge it in!

**Comment by orestiskats19** [comment]
Hey @mbfrahry, thanks for reviewing my PR. I have made the changes that you suggested, let me know what you think 😃 .

**Review by mbfrahry — APPROVED** [review]
LGTM!

**Comment by mbfrahry** [comment]
Thanks for addressing the review @orestiskats19! It should go out in 2.57.0 of the provider

**Pull request merged**
