### PR TITLE
Added azure network policy for AKS

### PR DESCRIPTION
**Pull request by thatInfrastructureGuy**
Enabling `azure` network policy installs [Azure-NPM](https://github.com/Azure/azure-container-networking/tree/master/npm)

Signed-off-by: Ashish <thatInfrastructureGuy@gmail.com>

### CODE REVIEW

**Comment by thatInfrastructureGuy** [comment]
Fixes: https://github.com/terraform-providers/terraform-provider-azurerm/pull/2987#issuecomment-480242120
Source: https://github.com/MicrosoftDocs/azure-docs/issues/28567#issuecomment-479183385_

**Comment by tombuildsstuff** [comment]
hey @thatInfrastructureGuy 

Running the tests for this we get the following error (with an empty subscription):

> * azurerm_kubernetes_cluster.test: Error creating/updating Managed Kubernetes Cluster "acctestaks190409093336749031" (Resource Group "acctestRG-190409093336749031"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourceCountExceedsLimitDueToTemplate" Message="Provisioning of resource(s) for container service acctestaks190409093336749031 in resource group acctestRG-190409093336749031 failed. Message: Subscription 00000000-0000-0000-0000-000000000000 has a quota of 200 for resources of type RouteTable with sku SkuNotSpecified. Subscription currently has 200 resources and the template contains 1 new resources of the this type which exceeds the quota. Please contact support to increase the quota for resource type RouteTable. Details: []"

AKS itself deploys an ARM Template behind the scenes, so I believe this is a bug in that Template, but I may be wrong? Out of interest does this provision successfully for you?

Thanks!

**Comment by thatInfrastructureGuy** [comment]
@tombuildsstuff I believe Azure is complaining that quota limit of 200 route tables is reached. Can you please check number of route tables used:

`az network list-usages --location $ARM_LOCATION --out table`

I am not able to reproduce :

```
make testacc TESTARGS='-run=TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicy'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor'|grep -v 'examples') -v -run=TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicy -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
?       github.com/terraform-providers/terraform-provider-azurerm       [no test files]
=== RUN   TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicy
=== PAUSE TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicy
=== RUN   TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicyComplete
=== PAUSE TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicyComplete
=== CONT  TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicy
=== CONT  TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicyComplete
--- PASS: TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicyComplete (783.19s)
--- PASS: TestAccAzureRMKubernetesCluster_advancedNetworkingAzureNPMPolicy (783.19s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm       783.226s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/kubernetes    (cached) [no tests to run]
?       github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/response      [no test files]
?       github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/set   [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/suppress      (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf    (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate      (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils (cached) [no tests to run]
?       github.com/terraform-providers/terraform-provider-azurerm/version       [no test files]
```
Having said that, I have explicitly set  ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_ENVIRONMENT ARM_SUBSCRIPTION_ID, ARM_TENANT_ID, ARM_TEST_LOCATION, ARM_TEST_LOCATION_ALT

**Comment by thatInfrastructureGuy** [comment]
@tombuildsstuff Is there something I can assist with here? Just making sure this does not fall through the cracks :) 

Thanks.

**Comment by thatInfrastructureGuy** [comment]
Awesome. Thanks @katbyte

**Pull request merged**
