### PR TITLE
Support for workspace mode in application_insights_resource

### PR DESCRIPTION
**Pull request by dylanmorley**
As per issue #7667, updating the application_insights_resource to enable support of workspace mode, available with upgrade of the Go SDK at v55.5 via PR #12435. 

* Updated the insights API from 2015-05-01 to 2020-02-02-preview
* Fixed upgrade issues (enum changes )
* Supporting workspace ID as an optional parameter when creating AI resources
* Added workspace_id to data source resource
* Using ResourceClient to perform update of retention_in_days, if option is specified - see details in ticket #7667 for reasons. 
* Documentation updates

image

### CODE REVIEW

**Comment by dylanmorley** [comment]
Anyone picking up a review on this - I'd appreciate some eyes on this commit 

https://github.com/terraform-providers/terraform-provider-azurerm/pull/12583/commits/109f25c624951052fc6e25437383f342d79d0a27

[RetentionInDays ](https://github.com/dylanmorley/terraform-provider-azurerm/blob/89e51e3c91a45be908c5a090bdb61c602c7a93a7/vendor/github.com/Azure/azure-sdk-for-go/services/preview/appinsights/mgmt/2020-02-02-preview/insights/models.go#L814) became a read only property in this version of the insights API, so we needed a way of setting the value after creating the resource

Am using the ResourceClient against hardcoded API Value - better way to do this, or is this acceptable?

**Comment by manicminer** [comment]
Hi @dylanmorley, thanks for working on this long awaited feature. It is unfortunate that the `RetentionInDays` field became read-only - despite the clever workaround you have using ResourcesClient, there is no precedent for this elsewhere in the provider so I am hesitant to approve that approach.

However, at first glance everything else looks good if you can take a look at the failed checks? I'll get back to you on the retention workaround.

**Comment by manicminer** [comment]
@dylanmorley Unfortunately hacking around this with the resources client isn't an approach that we're comfortable with. I understand this feature has been outstanding for a long time but it's up to the API team to maintain compatibility and not break it in this way. Can you raise an issue upstream on https://github.com/Azure/azure-rest-api-specs and link it here? Once that's resolved, this should be in a position to be mergeable. Thanks!

**Comment by dylanmorley** [comment]
OK thanks @manicminer - wasn't that comfortable with it either, but wanted an opinion as data retention as an option is going to deprecate when [Microsoft make Workspace mode](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7667#issuecomment-784863375) the default and also deprecate 'classic mode'. Is there any general guidance on handling breaking changes / deprecations in the Terraform Azure provider?

It was removed as an [option on the ARM API](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2020-02-02-preview/components?tabs=json)  which is why I presume it [became read-only here ](https://github.com/Azure/azure-rest-api-specs/blob/bf2b04461fa9bca79ac65c502017b66c88a6aad1/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2020-02-02/components_API.json#L555)

I'm interested to understand the things that need to change in order to use a standard approach (Azure API / Go SDK?).  I'll fix failed checks in the meantime.

**Comment by manicminer** [comment]
@dylanmorley Another option might be to implement this in a new resource / data source, for example `azurerm_application_insights_workspace_mode` (just an initial suggestion). The new resource could potentially use the newer API and only support workspace mode, e.g. doesn't have the `retention_in_days` or other deprecated properties. This may or may not be feasible depending on how much dependency mess happens as a result.

At the same time, the existing (classic) resource `azurem_application_insights` should probably be deprecated. We should also test whether newly migrated workspaces (in the portal) can be imported to the new resource, and potentially whether importing a classic resource into the new resource will essentially migrate it via Terraform.

WDYT?

**Comment by dylanmorley** [comment]
@manicminer a new resource is probably the cleanest approach. Let's see if any opinions in #7667 

['Classic' doesn't retire until at 2024](https://azure.microsoft.com/en-us/updates/we-re-retiring-classic-application-insights-on-29-february-2024/), at what point would you retire + remove azurem_application_insights? Continue to support the resource type for at least the next 18 months, but point people to the new type in the documentation to encourage migration, similar to VM docs, i.e.

image

**Comment by dylanmorley** [comment]
@manicminer upstream dependencies fixed & I've updated this branch with the latest  - can we reopen this PR pls?

**Comment by timja** [comment]
> @manicminer upstream dependencies fixed & I've updated this branch with the latest - can we reopen this PR pls?

if you can't re-open probably best to just create a new one

**Comment by dylanmorley** [comment]
Opened #12818

**Pull request closed without merging**
