### PR TITLE
`postgres_server`: Update Postgres server admin password only on change

### LINKED ISSUE #12007: administrator_login_password silently changed
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
* provider.azurerm v2.25.0

### Affected Resource(s)

* `azurerm_postgresql_server `

### Terraform Configuration Files

```hcl
resource azurerm_postgresql_server server {
  ...
  administrator_login_password = var.password
  ... 
  lifecycle {
    ignore_changes = [
      administrator_login_password
    ]
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

#### Scenario 1
1. Create `azurerm_postgresql_server` in terraform with a default `administrator_login_password`
2. Change the admin login password in azure portal
3. `tf apply`

**_Expected_**: tf plan shows no change for `administrator_login_password`, and no change is applied. 
**_Actual_**: tf plan shows no change for `administrator_login_password`. On apply the admin password in the portal _IS NOT_ changed back to the default, as expected. 

#### Scenario 2 
1. Create `azurerm_postgresql_server` in terraform with default `administrator_login_password`
2. Change the admin login password in azure portal
3. Make a change on any other attribute of the terraform resource.
4. `tf apply`

**_Expected_**: tf plan shows no change for `administrator_login_password`, and no change is applied.
**_Actual_**: tf plan shows changes for the other resources, but not `administrator_login_password`. On apply the admin password in the portal _IS_ changed back to the default. This is unexpected.

### References

- #1823 
- https://github.com/terraform-providers/terraform-provider-azurerm/pull/2263

cc: @tombuildsstuff

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #12007

@reviewer: 
- Do we consider this as a breaking change or not?
- Should we introduce a test to check this behaviour?

### CODE REVIEW

**Comment by noqcks** [comment]
Thank you for creating this @aristosvo! I'm honestly not that familiar with terraform behaviour, so I was curious, does the `HasChange` fn respect the `ignore_changes` lifecycle rule in terraform?

**Comment by aristosvo** [comment]
@noqcks I assumed it works this way, but I don't have any documentation supporting it. Maybe we could test it manually or using an AccTest with postgres cli or provider?

**Comment by noqcks** [comment]
That's ok. I believe the tests for this behaviour should be handled at the level of terraform-plugin-sdk. We should be able to get a maintainer to confirm for us.

**Comment by noqcks** [comment]
cc: @katbyte

**Review by katbyte — APPROVED** [review]
Thanks @aristosvo - LGTM 👍

**Pull request merged**
