### PR TITLE
Update indian region names

### LINKED ISSUE #7906: Terraform and Azure API locations inconsistency
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.20
+ provider.azurerm v2.20.0
```

### Affected Resource(s)

* ALL
### Terraform Configuration Files

For example RG resource, but everything else fails. RG is only the prerequisite 

```hcl
provider "azurerm" {
  version         = "~> 2"
  tenant_id       = var.tenant_id
  subscription_id = var.subscription_id
  features {}
}

resource "azurerm_resource_group" "resource_group" {
  name     = var.resource_group_name
  location = var.resource_group_location
  tags     = var.tags
}
```

### Expected Behavior

Terraform should create resources in desired location/region

### Actual Behavior

Terraform does not support the `south`/`west`/`central` India locations. They are called India `south`/`west`/`central` in terraform which is not valid on Azure site
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/location/validation_test.go#L167

If we set location/region name to Terraform format (validation above), we got an error originating from Azure 
```
Error: Error creating Resource Group "<SOME_RG>": resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationNotAvailableForResourceGroup" Message="The provided location 'indiasouth' is not available for resource group. List of available regions is 'centralus,eastasia,southeastasia,eastus,eastus2,westus,westus2,northcentralus,southcentralus,westcentralus,northeurope,westeurope,japaneast,japanwest,brazilsouth,australiasoutheast,australiaeast,westindia,southindia,centralindia,canadacentral,canadaeast,uksouth,ukwest,koreacentral,koreasouth,francecentral,southafricanorth,uaenorth,australiacentral,switzerlandnorth,germanywestcentral,norwayeast'."

  on 10-main.tf line 8, in resource "azurerm_resource_group" "resource_group":
   8: resource "azurerm_resource_group" "resource_group" {

```

Which is reasonable and expected since
```
08:44 $ az account list-locations -o table
DisplayName           Latitude    Longitude    Name
--------------------  ----------  -----------  ------------------
...
South India           12.9822     80.1636      southindia
Central India         18.5822     73.9197      centralindia
West India            19.088      72.868       westindia
...
```

But trying to use the valid location/region on Azure fails in Terraform validation 
```
Error: "southindia" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,indiasouth,indiawest,indiacentral,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast"

  on 10-main.tf line 8, in resource "azurerm_resource_group" "resource_group":
   8: resource "azurerm_resource_group" "resource_group" {

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### Additional info

The most interesting thing is that `centralindia` is valid even when I set it in terraform and create the resource (cannot found it in the validation test?) but southindia/westindia are not :question: How come the locations are not the same API <-> provider?

Location differences. Terraform on the left, Azure on the right
image (1)

### PR DESCRIPTION
**Pull request by favoretti**
Fixes #7906

### CODE REVIEW

**Comment by gek0** [comment]
When can this be available earliest in the new version of the provider?
Since this finally makes terraform usable to deploy in India regions, the current situation makes it impossible since terraform accepts location names in its own format and Azure API fails with 400 status code.
And of course, many thanks to @favoretti for the quick fix!

**Comment by jackofallops** [comment]
By way of update. This is blocked until we get a resolution from MSFT on the locations API returning incorrect values for the India locations.

**Comment by gjones-r7** [comment]
Any word from MSFT?

**Comment by jackofallops** [comment]
> Any word from MSFT?

Still a conversation in progress.  We're exploring all options at the moment.  I'm going to close this PR for now as any underlying fix will make this stale.

**Pull request closed without merging**
