### PR TITLE
Add multi-master for Azure Cosmos DB accounts

### PR DESCRIPTION
**Pull request by pietro**
The go SDK needs to be updated for this PR but I don't know if I should do it in this PR or in another. So, I only updated the package for CosmosDB.

### CODE REVIEW

**Comment by katbyte** [comment]
Hi @pietro,

Thanks for the contribution, we will update the SKD in another PR

**Comment by katbyte** [comment]
@pietro,

I hope you don't mind but i pushed some changes to fix the test so i could merge it today 🙂

**Comment by pietro** [comment]
@katbyte thanks for getting this merged!

**Comment by tombuildsstuff** [comment]
hi @pietro 

Just to let you know that this has been released as a part of v1.18 of the AzureRM Provider ([the full changelog is available here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.18.0/CHANGELOG.md)). You can upgrade to this by specifying the version in the provider block (as shown below) and then running `terraform init -upgrade`

```
provider "azurerm" {
  version = "=1.18.0"
}
```

Thanks!

**Comment by pietro** [comment]
thanks for the heads up @tombuildsstuff!

**Pull request merged**
