### PR TITLE
`azurerm_key_vault`: waiting for 10 successful dns locators before returning as created

### LINKED ISSUE #655: Azure keyvault gets created but secret creation doesnt wait for availability, and crashes
### Terraform Version
```
Terraform v0.11.1
AzureRM version 1.0
```

### Terraform Configuration Files
```
resource "azurerm_key_vault" "test_keyvault" {
    provider = "azurerm.operations"
    name = "test-${var.MyNumber}-kv"
    location = "North Europe"
    resource_group_name = "${azurerm_resource_group.opstenant_resource_group.name}"

    sku {
        name = "standard"
    }

    tenant_id = "${var.tenant_id}"

  access_policy {
    tenant_id = "${var.tenant_id}"
    object_id = "${var.group_devops_id}"

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get","set","list","delete"
    ]
  }

  access_policy {
    tenant_id = "${var.tenant_id}"
    object_id = "${var.spn_devops_id}"

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get","set","list","delete"
    ]
  }

    access_policy {
    tenant_id = "${var.tenant_id}"
    object_id = "${var.tfs_prod_spn}"

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get","set","list","delete"
    ]
  }


  enabled_for_deployment = true
  enabled_for_template_deployment = true

tags = "${var.resource_tags}"
}

################### SECRETS

resource "azurerm_key_vault_secret" "tenant_admuser_secret" {
  provider = "azurerm.operations"
  name      = "${var.admUser}"
  value     = "${var.admPass}"
  vault_uri = "${azurerm_key_vault.test_keyvault.vault_uri}"
  depends_on = ["azurerm_key_vault.test_keyvault"]

  tags = "${var.resource_tags}"
}
```

### Crash Output
1 error(s) occurred:
* module.MyModule.module.TestModule.azurerm_key_vault.test_keyvault: 1 error(s) occurred:
* azurerm_key_vault.ops_keyvault: dial tcp: lookup test-00006-kv.vault.azure.net: no such host

### Expected Behavior
AzureRM keyvault should be created and secret should wait for DNS propogation

### Actual Behavior
I receive the crash.
If i re run the same command, it works, because now the keyvault DNS hostname is replicated across azure dns servers

### Steps to Reproduce
Create .tf files with keyvault and secret
Terraform apply

### Important Factoids
The files are fine, a second terraform apply rerun creates the secrets successfully.
The "depends_on" part was added to test maybe it will help waiting for keyvault availbility
This issue started out of the blue, like a new terraform version issue.

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Switching over to ensure the DNS is resolved 10 times in a row before marking the KeyVault resource as successfully provisioned.

This should fix #655 but it's hard to tell since it fails sporadically:

```
* azurerm_key_vault_secret.test-secret: azurerm_key_vault_secret.test-secret: Error making Read request on Azure KeyVault Secret acctestsecret-5272604717641362572: keyvault.BaseClient#GetSecret: Failure sending request: StatusCode=0 -- Original Error: Get https://vault5272604717641362572.vault.azure.net/secrets/acctestsecret-5272604717641362572/?api-version=2016-10-01: dial tcp: lookup vault5272604717641362572.vault.azure.net on 192.168.22.2:53: no such host
```

### CODE REVIEW

**Comment by pixelicous** [comment]
@tombuildsstuff was this merged to 1.3.3? Doesn't seem like it..

**Comment by tombuildsstuff** [comment]
@pixelicous not yet, this is still WIP as this fix needs some additional tweaking

**Comment by tombuildsstuff** [comment]
Also now fixes #1005

**Comment by tombuildsstuff** [comment]
Key Vault tests pass:

screen shot 2018-04-24 at 16 55 24

**Comment by tombuildsstuff** [comment]
hey @pixelicous

Just to let you know that v1.4.0 of the Azure Provider has been released which includes the fix for this :)

Thanks!

**Pull request merged**
