### PR TITLE
certificate contents and password as sensitive

### PR DESCRIPTION
**Pull request by Lucretius**
Resolves https://github.com/terraform-providers/terraform-provider-azurerm/issues/3056

I also marked the certificate password as sensitive.

### CODE REVIEW

**Comment by Lucretius** [comment]
Not sure why the lint check is failing - I ran the same command locally without issue.  Unit tests passed, and I was able to run the compiled binary against some sample resources to verify the intended behavior.  Any ideas what could be causing the failure?

**Comment by tombuildsstuff** [comment]
@Lucretius it appears the hosted linter we use has added a new linter overnight, which is why this is failing - I'll open a separate PR to fix those; sorry about that.

**Comment by tombuildsstuff** [comment]
There's a PR open for the linting fixes in #3065 - since this is unrelated to those fixes I'm going to merge this anyway; thanks again @Lucretius :)

**Comment by TraGicCode** [comment]
Thanks guys this was quick!

How often does this provider release?

**Comment by katbyte** [comment]
@TraGicCode,

we aim for bi weekly releases, however it can be as quick as 1 week and as long as 4 depending on circumstances.

**Pull request merged**
