### PR TITLE
Add support for encrypted disks in aks

### LINKED ISSUE #7092: Support for AKS Encrypted disk set
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AKS supports encrypting the disks for the OS of the master nodes as well as the volumes created inside k8s. Documentation can be found [here](https://docs.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys) This enables some controls required in higher security environments.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

Due to the fact that it's enabled at cluster level at not per node pool, this is the proposed configuration.

```hcl
resource "azurerm_disk_encryption_set" "example" {
  name                = "des"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  key_vault_key_id    = azurerm_key_vault_key.example.id
}

azurerm_kubernetes_cluster {
  ....
  disk_encryption_set= azurerm_disk_encryption_set.example.id
  ....
}
```

https://docs.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disk-encryption

### PR DESCRIPTION
**Pull request by jlpedrosa**
Added disk_encryption_set to kubernetes_cluster resource and data.

Related: #7092

Fixes #7092

### CODE REVIEW

**Comment by jlpedrosa** [comment]
acc test passed for the test created in the PR.

**Comment by jbinko** [comment]
Thanks Jose for quick implementation. :-) Is it also supporting Windows pools? I saw in the commit Linux profile so just double checking. Before trying.

**Comment by jlpedrosa** [comment]
Hi @jbinko

The option is enabled at AKS level not per node pool, so as far as I understand it shouldwork for both types of nodepools.

Also it can be added to the storageclass k8s object, but I understand this pr is not required for that feature.

**Comment by jbinko** [comment]
Sounds good. Will try. Thank you again!

**Pull request closed without merging**
