### PR TITLE
Add resource.Retry to PurgeNestedItem

### PR DESCRIPTION
**Pull request by pearcec**

### CODE REVIEW

**Comment by pearcec** [comment]
I need to adjust the error messages to be generic and not specific to the secret.

**Comment by StefanVo** [comment]
Hi, is it planned to merge this PR into next milestone of the azurerm provider? Thanks :-)

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @pearcec

**Comment by tombuildsstuff** [comment]
Running the tests for this there's some residual failures from

**Comment by tombuildsstuff** [comment]
Unintentionally pressed a key combination to close the PR, sorry 🤦

**Pull request merged**
