### PR TITLE
Updated azurerm_machine_learning_compute_cluster documentation

### PR DESCRIPTION
**Pull request by arj119**
Partially addresses issue #12507, updates the node idle time parameter

Update to documentation for azurerm_machine_learning_compute_cluster.

### CODE REVIEW

**Comment by gro1m** [comment]
This is (unfortunately) correct. Might need to change the code such that `subnet_resource_id` is really _optional_. Sorry for that. And thanks for correcting the argument for the node idle time, it somehow went under.

**Comment by arj119** [comment]
> This is (unfortunately) correct. Might need to change the code such that `subnet_resource_id` is really _optional_. Sorry for that. And thanks for correcting the argument for the node idle time, it somehow went under.

Hmm I can separate this into a separate PR and just have the docs update for the node idle time in this one then :)

**Comment by gro1m** [comment]
@arj119 Does actually setting `subnet_resource_id=""` work or does the current configuration really force the existence of a Virtual Network and Subnet (in the context of my employer this is reasonable, but it would be bad if that were always necessary, as as such would not be generalizable).

**Review by katbyte — APPROVED** [review]
Thanks @arj119 - LGTM 🎉

**Comment by arj119** [comment]
> @arj119 Does actually setting `subnet_resource_id=""` work or does the current configuration really force the existence of a Virtual Network and Subnet (in the context of my employer this is reasonable, but it would be bad if that were always necessary, as as such would not be generalizable).

So this is what happens when running tf without `subnet_resource_id` and when  `subnet_resource_id = ""`:
```
│ Error: creating Compute Cluster "cluster" in workspace "workspace" (Resource Group "tf-sbx"): machinelearningservices.MachineLearningComputeClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.properties.subnet.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."
│ 
│   with module.machine_learning.azurerm_machine_learning_compute_cluster.cluster,
│   on modules/machine-learning/main.tf line 30, in resource "azurerm_machine_learning_compute_cluster" "cluster":
│   30: resource "azurerm_machine_learning_compute_cluster" "cluster" {
│ 
```

I am looking into the source code for this but it will take me some time due to other responsibilities.

**Pull request merged**
