### PR TITLE
New Data Source: azurerm_servicebus_queue_authorization_rule

### PR DESCRIPTION
**Pull request by callumc46**
Attempting to get functionality for the servicebus queue as a data source.

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @callumc46, thanks for opening this PR. The datasource looks great but we'll need tests and docs before we can merge.

**Comment by callumc46** [comment]
> Hey @callumc46, thanks for opening this PR. The datasource looks great but we'll need tests and docs before we can merge.

Thanks mbfrahry, I'll get them sorted.

**Comment by callumc46** [comment]
callum@callumc46:~/go/src/github.com/terraform-providers/terraform-provider-azurerm-1$ make testacc TEST=./azurerm/internal/services/servicebus/tests TESTARGS="-run='TestAccDataSourceAzureRMServiceBusQueueAuthorizationRule_basic'"
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test ./azurerm/internal/services/servicebus/tests -v -run='TestAccDataSourceAzureRMServiceBusQueueAuthorizationRule_basic' -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceAzureRMServiceBusQueueAuthorizationRule_basic
=== PAUSE TestAccDataSourceAzureRMServiceBusQueueAuthorizationRule_basic
=== CONT  TestAccDataSourceAzureRMServiceBusQueueAuthorizationRule_basic
--- PASS: TestAccDataSourceAzureRMServiceBusQueueAuthorizationRule_basic (271.81s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/servicebus/tests	271.836s

**Comment by callumc46** [comment]
@mbfrahry hope thats enough now. Give me a shout if I've missed something else.

**Review by katbyte — APPROVED** [review]
Thanks @callumc46  - LGTM 🚀

**Pull request merged**
