### PR TITLE
azurerm_function_app - make `pre_warmed_instance_count` computed to use azure's default

### LINKED ISSUE #9066: Terraform Azure Function Default Prewarmed Instances Does Not Match Azure Default
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terarform Version: 0.13.3
Azurerm Version: Confirmed on 2.28.0 and 2.33.0

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "azure-functions-test-rg"
  location = "westus2"
}

resource "azurerm_storage_account" "example" {
  name                     = "functionsapptestsa"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "example" {
  name                = "azure-functions-test-service-plan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    tier = "ElasticPremium"
    size = "EP1"
  }
}

resource "azurerm_function_app" "example" {
  name                       = "test-azure-functions"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
}
```

### Expected Behavior

Without explicity setting the prewarmed instances I would expect it to default to 1 as detailed by Microsoft [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan)

> The default pre-warmed instance count is 1, and for most scenarios should remain as 1.

### Actual Behavior

Prewarmed instances set to 0
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by RiverPhillips**
This resolves  #9066 by setting the default prewarmed pre_warmed_instance_count to 1

### CODE REVIEW

**Comment by jackofallops** [comment]
Hi @RiverPhillips - Thanks for this PR. I think this was left without a default due to non-premium SKU's discarding this value, so would create a Diff as the value will be `0` when read back from the API.  As such, this would probably need to be validated / adjusted in code, or possibly just updated in the documentation for appropriate usage guidance? WDYT?

**Comment by RiverPhillips** [comment]
HI @jackofallops thanks for your feedback. I think it would be sensible if we defaulted to 1 for all plans except for the consumption plan. I think that should solve the issue you raised surrounding the diff. Or we could require it be set for non-consumption SKUs.

**Review by katbyte — CHANGES_REQUESTED** [review]
@RiverPhillips - instead of adding a default here maybe we could change it to `computed` to let azure pick the default?

**Comment by RiverPhillips** [comment]
@katbyte - I hadn't considered that approach, I think it's the most practical and future proof so I have made that change

**Review by katbyte — APPROVED** [review]
Thanks @RiverPhillips - this LGTM 👍

**Pull request merged**
