### PR TITLE
[WIP] New Resource: `azurerm_sql_managed_instance`

### LINKED ISSUE #1747: Managed SQL database instance
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

---

It would be nice if we have a terraform feature for Azure SQL Managed database instance.

### PR DESCRIPTION
**Pull request by mbfrahry**
Continuation of  #2727

Fixes #1747

### CODE REVIEW

**Comment by iriahk89** [comment]
Hi, Do you think this going to be release anytime soon? knowing that we have issue on custom timeout for MI

**Comment by mbfrahry** [comment]
Closing this as blocked. We are waiting on a feature to be added to the api that will allow us to move forward on this resource.

**Comment by collen-kr** [comment]
@mbfrahry First, thank you for your work and contribution to this. It will be a huge help for me. Is there any update on whether we can get this PR updated/merged?

**Comment by tombuildsstuff** [comment]
@collen-kr see the upstream issue for updates: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1747

**Pull request closed without merging**
