### PR TITLE
Fix acctest `TestAccMsSqlVirtualMachine_keyVault`

### PR DESCRIPTION
**Pull request by yupwei68**
=== RUN   TestAccMsSqlVirtualMachine_keyVault
=== PAUSE TestAccMsSqlVirtualMachine_keyVault
=== CONT  TestAccMsSqlVirtualMachine_keyVault
--- PASS: TestAccMsSqlVirtualMachine_keyVault (1481.21s)

### CODE REVIEW

**Review by katbyte — COMMENTED** [review]
thanks @yupwei68 - looks like there is still a failing SQLVM test:

```
TestAccMsSqlVirtualMachine_storageConfiguration

------- Stdout: -------
=== RUN   TestAccMsSqlVirtualMachine_storageConfiguration
=== PAUSE TestAccMsSqlVirtualMachine_storageConfiguration
=== CONT  TestAccMsSqlVirtualMachine_storageConfiguration
    testing.go:620: Step 3/4 error: Error running apply: 
        Error: waiting for creation of Sql Virtual Machine (Sql Virtual Machine Name "acctest-VM-210323152154137030" / Resource Group "acctestRG-mssql-210323152154137030"): Code="Ext_AutomatedBackupError" Message="Error: 'The log for database 'tempdb' is not available. Check the operating system error log for related error messages. Resolve any errors and restart the database.;System.Data.SqlClient.SqlException (0x80131904): The log for database 'tempdb' is not available. Check the operating system error log for related error messages. Resolve any errors and restart the database.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at Microsoft.SqlServer.Management.IaaSAgentSqlQuery.Service.SqlQueryService.<>c__DisplayClass135_0.<DisableManagedBackup>b__0()\r\n   at Microsoft.SqlS'"
```

**Review by katbyte — CHANGES_REQUESTED** [review]
.

**Comment by yupwei68** [comment]
Hi kt, right. That requires the service team to fix it. I've transferred the problem to them. This PR is for only `TestAccMsSqlVirtualMachine_keyVault`. Or we can wait till the fix from the service side released to get this merged.

**Review by katbyte — APPROVED** [review]
kk, will merge this with the understanding service team will fix the problem with the other

**Pull request merged**
