### PR TITLE
New resources: `iothub_endpoint_storage_container`, `iothub_endpoint_eventhub`, `iothub_endpoint_servicebus_queue`, `iothub_endpoint_servicebus_topic`

### PR DESCRIPTION
**Pull request by maxbog**
Extracts Endpoint resources from IoTHub.

See #3303

### CODE REVIEW

**Comment by maxbog** [comment]
Those four resources have obviously very similar implementations. I wonder if it wouldn't be good to refactor and extract the code that is common to all four resources. 

What do you think?

**Comment by maxbog** [comment]
Is there any chance for someone to look at this PR? Maybe I should split it into smaller ones?

**Comment by maxbog** [comment]
anybody?

**Comment by mbfrahry** [comment]
Hey @maxbog. Apologies for the delay in getting this one and the other PRs in. I took a look and this mostly looks great. It's just missing best practices in the provider that have changed with how long this has been around. I've taken a crack at getting those in so you wouldn't have to but I couldn't merge it in cleanly since we haven't looked at this in so long. I've opened up a separate PR here #4823 that has all your commits and a couple of mine layered on top to get it up to snuff with the master branch of the provider. Let me know if those look ok and we'll get it reviewed on more time before getting it in

**Comment by maxbog** [comment]
@mbfrahry Your changes look fine for me. Would be great to have your PR in :D

**Comment by katbyte** [comment]
I'm going to close this as it's been superseded by #4823, thanks @maxbog & @mbfrahry !

**Pull request closed without merging**
