### PR TITLE
Bump azure-sdk-for-go/recoveryservices from 2018-01-10 to 2018-07-10

### PR DESCRIPTION
**Pull request by MitchDrage**
As part of feature request [8837](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8837) an update to the azure-sdk-for-go/recoveryservices sdk is required to provide access to the RecoveryPublicIPAddressID model that isn't present in the current version (2018-01-10).

See gist for [test results](https://gist.github.com/MitchDrage/25ef33f40882eee47a64164757ce36df) using the new tests pushed in v2.45 ([in this pull](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10347)).

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by tombuildsstuff** [comment]
Running the tests for this, it looks like the newer API is returning a 400 rather than a 404 when the Network Mapping doesn't exist:

```
Error checking for presence of existing site recovery fabric acctest-fabric1-210201093520393071 (vault acctest-vault-210201093520393071): siterecovery.ReplicationFabricsClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The resource with ID 2195638768288125375 isn't registered with the service." Details=[{"activityId":"689647ac-7f72-7f8b-e344-93183a09e18a","clientRequestId":"6cac2a93-9f39-48f7-abb8-a62785eeaf97","code":"SubscriptionIdNotRegisteredWithSrs","message":"The resource with ID 2195638768288125375 isn't registered with the service.","possibleCauses":"The operation failed due to an internal error.","recommendedAction":"Retry the last action. If the issue persists, contact Support."}]
```

So we'll need to update the Requires Import check to check for a 400 in addition to a 404 here

**Comment by tombuildsstuff** [comment]
Upstream issue: https://github.com/Azure/azure-rest-api-specs/issues/12759

**Comment by katbyte** [comment]
Checking historical test runs that issue seems to predate the API upgrade - as such going to merge

**Pull request merged**
