### PR TITLE
azurerm_hpc_cache: update API version to 2020-03-01 and support `mtu` and `root_squash_enabled` properties

### LINKED ISSUE #8021: Support for azurerm_hpc_cache option configure root squash
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource `azurerm_hpc_cache` does not provide settings:
* MTU size
* Root squash

These configuration options are available within the console.

### New or Affected Resource(s)

* azurerm_hpc_cache

### Potential Terraform Configuration

```hcl
configuration {
  mtu_size = <bytes>
  enable_root_squash = true|false
}
```

### References

https://docs.microsoft.com/en-us/azure/hpc-cache/configuration

### PR DESCRIPTION
**Pull request by magodo**
Update API version of storagecache from 2019-11-01 to 2020-03-01, which supports network/security settings for hpc cache.

Meanwhile, the model of hpc cache target (nfs/cls) are changed into using discriminator. Hence those files are also modified to compile.

There should be no breaking change introduced by this PR.

(fixes #8021)

### CODE REVIEW

**Comment by magodo** [comment]
@katbyte I have added the document and passed the CI, please continue reviewing 👀

**Comment by magodo** [comment]
@katbyte I have resolved the conflicts, please take a look.

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @magodo - no a couple test failures that once addressed this should be good to merge:

```
------- Stdout: -------
=== RUN   TestAccAzureRMHPCCacheBlobTarget_basic
=== PAUSE TestAccAzureRMHPCCacheBlobTarget_basic
=== CONT  TestAccAzureRMHPCCacheBlobTarget_basic
    TestAccAzureRMHPCCacheBlobTarget_basic: testing.go:684: Step 1 error: HPC Cache Target "acctest-HPCCTGT-bo6cv" (Resource Group "acctestRG-storage-200925202505000834", Cahe "acctest-HPCC-200925202505000834") "type" mismatch, expected "clfs", got "Microsoft.StorageCache/caches/storageTargets"
--- FAIL: TestAccAzureRMHPCCacheBlobTarget_basic (1696.69s)
FAIL

------- Stdout: -------
=== RUN   TestAccAzureRMHPCCacheBlobTarget_update
=== PAUSE TestAccAzureRMHPCCacheBlobTarget_update
=== CONT  TestAccAzureRMHPCCacheBlobTarget_update
    TestAccAzureRMHPCCacheBlobTarget_update: testing.go:684: Step 1 error: HPC Cache Target "acctest-HPCCTGT-pcwmf" (Resource Group "acctestRG-storage-200925202504964363", Cahe "acctest-HPCC-200925202504964363") "type" mismatch, expected "clfs", got "Microsoft.StorageCache/caches/storageTargets"
--- FAIL: TestAccAzureRMHPCCacheBlobTarget_update (1758.40s)
FAIL
```

**Comment by magodo** [comment]
Hi @katbyte I have removed the importer, since the Read callback has already handle incorrect import.

**Review by katbyte — APPROVED** [review]
Thanks @magodo - LGTM 👍

**Pull request merged**
