### PR TITLE
Upgrade Api Management Version from 2020-12-01 to 2021-01-01-preview

### PR DESCRIPTION
**Pull request by yupwei68**
To fix https://github.com/terraform-providers/terraform-provider-azurerm/pull/12125 to support `PublicIPAddress` to allow setting zone in api management service in vnet

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
build in TC fails:
```
[16:39:50]	[Step 4/5] api_management_api_release.go:8:2: cannot find package "." in:
[16:39:50]	[Step 4/5] 	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2020-12-01/apimanagement
```

**Comment by yupwei68** [comment]
Hi kt, I've updated the PR with the latest upstream change. Except one `sample` in `api_operation` is not returned, (I'm checking with service team), all other tests have passed. I'll track that one.

**Comment by yupwei68** [comment]
Temporarily closed for the blocker of `api_operation`

**Comment by amkctc** [comment]
Hi! Do You plan to resume working on this issue? Currently if you create APIM via terraform and manually assign availability zones with internal vnet - it completely breaks terraform workspace - because terraform unable to read the APIM state.
```
azurerm_api_management.apimaz: Refreshing state... [id=/subscriptions/.../resourceGroups/test-sandbox-apimaztest-cc-rg/providers/Microsoft.ApiManagement/service/test-sandbox-apimaz-cc-apim]
|
│ Error: making Read request on API Management Service "test-sandbox-apimaz-cc-apim" (Resource Group "test-sandbox-apimaztest-cc-rg"):
 apimanagement.ServiceClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="" 
Message="The service is configured to allow management requests only with the following api-version values: 2021-01-01-preview, 2021-04-01-preview"
│
│   with azurerm_api_management.apimaz,
│   on main.tf line 106, in resource "azurerm_api_management" "apimaz":
│  106: resource "azurerm_api_management" "apimaz" {
│
```

**Comment by tombuildsstuff** [comment]
@JeffreyRichter that seems like an API bug, where a resource is modified on one API Version but can't be retrieved on an older one?

**Comment by JeffreyRichter** [comment]
If you're saying that just modifying a resource with a new api-version value makes the resource completely ungettable with an old api-version value, then that is a breaking change and is not allowed by Azure's versioning policies. However, we occasionally DO allow an exception to this, but it requires that the service team fully document this behavior so that customers completely understand that updating a resource with a new api-version means that it will be inaccessible to a client using an old api-version so that customers are consciously and explicitly opting into this behavior on their schedule.

I'm guess that this documentation was done here, or you would have been expecting this behavior rather than being surprised by it. If so, then this change is against Azure's policies. Plus, I would have been notified of this break and I don't recall hearing about this one and so it likely is a violation of Azure's versioning policies. I'll contact some people closer to this issue. Thanks for bringing this to my attention.

**Comment by dmedeiros204** [comment]
Interesting enough I was able to set the public IP, and the AV Zone through a combination of Terraform and ARM but never lost terraform functionality after

```
  "properties": {
        "publicIpAddressId": "[parameters('publicIpAddressId')]",
        "virtualNetworkConfiguration": {
          "subnetResourceId": "[parameters('SubnetResourceId')]"
        },
        "virtualNetworkType": "Internal",
        "publisherEmail": "MyTest@Test.me",
        "publisherName": "MyTest"
      },
      "zones": ["1"]
```

Tf to implement
```
resource "azurerm_template_deployment" "pip" {
  name                = "pip_setup"
  resource_group_name = "myRG"

  template_body = file("${path.module}/apim_zones.json")

  parameters = {
    "publicIpAddressId" = "mypipid"
    "SubnetResourceId"  = azurerm_subnet.secondary.id
  }

  deployment_mode = "Incremental"
  
}
```

**Comment by yupwei68** [comment]
I'll tracking this problem with service team.

**Pull request closed without merging**
