### PR TITLE
New data resource: Table Storage SAS token

### LINKED ISSUE #7769: Support for Azure Table Storage SAS Token Data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a data source to allow creating SAS tokens for Table storage

### New or Affected Resource(s)

* data.azurerm_storage_account_table_sas

### Potential Terraform Configuration

```hcl
data "azurerm_storage_account_table_sas" "test" {
  connection_string = azurerm_storage_account.storage.primary_connection_string
  table_name        = azurerm_storage_table.table.name
  https_only        = true

  start  = "2018-03-21"
  expiry = "2022-03-21"

  permissions {
    read   = true
    add    = true
    update = false
    delete = true
  }
}

```

### PR DESCRIPTION
**Pull request by nickmhankins**
Fixes #7769 

hashicorp/go-azure-helpers#58 is a prerequisite

### CODE REVIEW

**Comment by IanMoroney** [comment]
@nickmhankins , would you be able to fix the issue with ComputeTableSASToken in data_source_storage_account_table_sas.go so that the test and linting are successful?

**Comment by IanMoroney** [comment]
Ah, I see it's dependent on 58, which is why it's failing.
👍

**Comment by nickmhankins** [comment]
> Ah, I see it's dependent on 58, which is why it's failing.
> 👍

Yea, it says I still have not signed the CLA in order to get that PR accepted, but I signed it 3 weeks ago.  Would you be able to help by seeing what's going on with that?

Thanks!

**Comment by katbyte** [comment]
@nickmhankins - until the questions are resolved in the linked PR (and it merged) i'm going to close this.

**Pull request closed without merging**
