### PR TITLE
`azurerm_cosmosdb_account`: expose `backup_policy`

### LINKED ISSUE #10557: Support for CosmosDB Continuous Backup Mode
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to create a CosmosDB instance using continuous backup mode per: https://docs.microsoft.com/en-us/azure/cosmos-db/continuous-backup-restore-introduction

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl

resource "azurerm_cosmosdb_account" "db" {
  # Options for backup_restore_type would be {"periodic" (default) | "continuous"} 
  backup_restore_type = "continuous"

}
```

### References

* https://docs.microsoft.com/en-us/azure/cosmos-db/continuous-backup-restore-introduction
* https://docs.microsoft.com/en-us/azure/cosmos-db/online-backup-and-restore

### PR DESCRIPTION
**Pull request by brunhil**
Expose the `backup_policy` field that can be configured for `Continuous` or `Periodic` backups.

Fixes #10557 

Upgrade CosmosDB API from `2020-04-01-preview` to `2020-06-01-preview` in order to support this field.

> === RUN   TestAccCosmosDBAccount_backupPolicy
> === PAUSE TestAccCosmosDBAccount_backupPolicy
> === CONT  TestAccCosmosDBAccount_backupPolicy
> --- PASS: TestAccCosmosDBAccount_backupPolicy (1344.51s)
> PASS
> ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos	1346.140s
> 

> === RUN   TestAccCosmosDBAccount_basic_global_eventual
> === PAUSE TestAccCosmosDBAccount_basic_global_eventual
> === CONT  TestAccCosmosDBAccount_basic_global_eventual
> --- PASS: TestAccCosmosDBAccount_basic_global_eventual (624.75s)
> PASS
> ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos      627.784s
>

### CODE REVIEW

**Comment by brunhil** [comment]
One question I have for maintainers is whether or not we want to upgrade *every* resource to the new preview version or just the CosmosDB Account?

**Comment by katbyte** [comment]
We try to keep all resources on the sae API version so all of them 🙂

**Comment by jackofallops** [comment]
It looks like there may be a bug (or possibly behavioural change) in the bumped version for `geo_location` / replication:
```
=== RUN   TestAccCosmosDBAccount_update_global
=== PAUSE TestAccCosmosDBAccount_update_global
=== CONT  TestAccCosmosDBAccount_update_global
    testing.go:705: Step 2 error: Check failed: 1 error occurred:
        	* Check 1/1 error: Check 7/13 error: azurerm_cosmosdb_account.test: Attribute 'geo_location.#' expected "3", got "1"
```
This error is present in all tests that expect more than one location as far as I can see.

**Comment by brunhil** [comment]
Thanks for finding the regression @jackofallops ! I pushed a fix and confirmed the referenced test passes locally,

```
TF_ACC=1 go test -v ./azurerm/internal/services/cosmos -run=TestAccCosmosDBAccount_update_global -timeout 60m -ldflags="-X=github.com/terraform-providers/
terraform-provider-azurerm/version.ProviderVersion=acc"
2021/03/01 19:42:33 [DEBUG] not using binary driver name, it's no longer needed
2021/03/01 19:42:33 [WARN] could not locate a terraform executable on system path; continuing
2021/03/01 19:42:38 [DEBUG] not using binary driver name, it's no longer needed
2021/03/01 19:42:38 [WARN] could not locate a terraform executable on system path; continuing
=== RUN   TestAccCosmosDBAccount_update_global
=== PAUSE TestAccCosmosDBAccount_update_global
=== CONT  TestAccCosmosDBAccount_update_global
--- PASS: TestAccCosmosDBAccount_update_global (2090.16s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos      2101.816s
```

**Comment by jackofallops** [comment]
Hi @brunhil - Thanks for the work on the regression, there's a few SDK version updates coming (one's in, hence the conflicts currently). There's at least one more, which contains Cosmos package changes, so you may want to wait for that before rebasing. I'll try to post back here once that's in, so we can get this settled and I can re-run the tests to confirm 👍

**Comment by tommyforlini** [comment]
@brunhil are you going to be able to resolve the conflicts in order to get these changes merged into the upcoming milestone. Really looking forward to leveraging the capability

**Comment by brunhil** [comment]
@tommyforlini absolutely! I'm just waiting to hear back if the second round of sdk updates have made it in. Do you know if that's done yet @jackofallops ? I saw the first round last Friday in but haven't been able to keep up to date this week thus far

**Comment by tommyforlini** [comment]
@brunhil  anything i can do to help fix the the remaining conflict so hopefully this can make the cut for tomorrows release?

**Comment by brunhil** [comment]
> @brunhil anything i can do to help fix the the remaining conflict so hopefully this can make the cut for tomorrows release?

Nah just pushed the rebase fix. Just waiting for review from the team!

**Comment by tommyforlini** [comment]
@katbyte wondering how come this PR didnt make the cut following the bot msg.
https://github.com/terraform-providers/terraform-provider-azurerm/pull/10578#issuecomment-816327418

**Comment by tommyforlini** [comment]
Is there any chance of this ever making the cut to be merged into the main brach?

**Review by katbyte — COMMENTED** [review]
@brunhil @tommyforlini - SDK upgrade has finally be merged (as well as service tests are all fixed) so this is good to go once the merge conflicts are fixed!

**Comment by brunhil** [comment]
> @brunhil @tommyforlini - SDK upgrade has finally be merged (as well as service tests are all fixed) so this is good to go once the merge conflicts are fixed!

Great! Thanks for following up @katbyte .

I'll work on rebasing these changes and making needed changes over the coming days hopefully @tommyforlini .

**Comment by katbyte** [comment]
Hey @brunhil - i hope you don't mind but i'm going to close this in favour of #11597 so we can get it merged this week

**Pull request closed without merging**
