### PR TITLE
Support for Function App publishing profile attribute

### LINKED ISSUE #8739: Support for exposing Function App publishing profile as a resource/data source attribute
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Function Apps have a publishing profile, an XML document that can be used by clients to publish code in a manner appropriate for a given configuration.  For example, the GitHub publishing action, https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions.

This feature would expose the publishing profile as an additional attribute of Function Apps, Function App slots, and the associated data source.

### New or Affected Resource(s)

Resources:
   * azurerm_function_app
   * azurerm_function_app_slot

Data sources:
   * azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "github_actions_secret" "publish_profile" {
  repository       = "foo"
  secret_name      = "AZURE_FUNCTIONAPP_PUBLISH_PROFILE"
  plaintext_value  = azurerm_function_app.fooapp.publishing_profile
}

```

### References

* #0000

### PR DESCRIPTION
**Pull request by jake-scott**
Fixes #8739

The tests are not passing, but they don't pass for me without this patch either..

### CODE REVIEW

**Comment by gdippolito** [comment]
That would be very useful to integrate better function apps with terraform. What is the blocker to get this merged?

**Comment by jackofallops** [comment]
Hi @jake-scott - Hope you don't mind, but I fixed up the merge conflicts and tweaked for some refactoring we've done in main. I'll take a look into the tests shortly to see if there's something awry, after which I'll review.

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @jake-scott 
The team has had a discussion on this internally and we believe the best way to surface this data is to introduce two new data sources (e.g. `azurerm_function_app_publishing_profile` and `azurerm_function_app_slot_publishing_profile`), rather than including in the existing resources and data source.  While this represents more work / code and additional config for the end user, the sensitive nature of the information in this property we believe warrants separating out. Is this something you are comfortable doing?

**Comment by jake-scott** [comment]
@jackofallops - I think that makes sense - I assume this is so that the profile doesn't make it to the state file unless the user specifically asks for it?  There are lots of other resources that leak sensitive things like private keys to the state though, is there a plan to remediate those in a similar way (and is this mechanism something we've done for other things already or will the functions app be the first?)

To answer your question, yep I can give this a go..

**Comment by jackofallops** [comment]
@jake-scott - Mostly it's because it's a highly sensitive set of data that has never been there before. Suddenly exposing that in all cases as this would do currently is likely to cause concern and/or pain to a lot of users, or worse yet unexpected security exposure. By splitting it out users such as yourself get access to it explicitly where needed without the potential problems. Does that make sense?

**Comment by jake-scott** [comment]
@jackofallops That makes perfect sense. I'll work on a new PR..

**Comment by jackofallops** [comment]
> @jackofallops That makes perfect sense. I'll work on a new PR..

Thanks @jake-scott - I'm going to go ahead and close this one and keep an eye out for the new one with the new data sources. 👍

**Pull request closed without merging**
