### PR TITLE
Example: Add vnet-hdinsight-secure configuration

### PR DESCRIPTION
**Pull request by doherty100**

### CODE REVIEW

**Comment by doherty100** [comment]
Hi I would like to contribute a new example configuration for deploying a secure VNet for use by HDInsight. It was developed for a production deployment of HDInsight which is currently in use. Organizations who wish to do a private, secure deployment of HDInsight into a VNet that is accessible from their on-premises network would benefit from this example. Please let me know if any improvements are required I would be happy to implement them.

**Comment by tombuildsstuff** [comment]
hey @doherty100 

Thanks for this PR :)

Apologies for the delayed review here, we've been trying to determine the best place for this example to live. Whilst we agree that the module is valuable to other users, we feel that without the HDInsights Resources (which as you've mentioned in the Readme aren't currently supported by Terraform) that this could be more useful as a [module on the Terraform Registry](https://registry.terraform.io).

Once the HDInsights resources are supported by Terraform (which is tracked in #37 - and is on our roadmap for the not-too-distant future) we could look to add some complete end-to-end samples within [the examples folder](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples) (as you've done here). However until this time we believe this module would be more useful [on the Terraform Registry](https://registry.terraform.io) and as such whilst I'm going to close this PR for the moment I'd like to thank you for this contribution :)

Thanks!

**Comment by doherty100** [comment]
@tombuildsstuff thanks for the consideration. I will attempt to make a submission on the terraform registry.

**Comment by doherty100** [comment]
@tombuildsstuff I published this on the Terraform Registry as you suggested at [network-hdi](https://registry.terraform.io/modules/doherty100/network-hdi/azurerm/1.0.0)

**Pull request closed without merging**
