### PR TITLE
Allow SKU capacity 0

### LINKED ISSUE #6730: TF apply/plan have different constraints for "Consumption" tier for API Management
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.8.0

### Affected Resource(s)

* `azurerm_api_management`

### Issue description
Since 2.8.0 the "Consumption" tier for API Management should be supported. However, I'm unable to set this tier:

#### Use `sku_name = "Consumption"`
`terraform plan` fails with `Error: sku_name(Consumption) is not formatted properly.`

#### Use `sku_name = "Consumption_0"`
`terraform plan` fails with `Error: expected sku_name capacity value to be greater that 1, got 0`

#### Use `sku_name = "Consumption_1"`
`terraform plan` passes, however, `terraform apply` fails with `Error: creating/updating API Management Service "<redacted>" (Resource Group "<redacted>"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameters" Message="Invalid parameter: For Consumption SKU Type capacity must be specified as 0."`

So it seems that `terraform plan` requires "Consumption_1" (or greater), but `terraform apply `requires "Consumption_0"

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Here the output when setting `sku_name = "Consumption_0"` and running `terraform apply`:

```
2020-05-01T06:47:23.0441766Z 2020/05/01 06:47:22 [ERROR] module.apim: eval: *terraform.EvalDiff, err: expected sku_name capacity value to be greater that 1, got 0
2020-05-01T06:47:23.0442653Z 2020/05/01 06:47:22 [ERROR] module.apim: eval: *terraform.EvalSequence, err: expected sku_name capacity value to be greater that 1, got 0
2020-05-01T06:47:23.0443329Z 2020/05/01 06:47:22 [TRACE] [walkRefresh] Exiting eval tree: module.apim.azurerm_api_management.customer_api
2020-05-01T06:47:23.0443789Z 2020/05/01 06:47:22 [TRACE] vertex "module.apim.azurerm_api_management.customer_api": visit complete
2020-05-01T06:47:23.0444288Z 2020/05/01 06:47:22 [TRACE] vertex "module.apim.azurerm_api_management.customer_api": dynamic subgraph encountered errors
2020-05-01T06:47:23.0444782Z 2020/05/01 06:47:22 [TRACE] vertex "module.apim.azurerm_api_management.customer_api": visit complete
```

### Expected Behavior

`terraform apply` and `terraform plan` should have the same capacity constraints for APIM `Consumption` tier.

### Actual Behavior

`terraform plan` requires capacity set to `0`, whereas `terraform apply` requires capacity to be set `>0`.

### PR DESCRIPTION
**Pull request by omgapuppy**
Addresses https://github.com/terraform-providers/terraform-provider-azurerm/issues/6730

Fixes #6730

### CODE REVIEW

**Comment by omgapuppy** [comment]
Might be sensible to only pass allowed capacity of `0` if `sku_name = "Consumption_0"`, but this is a quick workaround :shrug:

**Comment by katbyte** [comment]
and update the docs if needed!

**Comment by omgapuppy** [comment]
Didn't get around to it over the weekend, but looks like further changes to the provider are needed:

```
Error: creating/updating API Management Service "REDACTED" (Resource Group "staging"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NotSupported" Message="'Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30' customProperties are not supported in SkuType Consumption."
```

So while the `0` value satisfies the API constraint for Consumption tier capacity, the provider passes attributes with the API call that are not supported in that tier - annoying, as I had them left as defaults in given environment (disabled).

Will have a look at adding conditionals specific to Consumption tier in `resource_arm_api_management.go` later & writing some tests.

I can only commit time to this after work at present, but it is something that'd save us a fair chunk on low traffic endpoints vs using `Basic_1`.

**Comment by evertonmc** [comment]
You better add this to the docs as well, because `Basic_0` won't work, as well as `Consumption_1`

**Comment by omgapuppy** [comment]
Closing as I don't, unfortunately, have the capacity to commit to fixing this at the moment :(
:crossed_fingers: #6730 will be picked up by someone closer to the project.

**Pull request closed without merging**
