### PR TITLE
switch terraform SDK to v0.12-early9

### LINKED ISSUE #3101: Provide terraform 0.12 beta support
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Morning,
in https://github.com/terraform-providers/terraform-provider-azurerm/issues/2686 it mentions that you wont provide support till the 0.12 beta is released.

https://www.hashicorp.com/blog/announcing-terraform-0-1-2-beta1

If this is possible it would be great, as I have a number of issues that I want  to check with 0.12 and its new language support, mainly around resources that have not been defined.

Regards
Nicholas Irving

### PR DESCRIPTION
**Pull request by katbyte**
outstanding issues:
- [x] `panic: interface conversion: interface {} is nil, not map[string]interface {}`
	- `TestAccAzureRMVirtualMachineScaleSet_linuxUpdated`, `TestAccAzureRMVirtualMachineScaleSet_basicWindows_managedDisk_resize`, `TestAccAzureRMVirtualMachineScaleSet_upgradeModeUpdate` and more
	- ~phantom nil object, maybe related to [this sdk issue](https://github.com/hashicorp/terraform/issues/20486), vendor in master to check~ still broken with master
- [x] `TestAccAzureRMTemplateDeployment_withOutputs : Check failed: Check 4/6 error: Output 'tfFalseOutput': expected "0", got &terraform.OutputState{Sensitive:false, Type:"string", Value:"false", mu:sync.Mutex{state:0, sema:0x0}}`
- [x] `Expected a non-empty plan, but got an empty plan!`
	- most lb tests: `TestAccAzureRMLoadBalancerBackEndAddressPool_reapply`, `TestAccAzureRMLoadBalancerRule_reapply`
- [x] `TestAccAzureRMKubernetesCluster_addAgent: interface {} is nil, not map[string]interface {}`
	- ~phantom nil object, maybe related to [this sdk issue](https://github.com/hashicorp/terraform/issues/20486), vendor in master to check~ still broken with master
- [x] cosmos db: ` Error: Error expanding CosmosDB Account "acctest-190304225533879983" (Resource Group "acctestRG-190304225533879983") geo locations: Each `geo_location` needs to have a unique failover_prioroty. Multiple instances of '0' found`

Fixes #3101

### CODE REVIEW

**Comment by metacpp** [comment]
@katbyte Thanks for the work. A quick question: is this upgrade still compatible with Terraform `1.11.11` ?

**Comment by katbyte** [comment]
extra nil element:
```
=== RUN   TestAccAzureRMKubernetesCluster_addAgent
=== PAUSE TestAccAzureRMKubernetesCluster_addAgent
=== CONT  TestAccAzureRMKubernetesCluster_addAgent
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 622 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm.expandKubernetesClusterAddonProfiles(0xc000a4f5e0, 0xc00181c300)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_kubernetes_cluster.go:752 +0x93f
```

[config](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster_test.go#L600-L621)
[code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster.go#L752)

**Comment by katbyte** [comment]
another instance:
```
=== RUN   TestAccAzureRMVirtualMachineScaleSet_linuxUpdated
=== PAUSE TestAccAzureRMVirtualMachineScaleSet_linuxUpdated
=== CONT  TestAccAzureRMVirtualMachineScaleSet_linuxUpdated
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 847 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm.expandAzureRmVirtualMachineScaleSetNetworkProfile(0xc0018744d0, 0x0)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_machine_scale_set.go:1630 +0x1f94
```

[config](https://github.com/terraform-providers/terraform-provider-azurerm/blob/012/early4/azurerm/resource_arm_virtual_machine_scale_set_test.go#L2425)
[code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/012/early4/azurerm/resource_arm_virtual_machine_scale_set.go#L1630)

**Comment by kim0** [comment]
Hi @katbyte .. Thanks for the tons of fixes here to support 0.12!!

I'm starting on a new TF project soon, and it really pains me to start with 0.11 syntax. Is it possible to get a binary that's compatible with beta-2 sometime soon. Thanks!

**Comment by bentterp** [comment]
Last week's dev snapshot in http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/terraform-provider-azurerm/1.25.0-dev20190415H16-dev/ gives me

```Incompatible API version with plugin. Plugin version: 4, Client versions: [5]``` which I don't think is the expected outcome

**Comment by bentterp** [comment]
@kim0 while we wait for this to be resolved, something like this might help you: https://gist.github.com/bentterp/d9e8dcc9d17bfcce87a7563a769e9070

**Comment by katbyte** [comment]
@kim0 & @bentterp,

Sorry for the delay in getting a .12 compatible binary out, there was a regression with proxies we wanted to resolve and release a fix for first. However that just went out this morning in `v1.26.0` so check back _soon_ for `v1.27.0` with .12 support 😉

**Comment by bentterp** [comment]
@kim0  While we wait for 1.27.0, the beta1 snapshot of 1.23.0 seems to work with beta2 as well - http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/terraform-provider-azurerm/1.23.0-dev20190216H00-dev/

**Comment by katbyte** [comment]
@bentterp & @kim0,

just released v1.27 with .12 support 🙂

**Comment by bentterp** [comment]
@katbyte 
> just released v1.27 with .12 support 🙂

You spoil me 🤗

**Pull request merged**
