### PR TITLE
Create MongoDB v3.6 with azurerm_cosmosdb_account (#4757)

### LINKED ISSUE #4757: Create MongoDB v3.6 with azurerm_cosmosdb_account
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We need to create a CosmosDB with a MongoDB **3.6** API Version.

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
capabilities {
    name = "MongoDBv3.6"
}
```

### References
void

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #4757 for service/cosmosdb

FWIW, in #4757 are also validations mentioned. I'm looking into implementing these, but I'm not sure wheter these should be here in a custom validate function or not. If they should be here, the question is if I should break the existing contract to implement these (with more validations) in the schema:

```
"capabilities": {
	Type:     schema.TypeSet,
	Optional: true,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"EnableMongo": {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  false,
			},
..
```

### CODE REVIEW

**Comment by dany74q** [comment]
Awesome ! Any idea when this is going to be merged ? 
We can't create cosmos accounts w/ the 3.6 backend without this change.

**Comment by aristosvo** [comment]
@katbyte can you give us an indication when you have time for a review? It are just a few lines of code.

@dany74q I’m using it already myself based on my custom build, I can send it to you if you’d like that or follow the instructions in the repository.

**Comment by katbyte** [comment]
For now you could add a validation function onto the `capabilities` property. Looking at the schema now i am thinking in 2.0 we may want to make it a set of strings rather then a set of `name=capability` 🤔

**Comment by katbyte** [comment]
@aristosvo, wrt validations I really like your idea of adding boolean properties to the `capabilities` block, however that would be a breaking change that should be done for 2.0.

**Pull request merged**
