### PR TITLE
`azurerm_subscription(s)` - support for `tags`

### LINKED ISSUE #8443: Add Azure resource tags in each resource's outputs - like Kubernetes "annotations"
_This issue was originally opened by @asnowfix as hashicorp/terraform#26215. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
# Current Terraform Version

```
Terraform v0.12.28
+ provider.azurerm v2.27.0
```

### Use-cases

It is generally useful to add user-defined meta-data on resources. The natural place is "tags". In some cases these meta-data are used to locate/lookup the resource (this is what Kubernetes "labels" are for), but in some other cases these data can be additional information to be used to help set processing parameters on this particular resource when known (this is what Kubernetes "annotations" are for).

Terraform usage of Azure resources tags includes

1. Setting them (it is easy, using a map)
2. Lookup resource by tag values (this is what [azurerm_resources ](https://www.terraform.io/docs/providers/azurerm/d/resources.html) is for)

But it lacks:

3. Reporting tags & their values as resource output (likely as a map)

### Attempted Solutions

No tag in the Terraform output: As I need thees values, I am fetching them using the Azure SDK to insert the tags as tfvars before invoking terraform.

### Proposal

Add a `tags` output property to every data-source in the azurerm from resources that have tags .

### References

_Did not find any_

### PR DESCRIPTION
**Pull request by magodo**
Fixes #8443 

## Test Result

```bash
💤 make testacc TEST=./azurerm/internal/services/subscription/tests TESTARGS='-run TestAccDataSourceAzureRMSubscription'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test ./azurerm/internal/services/subscription/tests -v -run TestAccDataSourceAzureRMSubscription -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceAzureRMSubscription_current
=== PAUSE TestAccDataSourceAzureRMSubscription_current
=== RUN   TestAccDataSourceAzureRMSubscription_specific
=== PAUSE TestAccDataSourceAzureRMSubscription_specific
=== RUN   TestAccDataSourceAzureRMSubscriptions_basic
=== PAUSE TestAccDataSourceAzureRMSubscriptions_basic
=== CONT  TestAccDataSourceAzureRMSubscription_current
=== CONT  TestAccDataSourceAzureRMSubscriptions_basic
=== CONT  TestAccDataSourceAzureRMSubscription_specific
--- PASS: TestAccDataSourceAzureRMSubscription_specific (53.67s)
--- PASS: TestAccDataSourceAzureRMSubscription_current (54.10s)
--- PASS: TestAccDataSourceAzureRMSubscriptions_basic (63.96s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/subscription/tests  63.994s
```

Additionally, I tried to run against a subscription which has tags created:

```bash
tf_config/azure/subscription via 💠 default 
💤 tf apply -auto-approve
data.azurerm_subscription.current: Refreshing state... [id=/subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

foo = {
  "a" = "a"
  "b" = "b"
}

tf_config/azure/subscription via 💠 default took 36s 
💤 cat main.tf 
provider "azurerm" {
  features {}
}

data "azurerm_subscription" "current" {}

output "foo" {
  value = data.azurerm_subscription.current.tags
}
```

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
@magodo, could we change this to use the subscription api like in #8064? thanks!

**Comment by magodo** [comment]
@katbyte Sorry that I didn't get your point, which subscription API do you mean (maybe you attached the wrong link)?

**Comment by magodo** [comment]
@katbyte I assume you mean #9456? I've updated accordingly and tested locally. Please take a look!

**Review by katbyte — APPROVED** [review]
Thanks  @magodo - this LGTM 👍

**Pull request merged**
