### PR TITLE
Force recreation if storage_data_disk.creation_option changes

### PR DESCRIPTION
**Pull request by thiagocaiubi**
I'm not sure how to test this change, please provide any feedback to help me with it.

Azure Resource Manager API doesn't support changes to this field. It
should recreate the virtual machine and attach the disks again.

### Actual Behaviour:

module.xpto.azurerm_virtual_machine.prometheus_virtual_machine:
Modifying... (ID: /subscriptions/xxxxx...ute/virtualMachines/vm)
  delete_data_disks_on_termination:  "" => "false"
  delete_os_disk_on_termination:     "" => "true"
  storage_data_disk.0.create_option: "Empty" => "Attach"
  storage_data_disk.1.create_option: "Empty" => "Attach"
  tags.%:                            "0" => "1"
  tags.role:                         "" => "xpto"
Error applying plan:

1 error(s) occurred:

* module.xpto.azurerm_virtual_machine.vm: 1 error(s) occurred:

* azurerm_virtual_machine.prometheus_virtual_machine:
compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to
request: StatusCode=409 -- Original Error: autorest/azure: Service
returned an error. Status=409 Code="PropertyChangeNotAllowed"
Message="Changing property 'dataDisk.createOption' is not allowed."

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Hey @thiagocaiubi 

Thanks for opening this PR :)

> I'm not sure how to test this change, please provide any feedback to help me with it.

So the best way to do this is to add an acceptance test which has multiple phases - for instance in [this example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_virtual_machine_unmanaged_disks_test.go#L435). Essentially, we'd need to create a Virtual Machine with `creation_option` set to `Empty` - and then in an updated Terraform configuration switch that field to `Attach`. With regards to verifying that the machine has been recreated - there's an example of that [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_virtual_machine_unmanaged_disks_test.go#L373) :)

Those tests can then be run via:

```
TF_ACC=1 go test ./azurerm -v -timeout 120m -run TestAccAzureRMPostgreSQLConfiguration_backslashQuote
```

.. where `TestAccAzureRMPostgreSQLConfiguration_backslashQuote` is the test name. Running the tests presumes you have the environment variables set, [as defined here](https://www.terraform.io/docs/providers/azurerm/index.html#testing) - and will complain if not.

I'm hoping that makes sense? However this change looks sensible to me - I'd actually run into this earlier today too :)

Thanks!

**Comment by thiagocaiubi** [comment]
Hi @tombuildsstuff, thanks for the very informative explanation. 
I've update the PR based on the examples that you pointed out unfortunately I'm facing the following issue: 

```
TF_ACC=1 go test ./azurerm -v -timeout 120m -run TestAccAzureRMVirtualMachine_changeStorageDataDiskCreationOption
=== RUN   TestAccAzureRMVirtualMachine_changeStorageDataDiskCreationOption
--- FAIL: TestAccAzureRMVirtualMachine_changeStorageDataDiskCreationOption (495.48s)
        testing.go:428: Step 1 error: Error applying: 1 error(s) occurred:

                * azurerm_virtual_machine.test: 1 error(s) occurred:

                * azurerm_virtual_machine.test: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="The entity was not found."
FAIL
exit status 1
FAIL    github.com/terraform-providers/terraform-provider-azurerm/azurerm       495.597s
```

**Comment by tombuildsstuff** [comment]
Hey @thiagocaiubi 

Thanks for pushing those updates :)

I may be wrong, but taking a quick glance I think the issue may be that [the disks are being deleted when the Original VM is](https://github.com/terraform-providers/terraform-provider-azurerm/pull/218/files#diff-904ed26d6f062637d93fa33ea8773ac5R531) - would it be possible to check by removing those two fields? Terraform will automatically clear up the config once it's finished the test, so they shouldn't be needed :)

Thanks!

**Comment by thiagocaiubi** [comment]
Hi @tombuildsstuff , thanks! 😄 👍 

```
TF_ACC=1 go test ./azurerm -v -timeout 120m -run TestAccAzureRMVirtualMachine_changeStorageDataDiskCreationOption
=== RUN   TestAccAzureRMVirtualMachine_changeStorageDataDiskCreationOption
--- PASS: TestAccAzureRMVirtualMachine_changeStorageDataDiskCreationOption (791.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm       791.691s
```

**Comment by tombuildsstuff** [comment]
@thiagocaiubi apologies, I pushed a commit to this branch (to switch the OS version to Ubuntu 16 after #237) which apparently closed this PR.. I'll re-open it, sorry!

**Comment by thiagocaiubi** [comment]
@tombuildsstuff there is nothing to apologize for. The more important is making terraform better each day. I'm very happy to contribute back every now and then. 👍

**Pull request closed without merging**
