### PR TITLE
[WIP] App service source control

### LINKED ISSUE #3696: azurerm_app_service unable to configure source control.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently source_control block only applies to localGit. There seems to be no way to configure source control for any other scm methods. 
Using this module with scm_type set to other than None or LocalGit results in error:

> Error making Read request on AzureRM App Service Source Control "example-app-test-service-unique": web.AppsClient#GetSourceControl: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Repository 'GetSiteSourceControl' operation failed with System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.\r\n   at System.ThrowHelper.ThrowKeyNotFoundException()\r\n   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<GetSiteSourceControl>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass305_1.<<GetSiteSourceControl>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.GetSiteSourceControl(String subscriptionName, String webspaceName, String name)." Details=[{"Message":"Repository 'GetSiteSourceControl' operation failed with System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.\r\n   at System.ThrowHelper.ThrowKeyNotFoundException()\r\n   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.\u003cGetSiteSourceControl\u003ed__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.\u003c\u003ec__DisplayClass305_1.\u003c\u003cGetSiteSourceControl\u003eb__0\u003ed.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.GetSiteSourceControl(String subscriptionName, String webspaceName, String name)."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"05007","Message":"Repository 'GetSiteSourceControl' operation failed with System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.\r\n   at System.ThrowHelper.ThrowKeyNotFoundException()\r\n   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.\u003cGetSiteSourceControl\u003ed__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.\u003c\u003ec__DisplayClass305_1.\u003c\u003cGetSiteSourceControl\u003eb__0\u003ed.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.GetSiteSourceControl(String subscriptionName, String webspaceName, String name).","MessageTemplate":"Repository '{0}' operation failed with {1}.","Parameters":["GetSiteSourceControl","System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.\r\n   at System.ThrowHelper.ThrowKeyNotFoundException()\r\n   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.\u003cGetSiteSourceControl\u003ed__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.\u003c\u003ec__DisplayClass305_1.\u003c\u003cGetSiteSourceControl\u003eb__0\u003ed.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.GetSiteSourceControl(String subscriptionName, String webspaceName, String name)"]}}]

### New or Affected Resource(s)

azurerm_app_service

### Potential Terraform Configuration

```hcl
  site_config {
    scm_type    = "ExternalGit"
  }

  source_control {
    repo_url = "https://github.com/azureappserviceoss/wordpress-azure"
    branch = "master"
  }
```
```hcl
  site_config {
    scm_type    = "GitHub"
  }

  source_control {
    repo_url = "https://github.com/azureappserviceoss/wordpress-azure"
    branch = "master"
  }
```
### References

* https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest
* https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-github-deploy/azuredeploy.json

### LINKED ISSUE #4952: azurerm_function_app missing remote Git source control options
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am using the *azurerm_function_app* resource and I want to deploy my code to it from GitHub using an external Git source repo URL. This is a standard feature of all Azure App Services including Function Apps.

You already support this in the *azurerm_app_service* but for some reason have removed/omitted it from the azurerm_function_app despite from an Azure ARM perspective they are the same thing.

This was requested here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1801 and closed as duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/1104

But https://github.com/terraform-providers/terraform-provider-azurerm/issues/1104 only added the source_control support for * azurerm_app_service*

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "foo" {
  name = "bar"
  location = "northeurope"
  app_service_plan_id = "${azurerm_app_service_plan.blahblah.id}"
  source_control {
    repo_url = "https://github.com/benc-uk/serverless-cognitive.git"
    branch = "master"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code
* Here is a working ARM template with this feature https://github.com/benc-uk/azure-arm/blob/master/old/paas-other/function-app-withcode/azuredeploy.json

### LINKED ISSUE #5366: azurerm_app_service: Set external repository URL
I noticed in issue #1104 that a plethora of SCM types were added to the azurerm_app_service resource and I see it in the documentation. However, I don't see an option to set something such as the external GitHub repository URL. Does such an option exist, yet? I'm still having to use ARM templates to set the external repository URL (for Wordpress in this case). If it doesn't exist, consider this a feature request to set external GitHub repository URL.

### PR DESCRIPTION
**Pull request by joakimhellum**
- [x] New resource: `azurerm_app_service_source_control`
- [ ] `azurerm_app_service`: support for setting fields within the `source_control` block
  - Implementing this is a bit of a hack, see https://github.com/terraform-providers/terraform-provider-azurerm/issues/3696#issuecomment-529224458
- [ ] `azurerm_function_app`: support for setting fields within the `source_control` block
- [ ] Additional tests
- [ ] Additional documentation and examples (describing manual integration and which providers support continuous deployment)

Fixes #5366
Fixes #4952
Fixes #3696

Not sure if to add tests for the different source control providers, since it requires a source control token to be configured.

Wanted start discussion on how to add support for managing source control for an app service before `v2.0.0` release, in case a breaking change is preferred.

References:
- https://github.com/projectkudu/kudu/wiki/Continuous-deployment
- https://godoc.org/github.com/Azure/azure-sdk-for-go/services/web/mgmt/2018-02-01/web#AppsClient.CreateOrUpdateSourceControl
- https://docs.microsoft.com/bs-latn-ba/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config

### CODE REVIEW

**Comment by katbyte** [comment]
Hi @joakimhellum, wondering if your still working on this or is it ready for a review? 🤔

**Comment by joakimhellum** [comment]
@katbyte Sorry about the lack of updates here. We're still working on this, but have been testing this in forked repo for a while, and then forgot about this PR. This requried alot more work with testing the source control providers than first expected. Will clean up, rebase onto newest master and provide updates regarding the different source control providers during weekend.

**Comment by katbyte** [comment]
thanks @joakimhellum! 🙂

**Comment by jackofallops** [comment]
Hi @joakimhellum - I'm going to close this PR for now since there has been no activity for a couple of months.  If you have opportunity to return to working on this feature we can either re-open or create a new PR, whichever is more appropriate at the time.

Thanks

**Comment by al-lac** [comment]
Please start working on this pull request again soon. It is quite confusing that there are GitHub / Bitbucket / etc. options for the app service scm_type option. But setting them to GitHub or anything else other than "LocalGit" basically just ends in a broken deployment center. 

I do not want to use Azure RM Templates just because of this.

**Pull request closed without merging**
