### PR TITLE
Azure policy rest version bump to 2019-09-01

### LINKED ISSUE #7210: Support for Policies with all modes not only All, Indexed
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
New azure policoes require the field mode to be set to custom values, such as, `"Microsoft.Kubernetes.Data"` This is already supported on newer versions of the API. 

### New or Affected Resource(s)
* `policy_assignment_resource`
* `policy_definition_data_source`
* `policy_definition_resource`
* `policy_set_definition_data_source`
* `policy_set_definition_resource`

### Potential Terraform Configuration
There are no breaking changes

### References
* https://docs.microsoft.com/en-us/rest/api/resources/policydefinitions

### PR DESCRIPTION
**Pull request by jlpedrosa**
Azure sdk for policies bump to version '2019-09-01'.

References: #7210 

Fixes  #7210

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @jlpedrosa thanks for this PR.
But I am afraid that this is a duplicate of PR #7018

**Comment by jlpedrosa** [comment]
Hi @ArcturusZhang 
This PR is looking to be 100% backwards compatible and not introduce any breaking change. The tests don't need to be changed and existing acctests are passing just fine. As this is already an XXL change (but smaller than he other PR) maybe it's easier to merge this one and latter add the new feature. 
What ever they decide is fine for me as long as one of them gets merged.

**Comment by ArcturusZhang** [comment]
Hi @jlpedrosa make sense. Looking forward for this getting merged, and I then will rebase mine on this. Thanks!

**Comment by jlpedrosa** [comment]
Hi @ArcturusZhang 
This PR has been merged. I think you could rebase yours master and update it.

**Pull request merged**
