### PR TITLE
avoid diff for property "api_server_authorized_ip_ranges"

### PR DESCRIPTION
**Pull request by njuCZ**
fix issue #10500

image

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hey @njuCZ 

Thanks for this PR.

Taking a look through here this appears to be an API bug rather than something which Terraform should support - the description for this field in the SDK Is:

> // AuthorizedIPRanges - Authorized IP Ranges to kubernetes API server.

Since this is expecting an IP Range rather than a single IP address, it's likely this could change in the future to restrict this to an IP Range instead - so whilst we could look to add support for these, since the field itself is specifically mentioning an IP Range rather than an IP and/or an IP Range for the moment we need to assume this is a range.

Would you be able to reach out to the service team to confirm if this behaviour is intentional or a bug so that we can work out how to proceed here?

Thanks!

**Comment by katbyte** [comment]
@njuCZ - any updates here?

**Comment by njuCZ** [comment]
hi @katbyte, it actually should be IP ranges from service team. So should we use more specific validation rule?

**Comment by katbyte** [comment]
@njuCZ - it appears the service does accept single IP addresses, is this something they will fix/we shouldn't allow?

**Comment by njuCZ** [comment]
sorry, still get no official reply from aks team. I will close it for now. If there is any further information, I will reopen it. Thanks

**Pull request closed without merging**
