### PR TITLE
azurerm_kubernetes_cluster - add support for network_mode

### LINKED ISSUE #8827: azurerm_kubernetes_cluster - add support for network_mode in network_profile
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for network_mode in network_profile of azurem_kubernetes_cluster.
This is useful for the Azure-CNI which can operate in bridge or transparent modes.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "${var.prefix}-k8s"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "${var.prefix}-k8s"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_DS2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  network_profile {
    network_plugin = "azure"
    network_mode = "transparent"
  }

  addon_profile {
    aci_connector_linux {
      enabled = false
    }

    azure_policy {
      enabled = false
    }

    http_application_routing {
      enabled = false
    }

    kube_dashboard {
      enabled = true
    }

    oms_agent {
      enabled = false
    }
  }
}
```

### References

* #0000

### PR DESCRIPTION
**Pull request by Teller-Ulam**
Solves #8827
I could use some help writing tests for this.

(fixes #8827)

### CODE REVIEW

**Comment by jfair9** [comment]
Any updates on this? I have a need to deploy Calico Enterprise into AKS which requires the Transparent network_mode and I'm dreading needing to fall back on ARM templates to manage the AKS deployment.

**Review by katbyte — APPROVED** [review]
Thanks @Teller-Ulam - this LGTM 👍

**Comment by jackofallops** [comment]
Hi @Teller-Ulam - Hope you don't mind, but I've added some tests and tweaked this a little. I'll get the tests kicked off (they take a while) and hopefully this should be good to merge.

**Comment by Teller-Ulam** [comment]
Thank you @jackofallops that is awesome! I don't mind at all.

**Comment by jackofallops** [comment]
Tests looking OK, failures are transient:
image

**Pull request merged**
