### PR TITLE
Use API version 2020-03-01 for Loadbalancer

### LINKED ISSUE #7691: 2.18.0 - Error removing/updating load balancer rules
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.9
+ provider.azurerm v2.18.0

### Affected Resource(s)

* `azurerm_lb_rule`

### Expected Behavior

Something seems to have gone terribly wrong with deleting load balancer rules in 2.18.0 (I guess due to the new network SDK?), I'm seeing the error below.
It is fine with 2.17.0

### Actual Behavior

Error: Error Creating/Updating Load Balancer "management" (Resource Group "cbuk-core-cibuild173945-sfha-uksouth"): network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|sharedz1|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/30bcd4a9-4db4-4650-9681-420cad939976."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|systemz3|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/f238075c-2ede-4fb0-87a3-cb7d02bead59."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|sharedz3|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/8127b097-ac32-4f5d-b42a-7332ef3b4e82."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z1|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/7c2705e3-691f-41af-8440-8a6859e07351."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z2|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/80961ff3-64be-4fe9-b255-efa45bdafc0c."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|sharedz2|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/f2589883-33d7-4e06-a84c-e0e07fd18638."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|systemz1|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/6b6f9d8d-33c9-4694-91ba-74c4ab3fddf1."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z3|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/d3458da3-bd1e-488f-99e3-0e0374651e7a."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|systemz2|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/7a81fa47-26bf-4f2b-b8da-9de216f99a63."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z1|virtualMachines|1|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/d1260d1b-e317-44d7-a836-62c09b811e6a."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z1|virtualMachines|2|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/f17c9c33-dfd5-4089-886a-db818796f7f4."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z1|virtualMachines|3|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/71a23a75-f11a-4069-a161-77dfbb0d5a5e."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z1|virtualMachines|4|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/448a3115-3af8-429b-9126-def0034484f6."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z3|virtualMachines|1|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/f60c2431-8ec2-4151-a7fe-7fbeba0eca17."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z3|virtualMachines|2|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/436843e6-f740-4db2-a75b-b81c42ec323f."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z3|virtualMachines|3|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/23c90f13-f9d1-49d6-bd73-5c1092903a04."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z3|virtualMachines|4|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/3a8d05e6-37da-46ce-a76b-1782ee057dbe."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z2|virtualMachines|1|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/2c3183ef-617e-4899-9eb4-f45c9b3cd9f3."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z2|virtualMachines|2|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/bd155699-fd49-48f9-843b-67cd22cd6383."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z2|virtualMachines|3|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/36d72ce3-1d5a-4b2f-ae29-ba401880f15b."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|ci1z2|virtualMachines|4|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/outbound/loadBalancerBackendAddresses/b94dbb0f-2999-4613-ac59-a7030ae85d60."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|systemz3|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/management/loadBalancerBackendAddresses/dda2105f-a1b6-4f58-8dce-d4b8fd477582."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|systemz1|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/management/loadBalancerBackendAddresses/9426514c-33b3-47f8-bd2b-dfd71c8d8bf3."},{"code":"DuplicateIpConfigurationReferenceOnBackendAddressPool","message":"Found duplicate ipConfiguration reference /subscriptions/xxx/resourceGroups/cbuk-core-cibuild173945-sfha-uksouth/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|systemz2|virtualMachines|0|networkInterfaces|primary/ipConfigurations/primary on backend pool addresses /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools//loadBalancerBackendAddresses/ and /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers//backendAddressPools/management/loadBalancerBackendAddresses/638719a2-c00a-495b-8244-2b794e25098d."}]

### Steps to Reproduce

1. `terraform destroy`

### PR DESCRIPTION
**Pull request by marc-sensenich**
Closes #7691 by using the 2020-03-01 network API version. Based off a comment by @tombuildsstuff from #7741 as this issue is present on more than just `azurerm_lb_rule` deletion 

The reason for that issue is that service can't tolerate the client sending properties.backendAddressPools.n.properties.backendIPConfigurations in request body for load balancer resource since 2020-05-01, as it is a READ-ONLY attribute (this only occurs when azurerm_lb's sku is Standard).
Currently, Azure Go SDK can trim the READ-ONLY attributes during marshaling, but only for the root level attributes, so, in this case, Go SDK will still marshal the attribute into the request body. This is tracked in issue: Azure/autorest.go#438.

**Acceptance Tests**

```
--- PASS: TestAccAzureRMLoadBalancer_standard (74.84s)
--- PASS: TestAccAzureRMLoadBalancer_requiresImport (126.75s)
--- PASS: TestAccAzureRMLoadBalancerRule_disappears (136.04s)
--- PASS: TestAccAzureRMLoadBalancerBackEndAddressPool_basic (140.11s)
--- PASS: TestAccAzureRMLoadBalancerRule_updateMultipleRules (211.43s)
--- PASS: TestAccAzureRMLoadBalancerRule_removal (211.44s)
--- PASS: TestAccAzureRMLoadBalancer_basic (136.61s)
--- PASS: TestAccAzureRMLoadBalancerRule_inconsistentReads (211.45s)
--- PASS: TestAccAzureRMLoadBalancerProbe_basic (321.01s)
--- PASS: TestAccAzureRMLoadBalancer_frontEndConfigPublicIPPrefix (132.72s)
--- PASS: TestAccAzureRMLoadBalancerRule_complete (147.61s)
--- PASS: TestAccAzureRMLoadBalancerProbe_update (341.34s)
--- PASS: TestAccAzureRMLoadBalancerRule_basic (137.91s)
--- PASS: TestAccAzureRMLoadBalancerProbe_requiresImport (169.84s)
--- PASS: TestAccAzureRMLoadBalancerProbe_disappears (392.64s)
--- PASS: TestAccAzureRMLoadBalancerProbe_removal (202.78s)
--- PASS: TestAccAzureRMLoadBalancerProbe_updateProtocol (389.76s)
--- PASS: TestAccAzureRMLoadBalancerRule_update (1464.92s)
--- PASS: TestAccAzureRMLoadBalancerNatPool_removal (1194.92s)
--- PASS: TestAccAzureRMLoadBalancerRule_requiresImport (1464.96s)
--- PASS: TestAccAzureRMLoadBalancer_privateIP (1179.42s)
--- PASS: TestAccAzureRMLoadBalancer_emptyPrivateIP (1157.00s)
--- PASS: TestAccAzureRMLoadBalancerNatRule_basic (1152.61s)
--- PASS: TestAccAzureRMLoadBalancerNatRule_complete (1162.42s)
--- PASS: TestAccAzureRMLoadBalancer_tags (1196.95s)
--- PASS: TestAccAzureRMLoadBalancerOutboundRule_disappears (94.63s)
--- PASS: TestAccAzureRMLoadBalancerOutboundRule_requiresImport (105.37s)
--- PASS: TestAccAzureRMLoadBalancerNatPool_requiresImport (145.97s)
--- PASS: TestAccAzureRMLoadBalancerNatPool_disappears (149.86s)
--- PASS: TestAccAzureRMLoadBalancerBackEndAddressPool_disappears (156.94s)
--- PASS: TestAccAzureRMLoadBalancerNatPool_update (173.39s)
--- PASS: TestAccAzureRMLoadBalancer_frontEndConfig (213.04s)
--- PASS: TestAccAzureRMLoadBalancerOutboundRule_basic (119.46s)
--- PASS: TestAccAzureRMLoadBalancerNatPool_basic (137.47s)
--- PASS: TestAccAzureRMLoadBalancerNatRule_update (192.43s)
--- PASS: TestAccAzureRMLoadBalancerNatRule_disappears (137.54s)
--- PASS: TestAccAzureRMLoadBalancerOutboundRule_update (118.24s)
--- PASS: TestAccAzureRMLoadBalancerOutboundRule_withPublicIPPrefix (164.61s)
--- PASS: TestAccAzureRMLoadBalancerNatRule_updateMultipleRules (193.30s)
--- PASS: TestAccAzureRMLoadBalancerNatRule_removal (171.90s)
--- PASS: TestAccAzureRMLoadBalancerNatRule_requiresImport (180.32s)
--- PASS: TestAccAzureRMLoadBalancerOutboundRule_removal (201.86s)
--- PASS: TestAccAzureRMLoadBalancerBackEndAddressPool_requiresImport (181.10s)
--- PASS: TestAccAzureRMLoadBalancerBackEndAddressPool_removal (226.18s)
```

### CODE REVIEW

**Comment by hbuckle** [comment]
Can someone please review this? Load balancers have been broken for more than a month now

**Comment by marc-sensenich** [comment]
@magodo is this one on your radar based on our Slack conversation?

**Comment by magodo** [comment]
@marc-sensenich Yes, I have looked through this PR and it LGTM, thanks :+1: 

While downgrading API version needs some thoughts and tests, I am discussing with other maintainers for their opinions on this PR. In the meanwhile, we have some fix in the new Go SDK for the LB issue and trying hard to integrate into terraform azurerm provider.

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this / apologies for the delay here @marc-sensenich

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2020-08-19 at 11 02 28

**Pull request merged**
