### PR TITLE
New Resource: `azurerm_policy_assignment`

### LINKED ISSUE #46: Feature Request: Resource Policy Resource
_This issue was originally opened by @flacito as hashicorp/terraform#12695. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-policy

Would be great to see these eventually arive in the azurerm built-in provider.

### PR DESCRIPTION
**Pull request by tombuildsstuff**
```
$ acctests azurerm TestAccAzureRMPolicyAssignment_
=== RUN   TestAccAzureRMPolicyAssignment_basic
--- PASS: TestAccAzureRMPolicyAssignment_basic (262.01s)
=== RUN   TestAccAzureRMPolicyAssignment_complete
--- PASS: TestAccAzureRMPolicyAssignment_complete (257.42s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	519.467s
```

Fixes #46

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Policy Definitions tests pass:

```
$ acctests azurerm TestAccAzureRMPolicyDefinition_
=== RUN   TestAccAzureRMPolicyDefinition_importBasic
--- PASS: TestAccAzureRMPolicyDefinition_importBasic (116.69s)
=== RUN   TestAccAzureRMPolicyDefinition_basic
--- PASS: TestAccAzureRMPolicyDefinition_basic (112.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	228.755s
```

**Comment by tombuildsstuff** [comment]
Import tests pass:

```
$ acctests azurerm TestAccAzureRMPolicyAssignment_importComplete
=== RUN   TestAccAzureRMPolicyAssignment_importComplete
--- PASS: TestAccAzureRMPolicyAssignment_importComplete (300.40s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	300.433s
```

**Comment by JamesDLD** [comment]
Thanks for this usefull resource.
Could you please update the documentation : https://www.terraform.io/docs/providers/azurerm/r/policy_assignment.html

By replacing this sentence 

> scope- (Required) The Scope at which the Policy Assignment should be applied. This can either be the Subscription (e.g. /subscriptions/00000000-0000-0000-000000000000) or a Resource Group (e.g./subscriptions/00000000-0000-0000-000000000000/resourceGroups/myResourceGroup). Changing this forces a new resource to be created.

By

> scope- (Required) The Scope at which the Policy Assignment should be applied. This can either be the Subscription (e.g. /subscriptions/00000000-0000-0000-000000000000) or a Resource Group (e.g./subscriptions/00000000-0000-0000-000000000000/resourceGroups/myResourceGroup) or **a Resource (e.g./subscriptions/00000000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirutalNetwork)**. Changing this forces a new resource to be created.

**Comment by JamesDLD** [comment]
Hello @katbyte 
of course you can find the powershell associated page for example : https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/new-azurermpolicyassignment?view=azurermps-6.2.0

The First samples shows how to assign a policy to a Resource type : Resource Group.

Here I did it on several objects like : Resource Group, Virtual Network, Recovery Services Vault : https://github.com/JamesDLD/terraform

**Comment by tombuildsstuff** [comment]
@katbyte @JamesDLD in this case I'd suggest we say `Resource ID` rather than giving an example of a Resource ID as these can be case-sensitive within Azure (which is why we use Data Sources rather than hard-coding ID's in examples, where at all possible).

@JamesDLD would you mind opening a new issue specifically for this? Thanks! :)

**Comment by JamesDLD** [comment]
Look great to me @tombuildsstuff  @katbyte , just did create this ticket #1420 accordingly.

**Pull request merged**
