### PR TITLE
r/kubernetes_cluster: handling breaking changes in the AKS API

### LINKED ISSUE #6094: `azurerm_kubernetes_cluster`: `node_count` is always `nil` after initial creation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `azurerm_2.1.0`
* `TF 0.12.21`

### Affected Resource(s)

* `azurerm_kubernetes_cluster`
* `default_node_pool`

### Terraform Configuration Files

```hcl
...
default_node_pool {
    ...
    node_count          = 1
    enable_auto_scaling = false
    ...
}
...
```

### Expected Behavior
No error occuring for default_node_pool.

### Actual Behavior

```
Error: Error updating Default Node Pool "lhg-weur-kfkadevmdw-aks" (Resource Group "lhg-weur-kfkadevmdwaks-rg"): containerservice.AgentPoolsClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedClusterAgentPoolProfileProperties.Count constraint=Null value=(*int32)(nil) details: value can not be null; required parameter
```

I explicitly do NOT set `min_count` and `max_count` at all in that case (autoscaling = false). But when I check the state this is set (again), although if I remove the fields manually from it - maybe thats not relevant and is the default behavior anyways:

```
    default_node_pool {
        availability_zones    = [
            "1",
        ]
        enable_auto_scaling   = false
        enable_node_public_ip = false
        max_count             = 0
        max_pods              = 250
        min_count             = 0
        name                  = "default"
        node_count            = 1
        node_labels           = {}
        node_taints           = []
        os_disk_size_gb       = 128
        tags                  = {}
        type                  = "VirtualMachineScaleSets"
        vm_size               = "Standard_D2s_v3"
        vnet_subnet_id        = "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/virtualNetworks/zzz/subnets/aaa"
    }
```

Then if I change the `max_count` and `min_count` to `node_count` (in my example its `1`) I get:

```
Error: Error expanding `default_node_pool`: `max_count` and `min_count` must be set to `0` when enable_auto_scaling is set to `false`
```

It might be the issue is because range is not 0...100, but: 1...100

https://github.com/terraform-providers/terraform-provider-azurerm/blob/55eb723a30da21919865262d49995493ddaf0ce3/azurerm/internal/services/containers/kubernetes_nodepool.go#L71

https://github.com/terraform-providers/terraform-provider-azurerm/blob/55eb723a30da21919865262d49995493ddaf0ce3/azurerm/internal/services/containers/kubernetes_nodepool.go#L84

In #6020 something similar was done for the additional node pools, but it seems not for the default_node_pool.

### References

* #6020

### LINKED ISSUE #6178: AKS Managed Identity configuration can't be used without `service_principal` block
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform version 0.12.20
* Azurerm Provider version 2.1.0 
### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                = "aks"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  dns_prefix          = "aks"
  kubernetes_version  = "1.15.7"

  default_node_pool {
    name        = "default"
    min_count   = 1
    max_count   = 5
    vm_size     = "Standard_D2_v2"
    type        = "VirtualMachineScaleSets"
    node_labels = {
      "pool"= "infra"
    }
    enable_auto_scaling = true
    vnet_subnet_id      = azurerm_subnet.aks_subnet.id
  }

  role_based_access_control {
    enabled = true
  }

  network_profile {
    network_plugin     = "azure"
    network_policy     = "azure"
    docker_bridge_cidr = "172.17.0.1/16"
    service_cidr       = "10.0.16.0/24"
    dns_service_ip     = "10.0.16.10"
    load_balancer_sku  = "Standard"
  }

  identity {
    type = "SystemAssigned"
  }

  lifecycle {
    ignore_changes = [default_node_pool[0].node_count]
  }
}
```

### Debug Output

```
+ terraform plan -var-file=terraform.tfvars -out=plan.tfplan

Error: "service_principal": required field is not set

  on aks.tf line 1, in resource "azurerm_kubernetes_cluster" "aks":
   1: resource "azurerm_kubernetes_cluster" "aks" {
```

### Expected Behavior

According to #5278, now that system managed identity for AKS is available we should be able to skip the service_principal block in the AKS configuration. The current configuration forces you to set `service_principal` (I believe the update changed back when rebased on PR #5339).

### Steps to Reproduce

Run terraform with the above configuration for AKS. I have a bare subnet and resource group deployed that I am executing terraform against.

### Important Factoids

Nothing special

### References

* #5278
* #5339 - reverted the change that made service principal optional

### LINKED ISSUE #6235: azurerm_kubernetes_cluster forces redeployment of recent cluster due to windows_profile
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

TF v0.12.24 - AzureRM 2.2.0

### Affected Resource(s)

azure_kubernetes_cluster

### Terraform Configuration Files

Any recently deployed cluster with no "windows_profile" gets provisioned fine.
On any subsequent run, TF tries to redeploy the cluster referencing a change in that block.

```
      - windows_profile {
          - admin_username = "azureuser" -> null # forces replacement
        }
```

### References

* See behavior change in Azure AKS at https://github.com/Azure/AKS/releases/tag/2020-03-09

### LINKED ISSUE #6257: azurerm_kubernetes_cluster  gridlocks future terraform apply due to it deciding to also change service_principal
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
TF 0.12.23, azure 2.2.0

### Affected Resource(s)
azurerm_kubernetes_cluster  

### Terraform Configuration Files
```
  service_principal {
    client_id     = var.clientid
    client_secret = var.clientsecret
  }
```
### Debug Output
the cluster's initial deployment works, but then a future plan results in:
      ~ service_principal {
          ~ client_id     = "msi" -> "<REDACTED-SP-CLIENTID_UUID>"
            client_secret = (sensitive value)
        }
and then the apply errors with:
Error: Error updating Service Principal for Kubernetes Cluster "K8Scluster" (Resource Group "lab1"): containerservice.ManagedClustersClient#ResetServicePrincipalProfile: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Updating service principal profile is not allowed on MSI cluster."

  on modules\k8s\main.tf line 23, in resource "azurerm_kubernetes_cluster" "k8s":
  23: resource "azurerm_kubernetes_cluster" "k8s" {

### Expected Behavior

resource should be unchanged

### PR DESCRIPTION
**Pull request by wagnst**
BREAKING CHANGES:

* Azure Kubernetes Service
	* Due to a breaking change in the AKS API, the `azurerm_kubernetes_cluster` resource features a significant behavioural change where creating Mixed-Mode Authentication clusters (e.g. using a Service Principal with a Managed Identity) is no longer supported.
	* The AKS Team have confirmed that existing clusters will be updated by the Azure API to use only MSI when a change is made to the Cluster (but not the Node Pool). Whilst Terraform could perform this automatically some environments have restrictions on which tags can be added/removed - as such this operation will need to be performed out-of-band. Instead, upon detecting a Mixed-Mode Cluster which has not yet been updated - or upon detecting a former Mixed-Mode Cluster where the Terraform Configuration still contains a `service_principal` block - Terraform will output instructions on how to proceed.
	* `azurerm_kubernetes_cluster_node_pool` - clusters with auto-scale disabled must ensure that `min_count` and `max_count` are set to `null` (or omitted) rather than `0` (since 0 isn't a valid value for these fields).

NOTES:

* There's currently a bug in the Azure Kubernetes Service (AKS) API where the Tags on Node Pools are returned in the incorrect case - [this bug is being tracked in this issue](https://github.com/Azure/azure-rest-api-specs/issues/8952). This affects the `tags` field within the `default_node_pool` block for `azurerm_kubernetes_clusters` and the `tags` field for the `azurerm_kubernetes_cluster_node_pool` resource.
IMPROVEMENTS:

* dependencies: updating to use version `2020-02-01` of the Containers API [GH-6095]
* `azurerm_kubernetes_cluster` - making the `service_principal` block optional - so it's now possible to create MSI-only clusters [GH-6095]
* `azurerm_kubernetes_cluster` - making the `windows_profile` block computed as Windows credentials are now generated by Azure if unspecified [GH-6095]

BUG FIXES:

* `azurerm_kubernetes_cluster` - requiring that `min_count` and `max_count` are set to `null` rather than `0` when auto-scaling is disabled [GH-6095]
* `azurerm_kubernetes_cluster` - ensuring that a value for `node_count` is always passed to the API to match a requirement in the API [GH-6095]
* `azurerm_kubernetes_cluster` - ensuring that `tags` are set into the state for the `default_node_pool` [GH-6095]

Fixes #6094
Fixes #6235
Fixes #6257
Fixes #6178

### CODE REVIEW

**Comment by WodansSon** [comment]
@wagnst, hey... this looks mostly good to me, but I would like to push some changes to your repro as a lot of the logic in the expand function no longer makes any sense now that the RP has change and `node_count` is now a required parameter, if that is ok with you. I also would like to update the documentation and add a couple of test cases if you don't mind.

**Comment by aristosvo** [comment]
For the MSI it would make sense to also expose the `identity profile` with `kubelet identity`, as exposed from the API:
```json
"identityProfile": {
    "kubeletidentity": {
      "clientId": "434c14cc-5fc8-49a2-9f91-8fa25e12e2a2",
      "objectId": "13ca6861-af15-4255-9863-077baa53899f",
      "resourceId": "/subscriptions/6eaaf383-01c1-4431-921c-73577a49128d/resourcegroups/MC_aks-rg_testmsi_westeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/testmsi-agentpool"
    }
  },
```

Do you prefer a separate issue and pull request or could it be included here?

**Comment by tombuildsstuff** [comment]
Ignoring a few broken tests [due to this bug in the AKS API](https://github.com/Azure/azure-rest-api-specs/issues/8952) (which is also an issue before this PR) - the acceptance tests look good to me:

Screenshot 2020-04-06 at 13 58 43

**Comment by tombuildsstuff** [comment]
@aristosvo just seen this - would you mind opening a new issue for that? A PR would be great too - however it's probably easiest to wait until after this PR is merged given the changes to the AKS resource required to handle the breaking changes to the API here

Thanks!

**Pull request merged**
