### PR TITLE
azurerm_backup_policy_file_share add weekly, monthly, and yearly retention

### LINKED ISSUE #10732: Support for azurerm_backup_policy_file_share to support weekly/monthly/yearly retention
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, azurerm_backup_policy_file_share only supports retention daily in the provider, but the actual resource in Azure now supports retention_daily, retention_weekly, retention_monthly, and retention_yearly.

### New or Affected Resource(s)

* azurerm_backup_policy_file_share

### Potential Terraform Configuration

```hcl
resource "azurerm_backup_policy_file_share" "policy" {
  name                = "tfex-recovery-vault-policy"
  resource_group_name = azurerm_resource_group.example.name
  recovery_vault_name = azurerm_recovery_services_vault.vault.name

  timezone = "UTC"

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 10
  }

  retention_weekly {
    count    = 7
    weekdays = ["Sunday", "Wednesday", "Friday", "Saturday"]
  }

  retention_monthly {
    count    = 7
    weekdays = ["Sunday", "Wednesday"]
    weeks    = ["First", "Last"]
  }

  retention_yearly {
    count    = 7
    weekdays = ["Sunday"]
    weeks    = ["Last"]
    months   = ["January"]
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/backup/backup-afs#configure-backup-from-the-recovery-services-vault

### PR DESCRIPTION
**Pull request by IanMoroney**
Fixes #10732

### Features
* Adds weekly, monthly, and yearly retention
* Fixes validation and enforces Azure maximums for daily, weekly, monthly, and annual retention values
* Aligns code to match format of `azurerm_backup_policy_vm`
* Added tests for new scenarios
* Updated documentation

### Potential Terraform Configuration

```hcl
resource "azurerm_backup_policy_file_share" "policy" {
  name                = "tfex-recovery-vault-policy"
  resource_group_name = azurerm_resource_group.example.name
  recovery_vault_name = azurerm_recovery_services_vault.vault.name

  timezone = "UTC"

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 10
  }

  retention_weekly {
    count    = 7
    weekdays = ["Sunday", "Wednesday", "Friday", "Saturday"]
  }

  retention_monthly {
    count    = 7
    weekdays = ["Sunday", "Wednesday"]
    weeks    = ["First", "Last"]
  }

  retention_yearly {
    count    = 7
    weekdays = ["Sunday"]
    weeks    = ["Last"]
    months   = ["January"]
  }
}
```

### Test Results
```
=== RUN   TestAccBackupProtectionPolicyFileShare_basicDaily
=== PAUSE TestAccBackupProtectionPolicyFileShare_basicDaily
=== CONT  TestAccBackupProtectionPolicyFileShare_basicDaily
--- PASS: TestAccBackupProtectionPolicyFileShare_basicDaily (137.30s)
```

```
=== RUN   TestAccBackupProtectionPolicyFileShare_requiresImport
=== PAUSE TestAccBackupProtectionPolicyFileShare_requiresImport
=== CONT  TestAccBackupProtectionPolicyFileShare_requiresImport
--- PASS: TestAccBackupProtectionPolicyFileShare_requiresImport (148.44s)
```

```
=== RUN   TestAccBackupProtectionPolicyFileShare_completeDaily
=== PAUSE TestAccBackupProtectionPolicyFileShare_completeDaily
=== CONT  TestAccBackupProtectionPolicyFileShare_completeDaily
--- PASS: TestAccBackupProtectionPolicyFileShare_completeDaily (135.70s)
```

### CODE REVIEW

**Comment by IanMoroney** [comment]
@WodansSon , could this be a candidate for v2.49.0 ?

**Comment by IanMoroney** [comment]
@tombuildsstuff , would you be able to review this PR as this functionality is needed for a project I'm working on at the moment?
Many thanks!

**Comment by IanMoroney** [comment]
@jackofallops or @katbyte , would you be able to review and assign a milestone?
I don't have the ability to request a review from the Azure Providers group.

**Comment by IanMoroney** [comment]
Can someone review?

**Comment by IanMoroney** [comment]
@manicminer would you be able to review this PR? I'm desperately trying to find someone who can review it..

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the PR @IanMoroney - overall it looks good but i see a couple test failures:
```
------- Stdout: -------
=== RUN   TestAccBackupProtectionPolicyFileShare_updateDaily
=== PAUSE TestAccBackupProtectionPolicyFileShare_updateDaily
=== CONT  TestAccBackupProtectionPolicyFileShare_updateDaily
    testing.go:620: Step 2/3 error: Check failed: 1 error occurred:
        	* Check 6/13 error: azurerm_backup_policy_file_share.test: Attribute 'retention_weekly.0.weekdays.#' expected "2", got "3"
        
--- FAIL: TestAccBackupProtectionPolicyFileShare_updateDaily (188.60s)
FAIL

------- Stderr: -------
2021/03/30 23:03:26 [DEBUG] not using binary driver name, it's no longer needed
2021/03/30 23:03:26 [DEBUG] not using binary driver name, it's no longer needed

------- Stdout: -------
=== RUN   TestAccBackupProtectionPolicyFileShare_updateDailyToPartial
=== PAUSE TestAccBackupProtectionPolicyFileShare_updateDailyToPartial
=== CONT  TestAccBackupProtectionPolicyFileShare_updateDailyToPartial
    testing.go:620: Step 3/4 error: Error running pre-apply refresh: 
        Error: "retention_daily": required field is not set
        
          on config428031155/terraform_plugin_test.tf line 22, in resource "azurerm_backup_policy_file_share" "test":
          22: resource "azurerm_backup_policy_file_share" "test" {
        
        
    testing_new.go:21: WARNING: destroy failed, so remote objects may still exist and be subject to billing
    testing_new.go:21: failed to destroy: 
        Error: "retention_daily": required field is not set
        
          on config428031155/terraform_plugin_test.tf line 22, in resource "azurerm_backup_policy_file_share" "test":
          22: resource "azurerm_backup_policy_file_share" "test" {
        
        
        
--- FAIL: TestAccBackupProtectionPolicyFileShare_updateDailyToPartial (88.01s)
FAIL

------- Stderr: -------
2021/03/30 23:03:26 [DEBUG] not using binary driver name, it's no longer needed

```

could we ensure each timescale is represented in tests? daily, monthly, yearly, then going from daily->monthly->yearly->daily, 

thanks

**Comment by IanMoroney** [comment]
hi @katbyte , test have been corrected and should pass now.
I also resolved the merge conflict due to the stale fork.

**Review by manicminer — CHANGES_REQUESTED** [review]
@IanMoroney Thanks for the updates, this is looking good and the tests are passing. Could you add a test with 4 steps plus imports as per @katbyte's review, with configuration starting at daily, then changing to monthly, yearly and back to daily? Once that's in and passing this should be good to merge, thanks!

**Comment by IanMoroney** [comment]
As discussed, I added more tests.

`make acctests SERVICE='recoveryservices' TESTARGS='-run=TestAccBackupProtectionPolicyFileShare_' TESTTIMEOUT='120m'`

    --- PASS: TestAccBackupProtectionPolicyFileShare_YearlyRetention (137.26s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_WeeklyRetentionImport (174.27s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_requiresImport (176.90s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_WeeklyRetention (182.93s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_completeDaily (183.83s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_MonthlyRetention (185.26s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_updateDailyRetentionToWeekly (193.01s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_YearlyRetentionImport (218.09s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_updateDailyToPartial (226.15s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_basicDaily (226.86s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_MonthlyRetentionImport (228.94s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_updateYearlyRetentionToDaily (231.48s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_updateWeeklyRetentionToMonthly (243.96s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_updateDaily (259.03s)
    --- PASS: TestAccBackupProtectionPolicyFileShare_updateMonthlyRetentionToYearly (275.84s)

**Review by katbyte — APPROVED** [review]
Thanks @IanMoroney - LGTM 👍

**Pull request merged**
