### PR TITLE
New resource `azurerm_stream_analytics_job`

### PR DESCRIPTION
**Pull request by shelleybess**
New Stream Analytics resource for provider.

### CODE REVIEW

**Comment by shelleybess** [comment]
Created using SDK-for-go v11.0.0-beta. Needs update to new version.

**Comment by katbyte** [comment]
Hi @shelleybess,

Thank you for opening this PR and sharing your progress. Just wondering how this is going and if your still working on this resource 🙂

**Comment by shelleybess** [comment]
I am updating and resolved a few issues regarding starting and updating a job. Tests and a refactor are needed.

**Comment by shelleybess** [comment]
There is an issue when a job is created without a transformation. If set to running state it will return an error.

**Comment by r0bnet** [comment]
How's the status about this topic? Would like to use the stream analytics job to avoid a workaround with the ARM deployment.

**Comment by maxbog** [comment]
@shelleybess @katbyte I'm also interested in getting this PR merged ASAP. Is there anything I can help with? What is the status of this PR?

**Comment by maxbog** [comment]
@katbyte This PR seems abandoned by the original author. I'll add documentation, review the code, test it a bit and submit a new PR from my fork with the same commits and my modifications.

**Comment by tombuildsstuff** [comment]
hey @shelleybess 

Firstly, apologies for the delay with this PR - it's been sat at the bottom of the PR Review list for far too long (which is totally my fault!).

In order to understand how we could proceed with support for Stream Analytics I've spent some time looking into what these resources could look like; ultimately since there can only be a single transformation we've ended up merging this into the Stream Analytics Job resource. Since this codebase has diverged quite substantially since this PR was first opened - rather than trying to rebase this and update the Azure SDK to to the latest version, after some investigation it appeared to be faster to start over using the new API (branched from master) than to try and pull these changes in.

As such I'm going to close this PR for the moment - but I'd like to thank you for this contribution; whilst I appreciate this isn't ideal since it means the commits done in this PR won't make it into the Azure Provider (and also that this PR has been idle for so long) - I'll shortly be opening a PR to add support for Stream Analytics Jobs (which should make it into the v1.25 release of the AzureRM Provider) - and support for the remaining resources (Inputs, Outputs and Functions) should make it into the subsequent release.

Thanks!

**Pull request closed without merging**
