### PR TITLE
update api version of LB to 2020-05-01

### PR DESCRIPTION
**Pull request by magodo**
The LB api version is rolled back to 2020-03-01 in #8006 because of issue #7691. Now that the issue has been addressed in Azure/azure-rest-api-specs#10131 and the change has been involved in the Go SDK currently under used. So we shall upgrade the API back to 2020-05-01 so that all network resources are using the same one.

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @magodo

**Comment by tombuildsstuff** [comment]
@magodo how does https://github.com/Azure/azure-rest-api-specs/pull/10131 fix this? That Swagger fix appears to be just re-ordering two fields in the Swagger, rather than doing anything else - IIRC this was an API bug where these fields were being incorrectly mapped?

**Comment by magodo** [comment]
@tombuildsstuff The reason is that the service somehow can't tolerate the first properties to be read only, after swapping the order, the service can correctly decode the request.

Quote from service team:

> We took a look at the issue. The problem is that payload does not match what service expects:
In json payload we see both backendIPConfigurations and loadBalancerBackendAddressesProperties in backendAddressPool child resource.
It is not expected in service side to get the backendIPConfigurations property located first in JSON. That is causing the error on server side when deserialization happens.

**Comment by tombuildsstuff** [comment]
@magodo given the JSON spec states that the keys inside a map are can be in any order (and I can't think of a JSON Serialisation library which supports that?) - that sounds like an API bug which still needs to be resolved? Unfortunately we'd be unable to ship this until this is fixed, due to the design of/monthly churn from the Networking API's

**Comment by magodo** [comment]
Then it is possible that the Go SDK has changed the marshalling code generator to not include readonly properties in the request body (Azure/autorest.go#446)?

**Comment by magodo** [comment]
@tombuildsstuff Yes, you are right. So the reason why it now works seems because [we do not send the other properties in the API request](https://github.com/magodo/terraform-provider-azurerm/blob/de7d098fb7c8b2548e59622356f927a6f5456224/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2020-05-01/network/models.go#L6838-L6838) in Go SDK any more due to Azure/autorest.go#446.

**Comment by tombuildsstuff** [comment]
@magdoo unfortunately that's not something we can depend/reply on, due to the large churn within the Azure SDK - so it's possible for this to subtly break at any time, in a way that's incredibly hard to diagnose?

As such I think this PR is blocked for the moment - can we open a Swagger issue and reach out to the Service Team to get this bug fixed?

**Pull request closed without merging**
