### PR TITLE
match_values not required when the operator is any

### PR DESCRIPTION
**Pull request by uolter**

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
Thanks for the PR @uolter, could we update the documentation for this and add a check to error out if match value is missing when required?

thanks!

**Comment by uolter** [comment]
> Thanks for the PR @uolter, could we update the documentation for this and add a check to error out if match value is missing when required?
> 
> thanks!

Yes, sure! Unfortunately I do not have a deep knowledge with the provider. However in many cases the match_values attribute is not required when the operator is cdn.*Any, while is required with different operator vaules. 
I "fixed" just the one useful to me, but some other match_values need to be fixed and a better validation to be introduces.
Thank you,
Walter (@uolter)

**Comment by katbyte** [comment]
Hey @uolter - this is included in #8850 which i will hopefully merge for the next release, as such i'm going to close this. THanks again for the PR!

**Comment by uolter** [comment]
> Hey @uolter - this is included in #8850 which i will hopefully merge for the next release, as such i'm going to close this. THanks again for the PR!

Yep, thanks a lot!

**Pull request closed without merging**
