### PR TITLE
r/application_gateway: ensuring the casing on `identity_ids` within the `identity` block

### PR DESCRIPTION
**Pull request by JohnDelisle**
Fixes issue with `identity_ids` being case-sensitive, which results in terraform forcing an update on each apply due to case differences in e.g. `.../resourceGroups/...` vs. `.../resourcegroups/...`.  See issue #10029

Tested by building azurerm provider 2.4.0 locally.

### CODE REVIEW

**Comment by favoretti** [comment]
Convert it to generator instead maybe?

**Review by katbyte — DISMISSED** [review]
I'm going to second what @favoretti said, instead of making this property case insensitive we should use the new Parse functions when reading them in from azure to store them in the correct case.

**Comment by JohnDelisle** [comment]
> I'm going to second what @favoretti said, instead of making this property case insensitive we should use the new Parse functions when reading them in from azure to store them in the correct case.

Thanks for the feedback.  Would your suggested approach still achieve the objective of being case-insensitive?

The `identity_ids` could be getting pulled programatically (e.g. as a data source or as a resource elsewhere in the module), or they could be added by humans who expect them to be case-insensitive.

**Comment by katbyte** [comment]
@JohnDelisle - it will treat parts of the resource id as case insensitive (the non user specified bits like resourceGroup), you can see how to generate the parse functions in the resourceid.go files in many of the services now (not sure if they exist for ap gateware, i'm on mobile right now)

**Comment by JohnDelisle** [comment]
I've followed @sharebear's lead in #10105 and using `azurerm/internal/services/msi/parse`.  Tested working with `/ResourceGroup/` and `/resourceGroup/`.

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @JohnDelisle

**Comment by tombuildsstuff** [comment]
Tests look good 👍

**Pull request merged**
