### PR TITLE
Bug: azurerm_kubernetes_cluster errors out with InvalidLoadbalancerProfile on changes

### LINKED ISSUE #6525: InvalidLoadBalancerProfile in AKS
After deplyoing an app with a load balancer into a fresh AKS cluster with no load balancer profile configured (only sku to Standard) and then changing for example number of nodes gives me:

```
Error: Code="InvalidLoadBalancerProfile" Message="Load balancer profile must
specify one of ManagedOutboundIPs, OutboundIPPrefixes and OutboundIPs." 
Target="networkProfile.loadBalancerProfile"
```

Output of  `terrafom apply` which is causing it I guess:

```
            load_balancer_profile {
                effective_outbound_ips    = [
                    "/subscriptions/..../publicIPAddresses/.....",
                ]
                managed_outbound_ip_count = 1
                outbound_ip_address_ids   = []
                outbound_ip_prefix_ids    = []
            }
        }
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
+ provider.azurerm v2.6.0

* #0000

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes  #6525

### CODE REVIEW

**Comment by aristosvo** [comment]
Before:
```
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
TF_ACC=1 go test -v ./azurerm/internal/services/containers/tests/ -run=TestAccAzureRMKubernetesCluster_addAgent -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMKubernetesCluster_addAgent
=== PAUSE TestAccAzureRMKubernetesCluster_addAgent
=== CONT  TestAccAzureRMKubernetesCluster_addAgent
--- FAIL: TestAccAzureRMKubernetesCluster_addAgent (1190.94s)
    testing.go:640: Step 2 error: errors during apply:
        
        Error: updating Managed Kubernetes Cluster "acctestaks200419171809471201" (Resource Group "acctestRG-200419171809471201"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidLoadBalancerProfile" Message="Load balancer profile must specify one of ManagedOutboundIPs, OutboundIPPrefixes and OutboundIPs." Target="networkProfile.loadBalancerProfile"
        
          on /tmp/tf-test124628542/main.tf line 21:
          (source code not available)
        
        
FAIL
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers/tests	1190.991s
FAIL
GNUmakefile:100: recipe for target 'acctests' failed
```

After:
```
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
TF_ACC=1 go test -v ./azurerm/internal/services/containers/tests/ -run=TestAccAzureRMKubernetesCluster_addAgent -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMKubernetesCluster_addAgent
=== PAUSE TestAccAzureRMKubernetesCluster_addAgent
=== CONT  TestAccAzureRMKubernetesCluster_addAgent
--- PASS: TestAccAzureRMKubernetesCluster_addAgent (1507.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers/tests	1507.635s

```

**Comment by sbkg0002** [comment]
This would really help us! Is there anything we can do to help the merge?

**Comment by AntonChernysh** [comment]
Another one is looking forward for this PR to be merged.
===
kubelet_identity is not  exposed in 2.5.0 and we really need 2.6.0 or above but can't do it due to this bug.

**Comment by leiter-jakab** [comment]
@AntonChernysh 

I used this to expose the kubelet identity before 2.6:
```hcl
data "azuread_service_principal" "node_identity" {
  display_name = "${azurerm_kubernetes_cluster.my_cluster.name}-agentpool"
}

output "node_service_principal_id" {
  value = data.azuread_service_principal.node_identity.id
}
```

**Comment by angelbarrera92** [comment]
We are facing this issue. Is this PR planned to be merged any time soon?

**Comment by ekarlso** [comment]
@tombuildsstuff Any idea on getting this in for a quick 2.8.0 or 2.7.1 ? It's a really sad issue.

**Comment by twendt** [comment]
I have just successfully tested this PR.

**Comment by sbkg0002** [comment]
It's not part of the 2.9 release, is it?

**Comment by aristosvo** [comment]
Nope. I'll rebase it to resolve the conflicts

**Comment by gitflo1** [comment]
Will this PR be part of the 2.10 release? This is really blocking us from updating our clusters...

**Comment by aristosvo** [comment]
I discussed it with the maintainers, if it doesn’t make it into 2.10.0 (May 14th) expect it for 2.11.0.

**Comment by atrauzzi** [comment]
Can we please have this in a patch release `2.9.1`, ASAP?  This bug is far too disruptive to sit on a fix for the regular release cycle.

**Comment by djsly** [comment]
this needs to be picked up ASAP :)  we will be reverting back to a custom local provider code, but we hate doing this... @aristosvo  any feedback on your PR from @tombuildsstuff  / @katbyte  yet ? I quickly reviewed , and it seems good.

**Comment by aristosvo** [comment]
@djsly this:
> if it doesn’t make it into 2.10.0 expect it for 2.11.0.

@katbyte has taken a look at the PR and told me she will discuss it internally with someone more familiar with AKS, probably @tombuildsstuff. One of the main reasons they are hesitant to merge AKS PRs at the moment is due to a lot of breaking API changes for AKS lately..

**Comment by djsly** [comment]
@aristosvo I understand, so many changes. but this not being merged is breaking the usage of terraform + aks

**Pull request merged**
