### PR TITLE
azurerm_monitor_action_group  - add support for the `use_common_alert_schema` webhook property

### PR DESCRIPTION
**Pull request by phires**
Updated Azure SDK API for insights to 2019-06-01 to be able to use the option 'UseCommonAlertSchema'

(fixs #3363)

### CODE REVIEW

**Comment by phires** [comment]
Build seems to fail, because travis does not know / import the updated dependency https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/monitor/mgmt/2019-06-01/insights
Any way for me to fix this?

**Comment by mbfrahry** [comment]
Hey @phires, dependencies are updated manually so you'll have to do this yourself. The below should do the trick
```
go get github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-06-01/insights
go mod tidy
go mod vendor 
```

**Comment by phires** [comment]
Fix is commited, anythint I can do to resolve the conflicts?

**Comment by colinuipath** [comment]
> Fix is commited, anythint I can do to resolve the conflicts?

You can merge the latest master to your branch to resolve these conflicts: https://stackoverflow.com/questions/26241428/this-pull-request-contains-merge-conflicts-that-must-be-resolved
Let me know if you need more help on this.

I am looking forward to seeing this feature in v1.36.0.

**Comment by phires** [comment]
Finally :) Thank you all, I'm learning something new every day!

**Comment by phires** [comment]
@katbyte Well, I guess I have to read up on all those "mod" stuff... 
I've added you as a collaborator to my repository, your help is highly appreciated :)

**Comment by colinuipath** [comment]
@phires Can you also add me as a collaborator to your repo? I will try to sort it out with the missing files.

**Pull request merged**
