### PR TITLE
`azurerm_mysql_server` `ssl_enforcement_enabled` update fail

### PR DESCRIPTION
**Pull request by yupwei68**
Fix: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7228

=== RUN   TestAccAzureRMMySQLServer_createReplica
=== PAUSE TestAccAzureRMMySQLServer_createReplica
=== CONT  TestAccAzureRMMySQLServer_createReplica
--- PASS: TestAccAzureRMMySQLServer_createReplica (807.43s)
=== RUN   TestAccAzureRMMySQLServer_basicFiveSix
=== PAUSE TestAccAzureRMMySQLServer_basicFiveSix
=== CONT  TestAccAzureRMMySQLServer_basicFiveSix
--- PASS: TestAccAzureRMMySQLServer_basicFiveSix (165.97s)
=== RUN   TestAccAzureRMMySQLServer_basicFiveSixDeprecated
=== PAUSE TestAccAzureRMMySQLServer_basicFiveSixDeprecated
=== CONT  TestAccAzureRMMySQLServer_basicFiveSixDeprecated
--- PASS: TestAccAzureRMMySQLServer_basicFiveSixDeprecated (165.41s)
=== RUN   TestAccAzureRMMySQLServer_basicFiveSeven
=== PAUSE TestAccAzureRMMySQLServer_basicFiveSeven
=== CONT  TestAccAzureRMMySQLServer_basicFiveSeven
--- PASS: TestAccAzureRMMySQLServer_basicFiveSeven (319.59s)
=== RUN   TestAccAzureRMMySQLServer_basicEightZero
=== PAUSE TestAccAzureRMMySQLServer_basicEightZero
=== CONT  TestAccAzureRMMySQLServer_basicEightZero
--- PASS: TestAccAzureRMMySQLServer_basicEightZero (227.11s)
=== RUN   TestAccAzureRMMySQLServer_autogrowOnly
=== PAUSE TestAccAzureRMMySQLServer_autogrowOnly
=== CONT  TestAccAzureRMMySQLServer_autogrowOnly
--- PASS: TestAccAzureRMMySQLServer_autogrowOnly (252.00s)
=== RUN   TestAccAzureRMMySQLServer_requiresImport
=== PAUSE TestAccAzureRMMySQLServer_requiresImport
=== CONT  TestAccAzureRMMySQLServer_requiresImport
--- PASS: TestAccAzureRMMySQLServer_requiresImport (238.74s)
=== RUN   TestAccAzureRMMySQLServer_complete
=== PAUSE TestAccAzureRMMySQLServer_complete
=== CONT  TestAccAzureRMMySQLServer_complete
--- PASS: TestAccAzureRMMySQLServer_complete (227.11s)
=== RUN   TestAccAzureRMMySQLServer_update
=== PAUSE TestAccAzureRMMySQLServer_update
=== CONT  TestAccAzureRMMySQLServer_update
--- PASS: TestAccAzureRMMySQLServer_update (345.75s)
=== RUN   TestAccAzureRMMySQLServer_completeDeprecatedMigrate
=== PAUSE TestAccAzureRMMySQLServer_completeDeprecatedMigrate
=== CONT  TestAccAzureRMMySQLServer_completeDeprecatedMigrate
--- PASS: TestAccAzureRMMySQLServer_completeDeprecatedMigrate (194.79s)
=== RUN   TestAccAzureRMMySQLServer_updateDeprecated
=== PAUSE TestAccAzureRMMySQLServer_updateDeprecated
=== CONT  TestAccAzureRMMySQLServer_updateDeprecated
--- PASS: TestAccAzureRMMySQLServer_updateDeprecated (224.12s)
=== RUN   TestAccAzureRMMySQLServer_updateSKU
=== PAUSE TestAccAzureRMMySQLServer_updateSKU
=== CONT  TestAccAzureRMMySQLServer_updateSKU
--- PASS: TestAccAzureRMMySQLServer_updateSKU (317.73s)
=== RUN   TestAccAzureRMMySQLServer_createPointInTimeRestore
=== PAUSE TestAccAzureRMMySQLServer_createPointInTimeRestore
=== CONT  TestAccAzureRMMySQLServer_createPointInTimeRestore
--- PASS: TestAccAzureRMMySQLServer_createPointInTimeRestore (1449.75s)

### CODE REVIEW

**Comment by yupwei68** [comment]
Hi @katbyte , thanks for your comments. 
The customer issue is caused by once the `ssl_enforcement` = `Disabled`, we can't update this field to enabled. 
There are two fields (`ssl_enforcement_enabled` and `ssl_enforcement`,`ssl_enforcement` is to be deprecated). In update function, if we have updated `ssl_enforcement` to `enabled` , d.Get("ssl_enforcement_enabled") = false, because in tf state, its value is false. It'll always be covered by its previous state value.
This PR is to fix this problem.

**Comment by yupwei68** [comment]
I have merged the conflicts. I have changed this back, because I assume when `ssl_enforcement_enabled` is absent, d.Get("ssl_enforcement_enabled") will get false, ssl will be disabled. But by default, it should be enabled:

```
ssl := mysql.SslEnforcementEnumEnabled
if v := d.Get("ssl_enforcement_enabled").(bool); !v {
		ssl = mysql.SslEnforcementEnumDisabled
}
```

**Comment by yupwei68** [comment]
Thanks for your comments. I think it's fixed by tom's PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/6809. I'll close this PR.

**Comment by yupwei68** [comment]
Sorry that I find that there is another problem with the issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/7228.

Tests have passed:
=== RUN   TestAccAzureRMMySQLServer_basicFiveSix
=== PAUSE TestAccAzureRMMySQLServer_basicFiveSix
=== CONT  TestAccAzureRMMySQLServer_basicFiveSix
--- PASS: TestAccAzureRMMySQLServer_basicFiveSix (177.01s)
=== RUN   TestAccAzureRMMySQLServer_basicFiveSixDeprecated
=== PAUSE TestAccAzureRMMySQLServer_basicFiveSixDeprecated
=== CONT  TestAccAzureRMMySQLServer_basicFiveSixDeprecated
--- PASS: TestAccAzureRMMySQLServer_basicFiveSixDeprecated (173.28s)
=== RUN   TestAccAzureRMMySQLServer_basicFiveSeven
=== PAUSE TestAccAzureRMMySQLServer_basicFiveSeven
=== CONT  TestAccAzureRMMySQLServer_basicFiveSeven
--- PASS: TestAccAzureRMMySQLServer_basicFiveSeven (237.26s)
=== RUN   TestAccAzureRMMySQLServer_basicEightZero
=== PAUSE TestAccAzureRMMySQLServer_basicEightZero



=== CONT  TestAccAzureRMMySQLServer_basicEightZero
--- PASS: TestAccAzureRMMySQLServer_basicEightZero (232.91s)
=== RUN   TestAccAzureRMMySQLServer_autogrowOnly
=== PAUSE TestAccAzureRMMySQLServer_autogrowOnly
=== CONT  TestAccAzureRMMySQLServer_autogrowOnly
--- PASS: TestAccAzureRMMySQLServer_autogrowOnly (300.61s)
=== RUN   TestAccAzureRMMySQLServer_requiresImport
=== PAUSE TestAccAzureRMMySQLServer_requiresImport
=== CONT  TestAccAzureRMMySQLServer_requiresImport
--- PASS: TestAccAzureRMMySQLServer_requiresImport (290.18s)
=== RUN   TestAccAzureRMMySQLServer_complete
=== PAUSE TestAccAzureRMMySQLServer_complete
=== CONT  TestAccAzureRMMySQLServer_complete
--- PASS: TestAccAzureRMMySQLServer_complete (300.80s)
=== RUN   TestAccAzureRMMySQLServer_update
=== PAUSE TestAccAzureRMMySQLServer_update
=== CONT  TestAccAzureRMMySQLServer_update
--- PASS: TestAccAzureRMMySQLServer_update (964.43s)
=== RUN   TestAccAzureRMMySQLServer_completeDeprecatedMigrate
=== PAUSE TestAccAzureRMMySQLServer_completeDeprecatedMigrate
=== CONT  TestAccAzureRMMySQLServer_completeDeprecatedMigrate
--- PASS: TestAccAzureRMMySQLServer_completeDeprecatedMigrate (276.24s)
=== RUN   TestAccAzureRMMySQLServer_updateDeprecated
=== PAUSE TestAccAzureRMMySQLServer_updateDeprecated
=== CONT  TestAccAzureRMMySQLServer_updateDeprecated
--- PASS: TestAccAzureRMMySQLServer_updateDeprecated (241.84s)
=== RUN   TestAccAzureRMMySQLServer_updateSKU
=== PAUSE TestAccAzureRMMySQLServer_updateSKU
=== CONT  TestAccAzureRMMySQLServer_updateSKU
--- PASS: TestAccAzureRMMySQLServer_updateSKU (335.69s)
=== RUN   TestAccAzureRMMySQLServer_createReplica
=== PAUSE TestAccAzureRMMySQLServer_createReplica
=== CONT  TestAccAzureRMMySQLServer_createReplica
--- PASS: TestAccAzureRMMySQLServer_createReplica (904.03s)
=== RUN   TestAccAzureRMMySQLServer_createPointInTimeRestore
=== PAUSE TestAccAzureRMMySQLServer_createPointInTimeRestore
=== CONT  TestAccAzureRMMySQLServer_createPointInTimeRestore
--- PASS: TestAccAzureRMMySQLServer_createPointInTimeRestore (1477.00s)

**Comment by yupwei68** [comment]
@jackofallops , Sorry that I miss a minor change need to be solved. I have reopened the PR and add some tests.

**Comment by yupwei68** [comment]
Hi @katbyte , would you mind continue reviewing this PR ?

**Comment by jackofallops** [comment]
Tests Passing:
image

**Pull request merged**
