### PR TITLE
New Log Analytics Sku for azurerm_log_analytics_workspace (#1078)

### LINKED ISSUE #1078: New Log Analytics Workspace Sku (PerGB2018)
### Terraform Version
0.11.5

### Affected Resource(s)
- azurerm_log_analytics_workspace

### Terraform Configuration Files
```hcl
resource "azurerm_log_analytics_workspace" "law-demo" {
  name                = "demo-workspace-${random_id.workspace.hex}"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.oms.name}"
  sku                 = "Free"
}
```

### Debug Output
https://gist.github.com/MattMencel/bc48429af5d1021756a9eb44f649d8c2

### Expected Behavior
Azure API accepts the Sku

### Actual Behavior
Azure API rejected the Skus currently documented in the API.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
On April 3rd, 2018 Microsoft changed the pricing tiers for Log Analytics.

https://azure.microsoft.com/en-us/blog/introducing-a-new-way-to-purchase-azure-monitoring-services/

I did some research and was able to find the new Sku name, `PerGB2018`.  This is not officially documented anywhere yet that I can find.  I successfully tested deployment using the new Sku.

I believe the old Skus will still work if you have an older Azure subscription and have deployed Log Analytics services prior to April 3, 2018.  I am unable to test this in my subscription.

### References
#1079

### PR DESCRIPTION
**Pull request by MattMencel**
Fixes #1078

### CODE REVIEW

**Comment by MattMencel** [comment]
Does this need to be updated as well to get Travis CI to pass?

https://github.com/Azure/azure-sdk-for-go/blob/master/services/operationalinsights/mgmt/2015-11-01-preview/operationalinsights/models.go

**Comment by tombuildsstuff** [comment]
👋  hey @MattMencel 

Thanks for this PR :)

As you've seen for us to add support for this this would need to be added to the Azure SDK for Go - which is in turn generated from [these Swagger files](https://github.com/Azure/azure-rest-api-specs) ([in this case the Enum value needs to be added here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2015-11-01-preview/OperationalInsights.json#L1277)), which will then trigger a PR to the Go SDK repository, which can then be released and vendored in.

In the interim it might make sense just to hard-code this value for the moment and add a `TODO`; once this is added to the Go SDK we'll switch it out for the constant/enum value from the SDK, which should allow us to ship this now (and then fix it later) - what do you think?

Taking a look at this PR - if we can revert the `CHANGELOG.md` file, which we edit manually once PR's are merged (given this repo's moves fairly quickly it helps to avoid merge conflicts) - but this otherwise looks pretty good 👍 If we can hard-code the Constant/Enum value for the moment and add an Acceptance Test ([example](https://github.com/MattMencel/terraform-provider-azurerm/blob/3748ae35d7cbd495308dab97885398eadd60a592/azurerm/resource_arm_log_analytics_workspace_test.go#L54) verifying this new behaviour we should be good to merge :)

Thanks!

**Comment by MattMencel** [comment]
Hi @tombuildsstuff

I added the new Sku as a PR to `azure-rest-api-specs`.  I also pulled my comments out of the changelog.

I'm not sure how to handle the Acceptance Test.  Just add a new `resource "azurerm_log_analytics_workspace" "test"` at the bottom with the new Sku?

**Comment by tombuildsstuff** [comment]
hey @MattMencel 

Sorry - I'd missed we'd not replied to this!

> I added the new Sku as a PR to azure-rest-api-specs. I also pulled my comments out of the changelog.

👍 cool thanks, it looks like that change hasn't made it into v15.2 of the Azure SDK for Go - but I'd assume this is available from v16 which should be out at the end of this/the start of next month; once it is we can upgrade to that and this PR should build & work as expected.

> I'm not sure how to handle the Acceptance Test. Just add a new...

Indeed, there's two parts to this: firstly [adding a method which returns the Terraform Configuration for the acceptance test](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_log_analytics_workspace_test.go#L147) - (in this case that'll be provisioning a Log Analytics Workspace with the new SKU) - once that's done we then need to create a Test which calls that configuration ([here's an example of that](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_log_analytics_workspace_test.go#L54)). At which point this test can be run using the following command:

```
TF_ACC=1 go test ./azurerm -v -timeout 120m -run=SomeTestNameToRun
```

(We'll also run the tests at this end, so as long as the config is present we should be good :)

Thanks!

**Comment by MattMencel** [comment]
I borked my rebase.  Sorry....

I'm going to try to clean this up....but if I can't figure it out I'll just delete the PR and try again.

**Comment by tombuildsstuff** [comment]
Just checked, this value isn't present in v16.2.1 of the Azure SDK for Go - I guess it'll be released with v17

**Comment by tombuildsstuff** [comment]
hey @MattMencel 

Sorry for the delay here, just to let you know that I've taken another look at the SDK and this is now available - as such I've rebased this PR and we can now merge it :)

Thanks!

**Comment by tombuildsstuff** [comment]
Tests pass:

```
$ acctests azurerm TestAccAzureRMLogAnalyticsWorkspace_

=== RUN   TestAccAzureRMLogAnalyticsWorkspace_importRequiredOnly
--- PASS: TestAccAzureRMLogAnalyticsWorkspace_importRequiredOnly (136.16s)
=== RUN   TestAccAzureRMLogAnalyticsWorkspace_importRetentionInDaysComplete
--- PASS: TestAccAzureRMLogAnalyticsWorkspace_importRetentionInDaysComplete (74.59s)
=== RUN   TestAccAzureRMLogAnalyticsWorkspace_requiredOnly
--- PASS: TestAccAzureRMLogAnalyticsWorkspace_requiredOnly (129.72s)
=== RUN   TestAccAzureRMLogAnalyticsWorkspace_retentionInDaysComplete
--- PASS: TestAccAzureRMLogAnalyticsWorkspace_retentionInDaysComplete (131.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	471.669s
```

**Pull request merged**
