### PR TITLE
New Resource: `azurerm_service_fabric_cluster`

### LINKED ISSUE #541: Feature Request: Service Fabric
_This issue was originally opened by @retheshnair as hashicorp/terraform#16604. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi there,

Terraform support for azure service fabric cluster missing 
### Terraform Version
[root@puppettest PUPPETPREPROD]# terraform -v
Terraform v0.10.7

Your version of Terraform is out of date! The latest version
is 0.10.8. You can update by downloading from www.terraform.io/downloads.html

### PR DESCRIPTION
**Pull request by lstolyarov**
Fixes #541

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hi @lstolyarov

Thanks for this PR :)

Firstly, apologies for the delay with this PR - it's been sat at the bottom of the PR Review list for far too long (which is totally my fault!).

In order to see how we could move forward with this, I spent a little time yesterday looking into what this would entail. I've amended your original commit (although your name's still on the commit) to remove the old SDK and the `config.go/provider.go` files (since these would cause merge conflicts), and then rebased this on top of master. Once that was done, I then took a look into what was needed to get this merged: I ended up altering the schema to better match the API/ARM Templates that I could find (in particular the `fabric_settings` and `node_type` blocks, since there can be multiple of each); and have since added some acceptance tests and documentation.

Whilst I appreciate this PR has been sitting here awkwardly for far too long - I hope you don't mind that I've made these changes and pushed them to your fork. This now LGTM (although I'm going to ask @katbyte to review it) - and I believe we should be able to get this shipped into the next release of the AzureRM Provider.

Thanks!

**Comment by tombuildsstuff** [comment]
Tests pass:

screenshot 2018-07-30 at 15 34 49

**Comment by lstolyarov** [comment]
Hey @tombuildsstuff, no problems at all. Nice to see this in terraform!

**Comment by pixelicous** [comment]
Is it possible to also update service fabric configuration using terraform now?
I specifically wonder would it work like ARM template, as for configuring certificates on the nodes you usally redeploy the ARM template..

**Comment by tombuildsstuff** [comment]
@pixelicous only the node count of a cluster can be changed via TF, due to limitations within the API - [please see the docs for more info](https://www.terraform.io/docs/providers/azurerm/r/service_fabric_cluster.html) 😄

**Comment by pixelicous** [comment]
@tombuildsstuff Only that? Damn, that makes this very unusable. We provide certificates to the nodes so that the applications can use it and authenticate with keyvault, today we are doing it with ARM template, isn't it working with API as well??
[Can find more details of what i mean here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management)

I read the documentation for this object on terraform docs, it seems the "properties" block is missing, this also is a problem because you cannot use the RBAC block and this forces users to use client certificates which is not a best practice, the RBAC block is created using Microsoft's AADTOOL and looks like this:
```
"azureActiveDirectory": { 
     "tenantId":"xxxxxx-xxxxx-xxxxx-xxxxxx-xxxxxx", 
     "clusterApplication":"xxxxxx-xxxx-xxxx-xxxxx-xxxxxx", 
     "clientApplication":"xxxxx-xxxx-xxxx-xxxx-xxxxxx" 
},
```
[Details can be found here under "Set up Azure Active Directory for client authentication"](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-arm)

**Pull request merged**
