### PR TITLE
streamanalytics version upgrade: 2016-03-01 -> 2020-03-01-preview

### PR DESCRIPTION
**Pull request by magodo**
This PR is to upgrade the API version from 2016-03-01 to 2017-04-01-preview for the streamanalytics. The main reason is that the feature requested by #12096 is introduced since 2017-04-01-preview.

### CODE REVIEW

**Comment by magodo** [comment]
image

**Comment by jackofallops** [comment]
Hi @magodo - The PR Title/Description and the version update in the change don't match, can you check which is correct and update accordingly? Thanks!

**Review by katbyte — APPROVED** [review]
Thanks @magodo - LGTM 🤖 updated title to the API you've actlally used.

**Comment by magodo** [comment]
@katbyte and @jackofallops Sorry for missing this comment. Though the package is named 2020-03-01, the API version used underlying is actually 2017-04-01-preview:

https://github.com/terraform-providers/terraform-provider-azurerm/pull/12133/files#diff-e1bf104cbb131fedf0daa1d03e6c6d507630d437c0c14e959fc95daa6412fc87R88

**Pull request merged**
