### PR TITLE
Update `azurerm_policy_remediation` - Support `resource_discovery_mode`

### LINKED ISSUE #6658: Support for ResourceDiscoveryMode in `azurerm_policy_remediation`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for ResourceDiscoveryMode option in `azurerm_policy_remediation`. Reference: https://github.com/Azure/azure-sdk-for-go/blob/master/services/policyinsights/mgmt/2019-10-01/policyinsights/models.go#L2056

### New or Affected Resource(s)

* azurerm_policy_remediation

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes #6658

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by tombuildsstuff** [comment]
@ArcturusZhang looks like the tests are failing here:

```
------- Stdout: -------
=== RUN   TestAccAzureRMPolicyRemediation_atSubscriptionWithDiscoveryMode
=== PAUSE TestAccAzureRMPolicyRemediation_atSubscriptionWithDiscoveryMode
=== CONT  TestAccAzureRMPolicyRemediation_atSubscriptionWithDiscoveryMode
TestAccAzureRMPolicyRemediation_atSubscriptionWithDiscoveryMode: testing.go:745: Error destroying resource! WARNING: Dangling resources
may exist. The full state and error is shown below.
Error: errors during apply: deleting Policy Remediation "acctestremediation-7tx3v" (Scope "/subscriptions/*******"): policyinsights.RemediationsClient#DeleteAtSubscription: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDeleteRemediationRequest" Message="The request to delete remediation 'acctestremediation-7tx3v' is invalid. The remediation must be in a terminal provisioning state (Succeeded, Canceled, Failed) before it can be deleted."
```

**Comment by ArcturusZhang** [comment]
Oops, I will take a look

**Comment by ArcturusZhang** [comment]
Temporarily close this since I could not resolve this test failure without the help from service team...

**Pull request closed without merging**
