### PR TITLE
upgrade to v30.0.0 Azure go sdk

### PR DESCRIPTION
**Pull request by r0bnet**
Need a feature from >=v30.0.0 for `analysisservicesserver` so i updated the version and fixed some incompatibilities.

### CODE REVIEW

**Comment by r0bnet** [comment]
That's fine. Let's get this merged :)

**Comment by r0bnet** [comment]
... accidentally closed this PR...

**Comment by katbyte** [comment]
no bother, tests pass and merging now!

**Comment by maxbog** [comment]
Hi, 

According to this comment: https://github.com/hashicorp/terraform/pull/18968#issuecomment-440744060 the verisons should be kept in sync with the https://github.com/hashicorp/go-azure-helpers and https://github.com/hashicorp/terraform repo. Is there a plan to upgrade the versions in the other two repos?

I created an issue in the go-azure-helpers repo, as the upgrade would fix a problem I have: https://github.com/hashicorp/go-azure-helpers/issues/29

**Pull request merged**
