### PR TITLE
add public network access to container registry

### PR DESCRIPTION
**Pull request by ms-henglu**
To address issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/7334

Below paste the run pass result for th test cases

```
=== RUN   TestAccContainerRegistry_update
=== PAUSE TestAccContainerRegistry_update
=== CONT  TestAccContainerRegistry_update
--- PASS: TestAccContainerRegistry_update (213.56s)
PASS

=== RUN   TestAccContainerRegistry_networkAccessProfileIp
=== PAUSE TestAccContainerRegistry_networkAccessProfileIp
=== CONT  TestAccContainerRegistry_networkAccessProfileIp
--- PASS: TestAccContainerRegistry_networkAccessProfileIp (161.77s)
PASS

=== RUN   TestAccContainerRegistry_geoReplication
=== PAUSE TestAccContainerRegistry_geoReplication
=== CONT  TestAccContainerRegistry_geoReplication
--- PASS: TestAccContainerRegistry_geoReplication (856.19s)
PASS

```

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
Thanks @ms-henglu - LGTM 👍

**Review by katbyte — CHANGES_REQUESTED** [review]
Looks like we have a test failure, could we fix it to make sure its not from the api upgrade:

```
------- Stdout: -------
=== RUN   TestAccContainerRegistry_geoReplication
=== PAUSE TestAccContainerRegistry_geoReplication
=== CONT  TestAccContainerRegistry_geoReplication
    testing.go:620: Step 1/5 error: Check failed: Check 4/5 error: azurerm_container_registry.test: Attribute 'georeplication_locations.0' expected "westeurope", got "eastus2"
--- FAIL: TestAccContainerRegistry_geoReplication (214.52s)
FAIL

------- Stderr: -------
2021/03/17 23:57:52 [DEBUG] not using binary driver name, it's no longer needed
2021/03/17 23:57:52 [DEBUG] not using binary driver name, it's no longer needed
```

**Comment by ms-henglu** [comment]
@katbyte Thanks for code review. I added a commit to fix the test. By the way, the test fails before API upgrade. Please review again. Thanks!

**Review by katbyte — APPROVED** [review]
Thanks @ms-henglu  - LGTM 👍

**Pull request merged**
