### PR TITLE
azurerm_recovery_services_vault: Support for `identity` block

### LINKED ISSUE #9619: Add identity MSI SystemAssigned to azurerm_recovery_services_vault
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Managed identity identity is required to enable private endpoint to ASR
Require also the identity to be exported.

### New or Affected Resource(s)

* azurerm_recovery_services_vault

### Potential Terraform Configuration

```hcl
resource "azurerm_recovery_services_vault" "vault" {
  name                = "example_recovery_vault"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "Standard"

 identity {
  type = "SystemAssigned"
 }
  soft_delete_enabled = true
}
```

### References

* #0000

### PR DESCRIPTION
**Pull request by favoretti**
Fixes #9619

### CODE REVIEW

**Comment by favoretti** [comment]
```
$ TF_ACC=1 go test -v ./azurerm/internal/services/recoveryservices/tests -timeout=1000m -run TestRecoveryServicesVault_basicWithIdentity
=== RUN   TestRecoveryServicesVault_basicWithIdentity
=== PAUSE TestRecoveryServicesVault_basicWithIdentity
=== CONT  TestRecoveryServicesVault_basicWithIdentity
--- PASS: TestRecoveryServicesVault_basicWithIdentity (90.38s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/recoveryservices/tests	91.530s
```

Unit tests failing seems to be not my doing?

**Comment by tombuildsstuff** [comment]
@favoretti apologies, that's related to a re-generation needing re-running (we're still working through hooking that up, so there's no GHA to catch that until it's all the way through)

**Review by katbyte — APPROVED** [review]
Thanks @favoretti - LGTM 👍

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2020-12-07 at 11 49 07

**Pull request merged**
