### PR TITLE
`azurerm_kubernetes_cluster_node_pool` - `node_count`, `min_node`, and `max_node` can now be set to `0`

### PR DESCRIPTION
**Pull request by zeroX-tj**
This updates the validation rules for the new Azure SDK where you can create zero size nodepools

#8219 

If there's anything else i should do, let me know, first PR. I tested it locally by using it.

### CODE REVIEW

**Comment by gdippolito** [comment]
I think this would be really nice to have. @zeroX-tj are you looking into addressing the comment?

**Comment by zeroX-tj** [comment]
> I think this would be really nice to have. @zeroX-tj are you looking into addressing the comment?

I'm really not so familiar with Go so i was planning in looking into it when i had more time. But that didn't happen yet.

**Review by gdippolito — APPROVED** [review]

**Review by gdippolito — APPROVED** [review]

**Comment by migolfi** [comment]
This looks great and it would be very helpful for some work I am currently on. Is there anything else needed on this? 
It looks like it's waiting for feedback from @mbfrahry

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @zeroX-tj. These changes look good and the test changes works! We are missing two things after further review. `max_count` validation should also start at 0 since it can be greater than or equal to `min_count` and we need to update the docs to reflect the changes here and we'll be good to go. https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/kubernetes_cluster_node_pool.html.markdown

**Comment by zeroX-tj** [comment]
Sorry for the reverts, was a bit confused by the failed builds but then i figured out it's because of cancelation :) Monday mornings 

I think everything should be good now.

**Review by mbfrahry — APPROVED** [review]
LGTM!

**Comment by mbfrahry** [comment]
Thanks for this @zeroX-tj!

**Pull request merged**
