### PR TITLE
New Resource: azurerm_sql_managed_instance (local branch for #2727)

### PR DESCRIPTION
**Pull request by katbyte**
As we don't have access to push to #2727 i have created a new PR so we can run tests.

### CODE REVIEW

**Comment by kim0** [comment]
Thanks @katbyte !! Is this still on track for merging in 1.30 ?

Also some nitpicks, I see some [options](https://docs.microsoft.com/en-us/cli/azure/sql/mi?view=azure-cli-latest#az-sql-mi-create) in the az cli, that don't seem supported (tier, public endpoint...etc). Nothing too important, but just thought to mention.

Really hope this resource lands the soonest, as I'm waiting for it

Thanks!

**Comment by kim0** [comment]
Hi @katbyte .. regarding your [comment](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2727#issuecomment-498818247) I was able to get it deploying correctly. Unfortunately Azure now seems to be forcing some painful policy that requires a large number of routing entries and NSG rules to be used. I was able to collect all of them into a sample[1] that works for me! 

@katbyte .. I had tested commit `6391188` and that still didn't have the property "fully_qualified_domain_name`, so hoping that one is a quick fix please.

[1]https://paste.ubuntu.com/p/pWy6fhw8TG/

**Comment by kim0** [comment]
@katbyte to be clear, and also that same commit wasn't able to `import` a managed instance deployed through the GUI. More details at #3587 

Also more details on the `fully_qualified_domain_name` issue at #3593

**Comment by tombuildsstuff** [comment]
Closing since this can be a branch we're using to run the tests rather than a PR - the work/discussion for this is continuing in #3587 but is blocked on 2.0.

**Comment by kim0** [comment]
@tombuildsstuff .. I guess you meant the discussion is continuing in #2727 instead of #3587 ?

**Pull request closed without merging**
