### PR TITLE
SQL Database Backup retention policies

### LINKED ISSUE #1802: Resources and Datasources for SQL Server Backups
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to use terraform to manage our sql server backups: https://docs.microsoft.com/en-us/rest/api/sql/backupshorttermretentionpolicies/createorupdate

### New or Affected Resource(s)

Should be resources and datasources for Backup Policies

### References

https://docs.microsoft.com/en-us/rest/api/sql/backupshorttermretentionpolicies/createorupdate

### PR DESCRIPTION
**Pull request by rlekni**
Adding support for Backup Short term and Long term retention policies to `mssql_database_resource`.

(fixes #1802)

### CODE REVIEW

**Comment by WackPenguin** [comment]
> Hi @WackPenguin,
> 
> thanks for the PR. I'm curious as to why you chose to add two new resources instead of adding these as properties on the existing database resources?

Hi @katbyte,

I figured, this is going to be more flexible in terms of resource creation. Rather than cramming everything in the database resource.

**Comment by WackPenguin** [comment]
Hi @katbyte,

While the backup configuration goes on sql server, we are still configuring the backups per database, therefore it made more sense to do resources per database. And as I mentioned in my previous response, I feel like due to different ways databases can be deployed, having these as separate resources gives more flexibility.

**Comment by katbyte** [comment]
@WackPenguin - i'm not sure i follow what additional flexibility this gives? could you elaborate on that? as it is a 1-1 relationship its much like the extended auditing policies & thread detection which are built into the db resources.

Separately this is using the v3.0 API, so could we place it into the mssql service package and name it as such? the sql * resources use the old api while the mssql resources use the new one (and i just migrated the last sql one over now)

**Comment by WackPenguin** [comment]
@katbyte the flexibility I have in mind is that, with this resources you are not forced to have either of sql_server or database resources managed in your terraform code. And even if they are managed, it would just be an additional resource. If you still think that it should ideally lie inside the mssql server resource or database one, I could move it.

**Comment by hobbesuk** [comment]
any update on when this'll be released?

**Comment by BartoszDopke** [comment]
Anyone knows where it will be released?

**Comment by rlekni** [comment]
> @katbyte the flexibility I have in mind is that, with this resources you are not forced to have either of sql_server or database resources managed in your terraform code. And even if they are managed, it would just be an additional resource. If you still think that it should ideally lie inside the mssql server resource or database one, I could move it.

Does this make sense? I have also moved these resource to mssql

**Comment by rlekni** [comment]
> Hi @rlekni - I've had a read over this and I'm in agreement with @katbyte, it doesn't make a lot of sense to have this as a separate resource. The 1:1 nature, and the complete dependency on the target database, means that this would be more appropriate as additional optional property blocks on the Database resource itself.
> 
> Could you update the implementation as such and one of us will review again?
> 
> Thanks!

@jackofallops Ok, Moved the retention policies to mssql db resource. Could you have a look at it.

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @rlekni - looks like all the tests are failing with panics now thou:

```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccAzureRMMsSqlDatabase_GP
=== PAUSE TestAccAzureRMMsSqlDatabase_GP
=== CONT  TestAccAzureRMMsSqlDatabase_GP

------- Stderr: -------
panic: runtime error: index out of range [0] with length 0

goroutine 518 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/mssql/helper.ExpandLongTermRetentionPolicy(0x8447b10, 0x0, 0x0, 0x424e300)
	/opt/teamcity-agent/work/a73be106926a7472/azurerm/internal/services/mssql/helper/sql_retention_policies.go:69 +0x56c
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/mssql.resourceArmMsSqlDatabaseCreateUpdate(0xc00013fc70, 0x43b2da0, 0xc001f6cb00, 0x0, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/azurerm/internal/services/mssql/mssql_database_resource.go:420 +0x17f0
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000720a20, 0xc000beda90, 0xc001ee8ec0, 0x43b2da0, 0xc001f6cb00, 0x43de201, 0xc00170e7e8, 0xc000918780)
	/var/lib/teamcity/go/1.14.5/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/resource.go:310 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000100e00, 0xc000df3a10, 0xc000beda90, 0xc001ee8ec0, 0xc00170a1a8, 0xc001119660, 0x43e10a0)
	/var/lib/teamcity/go/1.14.5/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc001f68850, 0x53b2520, 0xc000f86cf0, 0xc00013f7a0, 0xc001f68850, 0x0, 0xc001d89b78)
	/var/lib/teamcity/go/1.14.5/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/helper/plugin/grpc_provider.go:885 +0x8b4
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x47f8460, 0xc001f68850, 0x53b2520, 0xc000f86cf0, 0xc00004f980, 0x0, 0x53b2520, 0xc000f86cf0, 0xc001704580, 0x580)
	/var/lib/teamcity/go/1.14.5/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001621200, 0x53f3980, 0xc001621380, 0xc000115800, 0xc001845020, 0x840d760, 0x0, 0x0, 0x0)
	/var/lib/teamcity/go/1.14.5/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc001621200, 0x53f3980, 0xc001621380, 0xc000115800, 0x0)
	/var/lib/teamcity/go/1.14.5/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000ec59b0, 0xc001621200, 0x53f3980, 0xc001621380, 0xc000115800)
	/var/lib/teamcity/go/1.14.5/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/var/lib/teamcity/go/1.14.5/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
```

**Comment by katbyte** [comment]
Hi @rlekni - We are trying to fix this up to get it merged, but as we are unable yo push to you branch we've opened a new pr here #8765, so i amm going to close this one. Thanks for getting this started for us!

**Pull request closed without merging**
