### PR TITLE
`azurerm_container_registry`: support for  versionless encryption keys for ACR

### LINKED ISSUE #11774: ACR Encryption block doesn't allow for versionless keys
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The recently implemented encryption option for Azure Container Registry is currently forcing the user to provide a versioned key from Key Vault for the encryption. If you want to setup automatic key rotation you have to pass in a versionless id. This can be fixed by changing the schema to a NestedItemIdWithOptionalVersion.

### New or Affected Resource(s)

* azurerm_container_registry

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_key" "acr-key" {
  name         = "acr-key"
....
  ]
}

resource "azurerm_container_registry" "acr" {
...
  encryption {
    enabled            = true
    key_vault_key_id   = azurerm_key_vault_key.acr-key.versionless_id  
  }
}
```

### References

* #0000

### PR DESCRIPTION
**Pull request by tj-corrigan**
Closes #11774 

This allows for the use of versionless keys in ACR. I also included a small fix that allows for the upgrading of encryption keys.

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @tj-corrigan! This fix looks great but I do want to ask for two tests here. One for checking that a versionless key works and another to confirm that we can update encryption

**Comment by tj-corrigan** [comment]
@mbfrahry I went ahead and added a test that creates an encrypted ACR with a specific version and then updates it to use the versionless key. Tests works fine on my machine but it is failing to properly cleanup since the keyvault is required to have purge_protection turned on:

```Error: Error purging of Key "key-acr" (Key Vault "https://testkv210525173542901084.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=642777f6-b38a-4f1d-88b4-4d7fe42927de;oid=a7bd45ed-2bf6-4d3f-9604-2930fa4f7c94;iss=https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/' does not have keys purge permission on key vault 'testkv210525173542901084;location=eastus'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"ForbiddenByPolicy"}```

It looks like the tests for DiskEncryptionSet have the same issue but I'm not sure how the CI/CD tools handle that situation.

**Comment by mbfrahry** [comment]
Not a problem! That'll work for us! Thanks for taking the time to get that test added

**Review by mbfrahry — APPROVED** [review]
LGTM!

**Pull request merged**
