### PR TITLE
`azurerm_function_app` & `azurerm_function_app_slot` support for ip_restrictions field name, priority & action. Also added support for scm_ip_restriction field.  

### LINKED ISSUE #7431: `azurerm_function_app` & `azurerm_function_app_slot` support for ip-restrictions scm/kudu site
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for ip-restrictions scm/kudu site for function app & slot. 

### New or Affected Resource(s)

* azurerm_function_app
* azurerm_function_app_slot

### Potential Terraform Configuration

```hcl
  site_config {
   # Current network IP address restriction on function app
    ip_restriction {
      ip_address  = "1.2.3.4"
    }

   # Proposed new IP address restriction on function app SCM/KUDU site
    scm_ip_restriction {
      ip_address  = "5.6.7.8"
    }
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions

* Same as  #3685 but for function app

* #6955

### LINKED ISSUE #7446: `azurerm_function_app` & `azurerm_function_app_slot` support for name, priority & action
### Community Note

* Please vote on this issue by adding a 👍  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The fuction app could have the same IP restrictions as the App Service. Therefore it would be great to add support for name, priority & action for function app. This should also be done to the slot. 

### New or Affected Resource(s)
* azurerm_function_app
* azurerm_function_app_slot

### Potential Terraform Configuration
```hcl
ip_restriction = {
     ip_address = "1.2.3.0/24" # This exists today
     name = "foo" 
     priority = 101 
  }

ip_restriction = {
     ip_address = "1.2.3.4/32" # This exists today
     name = "bar"
     priority = 100 
     action = "Deny"
  }
]   
```
References
#6705 #6388 #6900

### PR DESCRIPTION
**Pull request by SebRosander**
Fixes #7446 
Fixes #7431

Same functionality as #6955 & #6705 & #6900 for app_service

### CODE REVIEW

**Comment by SebRosander** [comment]
Dunno why test aren't showing up. Last test passes: https://travis-ci.org/github/terraform-providers/terraform-provider-azurerm/builds/701288411

**Comment by traeddle** [comment]
is there a plan to merge this soon?

**Comment by espenekvang** [comment]
When will this be merged?

**Comment by jackofallops** [comment]
Hi @SebRosander 
As discussed offline: Since I missed this PR when I was working on #7945, and I believe the changes here have been fully covered by that. With this in mind I'm going to close this and if there's functionality I've missed, I'd be happy to review a new PR for anything missed, or if you'd prefer to call it out I can get it in.

My apologies for superseding your work, albeit accidentally, I hope it doesn't put you off contributing further in future.

Thanks!

**Pull request closed without merging**
