### PR TITLE
dependencies: updating `github.com/hashicorp/go-azure-helpers` to `v0.14.0`

### LINKED ISSUE #10292: Azure Cloud Shell Bash: Azure CLI authentication broken in azurerm v2.44.0
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4 (current release in Azure Cloud Shell)
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0

### Affected Resource(s)

* `provider "azurerm"`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}
```

### Debug Output

Unable to enable trace debug output in Azure Cloud Shell.

### Panic Output

N/A

### Expected Behaviour

Terraform plan should use Azure CLI authentication and complete with no errors.

### Actual Behaviour

Terraform plan results in the following error:

Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/f6d69ee2-34d5-4ca8-a143-7a2fc1aeca55/providers?api-version=2016-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":{"code":"bad_request_102","message":"Required metadata header not specified"}} Endpoint http://localhost:50342/oauth2/token?api-version=2017-09-01&resource=https%3A%2F%2Fmanagement.azure.com%2F

  on 10-common.tf line 1, in provider "azurerm":
   1: provider "azurerm" {

### Steps to Reproduce

1. Navigate to portal.azure.com and sign in
2. Open a new Bash Cloud Shell
3. Move to a directory that has any valid Terraform configuration using azurerm provider v2.44.0
4. `terraform init`
5. `terraform plan`
6. Observe error
7. Switch to azurerm provider v2.42.0
8. `terraform init`
9. `terraform plan`
10. Command completes and plan output is shown

### Important Factoids

This is only happening in Azure Cloud Shell bash. The same configuration works fine in Ubuntu client. This is a new problem I noticed when switching from azurerm v2.42 to azurerm v2.44.

### References

* [aka.ms/cloudshell](https://aka.ms/cloudshell)

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR updates the following dependencies:

* `github.com/hashicorp/go-azure-helpers` to `v0.14.0`
* `github.com/Azure/go-autorest/autorest` to `v0.11.18`

Which fixes support for running in Azure CloudShell - and explicitly opts out of the Managed Identities support within the Azure SDK for App Service, App Service Environment and Function Apps, since these are intentionally not supported

Fixes #10292

### CODE REVIEW

**Review by jackofallops — APPROVED** [review]
LGTM 👍

**Comment by sharebear** [comment]
@tombuildsstuff I saw this in the changelog... is it possible to get a little more detail on what is meant by the following

> and explicitly opts out of the Managed Identities support within the Azure SDK for App Service, App Service Environment and Function Apps, since these are intentionally not supported

We use MSI in our CI pipeline for managing `azurerm_app_service`, `azurerm_function_app` and `azurerm_app_service_plan` resources, will these be affected by this change?

With no links to the upstream issues it's a little difficult to understand the impact based upon just the diff here :)

**Comment by tombuildsstuff** [comment]
@sharebear 

> We use MSI in our CI pipeline for managing azurerm_app_service, azurerm_function_app and azurerm_app_service_plan resources, will these be affected by this change?

MSI itself is available in different environments (App Service/Function App, Containers, AKS, VM's etc) - what this is saying is the Azure Provider no longer supports being run inside of an App Service/Function App (since we never did, but this explicitly removes MSI as an option when running inside of an App Service/Function App, due to known issues) - your setup (from the sound of it using MSI within a VM/Container) is supported.

**Comment by sharebear** [comment]
@tombuildsstuff Thanks for the clarification. Sounds like I'm good for my current setup.

**Pull request merged**
