### PR TITLE
`azurerm_cdn_endpoint` - `delivery_rule` condition optional `match_values`

### LINKED ISSUE #8770: azurerm_cdn_endpoint request_uri_condition if "any" match_values still required
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.21
+ provider.azurerm v2.30.0
```

### Affected Resource(s)

* `azurerm_cdn_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_endpoint" "example" {
  name                = "example-${terraform.workspace}"
  resource_group_name = var.RESOURCE_GROUP.name
  location            = var.RESOURCE_GROUP.location
  profile_name        = azurerm_cdn_profile.iam-cdn-profile.name

  origin {
    name      = "example${terraform.workspace}"
    host_name = var.PLUGIN_JS_ENDPOINT
  }

  delivery_rule {
    name  = "SecurityHeaders"
    order = 1

    request_uri_condition {
      operator     = "Any"
      match_values = ["*"]
    }

    modify_response_header_action {
      action = "Append"
      name   = "X-Frame-Options"
      value  = "SAMEORIGIN"
    }
  }

  origin_host_header = var.PLUGIN_JS_ENDPOINT
}
```

### Expected Behavior

Expected TF to create new rule with request uri condition

### Actual Behavior

The following error occurs:
```
Error: Error waiting for the CDN Endpoint "example" (Profile "example-cdn-dev" / Resource Group "example") to finish updating: Code="BadRequest" Message="{\"ErrorMessage\":\"Invalid RulesEngineConfig: (Match value(s) must not be provided for Operator 'Any').\"}"

  on CDN\terraform.tf line 107, in resource "azurerm_cdn_endpoint" "example":
 107: resource "azurerm_cdn_endpoint" "example" {
```

### Comment

I tried to not using **match_values** or to set it to **null** but it is required by azurerm provider validation.

### PR DESCRIPTION
**Pull request by magodo**
When the `delivery_rule` condition operator is set to `Any`, we should
not pass any `match_values` at all.

Fixes #8770

### CODE REVIEW

**Review by jackofallops — COMMENTED** [review]
Hi @magodo 
Thanks for this PR. What does the API do if presented with a payload that doesn't use the `Any` operator and no `match_rules` are present? It feels remiss to trade one API error for another? If it does error, this should be addressed in code or documentation? WDYT?

**Comment by magodo** [comment]
@jackofallops You're right, I should have mentioned it in the document to make it clear. Whilst I think it is not necessarily to check in the code as it will fail in the API anyway, there is no too much benefit to fail a bit earlier just before sending the request.

**Comment by DeltaOffset** [comment]
Hello,

Is there a time when this will be implemented? we are having problems deploying our delivery_rule.
`  delivery_rule {
    name  = "BypassAllContent"
    order = 3

    cache_expiration_action {
      behavior = "BypassCache"
    }

    url_path_condition {
      match_values     = []
      negate_condition = false
      operator         = "Any"
      transforms       = []
    }
  }`

**Review by DeltaOffset — COMMENTED** [review]
Changing from Required to Optional setting for match_values when the operator is "Any" should be a valid fix for this scenario. IMHO

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @magodo 

Taking a look through whilst this seems ok, can we add some tests for this to confirm that these changes are sufficient?

Thanks!

**Comment by magodo** [comment]
@tombuildsstuff Thank you for reviewing! I have added a test to cover all the conditions which has match set to `Any`.

## Test Result

```bash
💤 make testacc TEST=./azurerm/internal/services/cdn/tests TESTARGS='-run TestAccAzureRMCdnEndpoint_deliveryRuleOptionalMatchValue'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test ./azurerm/internal/services/cdn/tests -v -run TestAccAzureRMCdnEndpoint_deliveryRuleOptionalMatchValue -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMCdnEndpoint_deliveryRuleOptionalMatchValue
=== PAUSE TestAccAzureRMCdnEndpoint_deliveryRuleOptionalMatchValue
=== CONT  TestAccAzureRMCdnEndpoint_deliveryRuleOptionalMatchValue
--- PASS: TestAccAzureRMCdnEndpoint_deliveryRuleOptionalMatchValue (445.78s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn/tests   445.901s
```

**Comment by DeltaOffset** [comment]
Guys Is this going to be merged soon? I Will like to import my cdn rules

**Comment by katbyte** [comment]
@magodo - could we fix the merge conflicts? once thats done i think this is good to merge

**Comment by magodo** [comment]
@katbyte I've resolved the conflicts, please take another look!

```bash
💤 make testacc TEST=./azurerm/internal/services/cdn TESTARGS='-run TestAccCdnEndpoint_deliveryRuleOptionalMatchValue'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test ./azurerm/internal/services/cdn -v -run TestAccCdnEndpoint_deliveryRuleOptionalMatchValue -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccCdnEndpoint_deliveryRuleOptionalMatchValue
=== PAUSE TestAccCdnEndpoint_deliveryRuleOptionalMatchValue
=== CONT  TestAccCdnEndpoint_deliveryRuleOptionalMatchValue
--- PASS: TestAccCdnEndpoint_deliveryRuleOptionalMatchValue (504.39s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn 504.426s
```

**Review by katbyte — APPROVED** [review]
Thanks @magodo - aside from the docs needed to be updated this LGTM 👍

**Pull request merged**
