### PR TITLE
WIP : Support for spot node pool

### LINKED ISSUE #6086: Support for spot node pool in azurerm_kubernetes_cluster
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Request to support for spot node pool in azurerm_kubernetes_cluster

Request to support for spot node pool in azurerm_kubernetes_cluster as per article in below
https://docs.microsoft.com/en-us/azure/aks/spot-node-pool

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### PR DESCRIPTION
**Pull request by rajalokan**
- Support for spot node pool in azurerm_kubernetes_cluster

Fixes #6086

### CODE REVIEW

**Comment by Starefossen** [comment]
We need this. Any way I can help moving this forward?

**Comment by Niteesh** [comment]
looking forward to use this. Any plans to make this available soon

**Comment by pbrit** [comment]
@tombuildsstuff and @rajalokan I added more thorough implementation. 
Should we close this one in favour of #7145?

**Comment by pbrit** [comment]
@Niteesh, @Starefossen 
Please have a look at #7145. The implementation was tested, it works for me. Please let me know if it doesn't for you.

**Comment by rajalokan** [comment]
Thanks a ton Paul. I will go ahead and close this PR.

**Pull request closed without merging**
