### PR TITLE
Add Orchestrator version for Kubernetes Cluster and Node Pool

### PR DESCRIPTION
**Pull request by titilambert**

### CODE REVIEW

**Comment by katbyte** [comment]
I beleive this will also fix #5541

**Comment by titilambert** [comment]
@katbyte tests and docs added

**Comment by djsly** [comment]
Are we all set with this PR @katbyte  ? thanks !

**Comment by djsly** [comment]
@katbyte @tombuildsstuff Friendly Bump

**Comment by djsly** [comment]
We just did an upgrade test using the provider locally compiled.

We saw that both he default Agent Pool and the Extra Agent Pool were updated during the AKS resource upgrade.

here's the output of terraform 
`module.cd4.module.aks.azurerm_kubernetes_cluster.aks: Modifying...`

and the proof that both agent pool are getting updated.
Note that the `win2` agent_pool is managed by
`mmodule.cd4.module.aks.azurerm_kubernetes_cluster_node_pool.agent_pools["win2"]` 

Screen Shot 2020-03-27 at 5 30 40 PM
Screen Shot 2020-03-27 at 5 30 32 PM

**Comment by djsly** [comment]
Ok I found one of the issue, there is bug in the PR I think... the control plane isn't getting updated due to this flag: `updateCluster`

https://github.com/titilambert/terraform-provider-azurerm/blob/86a8ccbca6f924cebb887647a1b65a63f8892cdd/azurerm/internal/services/containers/resource_arm_kubernetes_cluster.go#L781-L839

So even though we pass 1.15.10 as the orchestrator_version and the kubernetes_version, 
It looks like the clusterclient didn't run hence the control plane was not update to 1.15.10 but then a nodePoolClient issued an upgrade.

FYI, I'm with MSFT right now and my cluster is in a pretty nasty state.

**Comment by djsly** [comment]
Small update on my last message, MSFT have identify a bug that prevent the cluster upgrade to properly function.  They are working on patching my cluster and will push the fix to all DC after that... 
once I know more, I will provide more info here, but all that to say that I don't think that this PR is the cause of any issues AKS clusters upgrade are having at this time :)

**Comment by djsly** [comment]
@tombuildsstuff  / @titilambert  now that MSFT fixed their stuff, I tried another upgrade Ising this PR

we went from AKS 1.14.8 to 1.15.10

I get this error when the default node pool is trying to update

```
Error: Error updating Default Node Pool "prod1b-k8s" (Resource Group "prod1b-aks-rg"): containerservice.AgentPoolsClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedClusterAgentPoolProfileProperties.Count constraint=Null value=(*int32)(nil) details: value can not be null; required parameter
```

I think there might be an error with the order of execution.
https://github.com/titilambert/terraform-provider-azurerm/blob/86a8ccbca6f924cebb887647a1b65a63f8892cdd/azurerm/internal/services/containers/resource_arm_kubernetes_cluster.go#L781-L839

we do 
```
1) clusterClient.CreateOrUpdate (no version bump)
2) nodePoolsClient.CreateOrUpdate (updating the default agent pool with a new version that wasn't push to the control plane...)
3) clusterClient.CreateOrUpdate (with version bump)
```

I'm not sure why 1) and 3) are decoupled, but I think that the agentPool update should be last at a minimum. if there is a reason not to combine 3) into 1) ..

What do you guys think ?

**Comment by djsly** [comment]
@tombuildsstuff  just saw you guys merged many bug fixes with kubernetes, should I expect a second pass focusing on all of the node_pool PR ?

**Comment by djsly** [comment]
@tombuildsstuff  I have changed the order of execution for the upgrade since I'm getting this
```


Error: updating Default Node Pool "sly-k8s" (Resource Group "sly-aks-rg"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="AgentPoolMcVersionIncompatible" Message="Agentpool Version 1.15.10 is incompatible to managed cluster version 1.15.7. Detail: Patch version of agentPool version 10 is bigger than managedCluster version 7. For more information, please check https://aka.ms/version-skew-policy"
```

which make sense, the AgentPool version update needs to occur after the control plane version update.

**Comment by tombuildsstuff** [comment]
> @tombuildsstuff just saw you guys merged many bug fixes with kubernetes, should I expect a second pass focusing on all of the node_pool PR ?

hey - sorry thought I'd replied to this - yes, I'm taking a look at this today 👍

**Comment by titilambert** [comment]
Hello @tombuildsstuff any news about this ?

**Comment by twendt** [comment]
I have just tested this PR and it worked without any issues. I first created a new 1.15.7 cluster and then upgraded the control plane and default node pool to 1.16.7l in one go.

**Pull request closed without merging**
