### PR TITLE
Support app service HTTP blob logging

### PR DESCRIPTION
**Pull request by phekmat**
This PR is an extension of #3520 (and works toward #1082), adding blob support for the HTTP logs

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2019-09-06 at 12 20 43

**Comment by tombuildsstuff** [comment]
Accidentally hit close rather than comment, sorry 🤦‍♂

**Comment by sorenhansendk** [comment]
@phekmat Hi. I have just cloned your repository and builded the code as a Terraform plugin, so I could use this HTTP logs feature. But it don't working - i have added the following:

<pre>
logs {
  http_logs {
    azure_blob_storage {
      sas_url           = "https://[my-blob].blob.core.windows.net/testing?${data.external.logs_sas_token.result.token}"
      retention_in_days = 30
    }
  }
}
</pre>

But when I go to my portal on my new web app - the settings is:

image

**Comment by sorenhansendk** [comment]
@phekmat Thank you for the PR. I have tested it on the resource type `azurerm_app_service` today and it works fine. Will it be possible to add the same settings to the `azurerm_app_service_slot` resource type?

**Comment by phekmat** [comment]
@sorenhansendk I just created #4473 for that

**Pull request merged**
