### PR TITLE
dependencies: update azure-sdk-for-go to v47.1.0

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Now azure-sdk-for-go treats a package with at least one preview API as a preview package, therefore some packages have been moved to the preview directory (including cosmos-db/2020-04-01, policyinsights/2019-08-01 and servicefabric/2018-02-01). 
Also azure-sdk-for-go also treats a package without any preview APIs as a stable package, therefore some packages have moved out of the preview directory (including hdinsights/2018-06-01)

### CODE REVIEW

**Comment by benc-uk** [comment]
Hah, I was just putting PR together for this, I should have checked first 😝

**Comment by jackofallops** [comment]
Hi @ArcturusZhang - Looks like there's an older version of the `allowed-subcategories` crept into your PR that's erroring in travis.  If you can fix that up, we'll take a look at getting this reviewed and tested as soon as possible after the release of v2.32.0 scheduled for today.

**Comment by ArcturusZhang** [comment]
Seems I have missed the v2.32.0 release...

**Comment by ArcturusZhang** [comment]
Hi @jackofallops I am planning to directly update the SDK to v47.1.0 which would be released very soon. We have some work that depends on v47.1.0. I will update this PR once the new SDK is released, thanks

**Comment by jackofallops** [comment]
> Hi @jackofallops I am planning to directly update the SDK to v47.1.0 which would be released very soon. We have some work that depends on v47.1.0. I will update this PR once the new SDK is released, thanks

Hi @ArcturusZhang - We can hold off, not a problem.  Ideally we need a few full test suite runs against a new SDK version to check for regressions/issues, so depending on when you 47.1.0 is released and updated here, we may not be able to merge for the 2.33 release.

**Comment by ArcturusZhang** [comment]
Hi @jackofallops I just update the SDK to v47.1.0, please take a look, thanks!

**Comment by jackofallops** [comment]
Hi @ArcturusZhang - Looks like the error in the docs categories crept back in breaking the linter. 

I'll make time to review this later today and figure out which sets of tests we need to run for acceptance.

**Comment by ArcturusZhang** [comment]
@jackofallops awesome, thanks! Some of the packages are just renamed without changes, therefore I believe tests on those packages may be omitted.

**Comment by ArcturusZhang** [comment]
Hi @jackofallops any updates?

**Comment by tombuildsstuff** [comment]
hi @ArcturusZhang 

Unfortunately there's some other PR's which introduce new vendoring changes which need to go in before this PR - since this PR is too big to review in it's own right on Github, once those new vendor PR's have been merged we'll re-do this and diff this locally, then push it up. As such, whilst I'd like to thank you for this PR - I'm going to close this PR for the moment until the PR's containing other vendor changes have been merged, since these will introduce a merge conflict (and this is the easier of the PR's to regenerate).

Thanks!

**Pull request closed without merging**
