### PR TITLE
move tests: storage

### PR DESCRIPTION
**Pull request by katbyte**

### CODE REVIEW

**Review by jackofallops — APPROVED** [review]
LGTM 👍

**Comment by ArcturusZhang** [comment]
Hey @katbyte and @jackofallops actually I have done the tests migration for this RP a few days ago, but it was closed to avoid conflicts, could you also have a look? It is here: https://github.com/terraform-providers/terraform-provider-azurerm/pull/9741

**Comment by ArcturusZhang** [comment]
And I just rebased #9741 on the latest commit of origin/master

**Comment by ArcturusZhang** [comment]
It turns out that I cannot reopen a PR if the branch has been force pushed after it was closed. Therefore I opened a new PR for this: https://github.com/terraform-providers/terraform-provider-azurerm/pull/9864

**Comment by katbyte** [comment]
Hey @ArcturusZhang - we are breaking up moving the tests from refactoring the with the test shim to make the diffs easier to read & check. Going to merge this now so should be a simple matter to rebase on top of master

**Pull request merged**
