### PR TITLE
Support for `client_certificate_enabled`, `gateway_disabled`, `min_api_version` and `zones` in `azurerm_api_management`

### PR DESCRIPTION
**Pull request by yupwei68**
Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/8529
https://github.com/terraform-providers/terraform-provider-azurerm/issues/12126

### CODE REVIEW

**Comment by katbyte** [comment]
Could we fix the tests:
image

**Comment by yupwei68** [comment]
Hi kt, the acctests are fixed in https://github.com/terraform-providers/terraform-provider-azurerm/pull/12173

**Review by katbyte — APPROVED** [review]
Thanks @yupwei68 - LGTM 🍰

**Comment by walima0103** [comment]
Hi,

I'm getting this error using the provider v2.64.0: 

image

trying to deploy an Internal API Management in Zones:

```terraform
resource "azurerm_api_management" "wcdtapimtflabapim" {
  name                = "wcdtapimtflabapim"
  location            = azurerm_resource_group.wcdtapimtflabrg.location
  resource_group_name = azurerm_resource_group.wcdtapimtflabrg.name

  zones = [ "1", "2", "3" ]

  sku_name = "Premium_3"

  virtual_network_type = "Internal"

  virtual_network_configuration {
    subnet_id = azurerm_subnet.wcdtapimtflabvnetAPIMSubnet.id
  }

  identity {
    type = "SystemAssigned"
  }

  sign_up {
    enabled = true
    terms_of_service {
      consent_required = false
      enabled          = false
      text             = "The Terms of Service which users are required to agree to in order to sign up"
    }
  }

  publisher_name  = "wcdtapimtflab"
  publisher_email = "pub@wcdtapimtflab.intra"

}
```

Apparently, the parameter "properties.publicIpAddressId" (https://docs.microsoft.com/en-us/rest/api/apimanagement/2021-01-01-preview/api-management-service/create-or-update) is not availlable in terraform provider.

image

**Comment by yupwei68** [comment]
Hi @walima0103 Thanks for your comment.

"publicIpAddressId" is a feature currently in preview. I'll get it implemented once it's GA.

**Pull request merged**
