### PR TITLE
Support in-place update of app service slots

### LINKED ISSUE #1335: Feature Request: Allow in-place update of App Service Slots
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Since https://github.com/Azure/azure-rest-api-specs/issues/1697 has been resolved, slots can update the `tags`, `https_only`, `enabled`, and `client_affinity_enabled` settings. This was resolved for app services and functions in #1125.

### New or Affected Resource(s)

* azurerm_app_service_slot

### PR DESCRIPTION
**Pull request by phekmat**
- Upgrade to 2018-02-01 of the App Service API
- Remove `ForceNew` on several slot attributes and update them in place

Fixes #1335

### CODE REVIEW

**Comment by katbyte** [comment]
One of the tests is failing:

```
------- Stdout: -------
=== RUN   TestAccAzureRMAppServiceSlot_clientAffinityEnabledUpdate
--- FAIL: TestAccAzureRMAppServiceSlot_clientAffinityEnabledUpdate (157.39s)
    testing.go:513: Step 1 error: Check failed: Check 2/2 error: azurerm_app_service_slot.test: Attribute 'client_affinity_enabled' expected "false", got "true"
FAIL
```

**Comment by phekmat** [comment]
@katbyte I pushed a fix for that (roughly the same as the one added in 61a10693)

**Comment by katbyte** [comment]
@phekmat,

there are two of the older tests still failing with the same error:
```
------- Stdout: -------
=== RUN   TestAccAzureRMAppServiceSlot_manyIpRestrictions
--- FAIL: TestAccAzureRMAppServiceSlot_manyIpRestrictions (108.74s)
    testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:
        
        * azurerm_app_service_slot.test: 1 error(s) occurred:
        
        * azurerm_app_service_slot.test: web.AppsClient#CreateOrUpdateSlot: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="IpSecurityRestriction.IpAddress is invalid." Details=[{"Message":"IpSecurityRestriction.IpAddress is invalid."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51012","Message":"IpSecurityRestriction.IpAddress is invalid.","MessageTemplate":"{0} is invalid.","Parameters":["IpSecurityRestriction.IpAddress"]}}]
FAIL

------- Stdout: -------
=== RUN   TestAccAzureRMAppServiceSlot_oneIpRestriction
--- FAIL: TestAccAzureRMAppServiceSlot_oneIpRestriction (104.85s)
    testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:
        
        * azurerm_app_service_slot.test: 1 error(s) occurred:
        
        * azurerm_app_service_slot.test: web.AppsClient#CreateOrUpdateSlot: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="IpSecurityRestriction.IpAddress is invalid." Details=[{"Message":"IpSecurityRestriction.IpAddress is invalid."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51012","Message":"IpSecurityRestriction.IpAddress is invalid.","MessageTemplate":"{0} is invalid.","Parameters":["IpSecurityRestriction.IpAddress"]}}]
FAIL
```

These seem to be new and unique to your PR. Apologies for missing these earlier. I just tested the ones you had added at first.

**Comment by phekmat** [comment]
Thanks for that @katbyte. It looks like the same tests are failing for the regular `app_service` resource, so it's likely due to the new API version. 

I'll try to find some time to debug the issue.

**Comment by phekmat** [comment]
Minor update, it looks like the new version of the API has both removed the subnetMask field and requires that the IP address be in CIDR notation (x.x.x.x/y). I couldn't find any documentation of this new behavior, but it should be straightforward to work around it.

**Comment by tombuildsstuff** [comment]
@phekmat is updating App Service Slots dependent on the API upgrade? If not it may be worth removing that change for the moment?

**Comment by phekmat** [comment]
The API upgrade is required IIRC. The Swagger was updated for the old API for web apps in https://github.com/Azure/azure-rest-api-specs/pull/2664, but those fields are still there for slots. I believe I ran into the same issue as you did in https://github.com/Azure/azure-rest-api-specs/issues/1697

**Comment by phekmat** [comment]
I've rebased and added the IP/mask translation, so this should be good for review again. Apologies for the delay

**Comment by tombuildsstuff** [comment]
All the App Service related tests pass:

screenshot 2018-07-15 at 13 38 50

**Comment by tombuildsstuff** [comment]
hi @phekmat 

Just to let you know that is now available in [v1.10 of the AzureRM Provider(https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.10.0/CHANGELOG.md#1100-july-21-2018) - which you can update to this version by specifying it in the Provider block, like so:

```
provider "azurerm" {
  version = "=1.10.0"
}
```

Thanks!

**Pull request merged**
