### PR TITLE
azurerm_express_route_circuit - de-provision and re-provision circuit when changing bandwidth reduction (#3983)

### LINKED ISSUE #3983: Expressroute bandwidth reduction doesn't de-provision and re-provision circuit as would be expected
When changing bandwidth_in_mbps to a value less than the currently provisioned amount, Terraform should deprovisioned and reprovisioned the circuit.  Currently it will just try to directly change bandwidth_in_mbps and of course would fail, due to limitations described below.

https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-circuit-portal-resource-manager
"Although you can seamlessly upgrade the bandwidth, you cannot reduce the bandwidth of an ExpressRoute circuit without disruption. Downgrading bandwidth requires you to deprovision the ExpressRoute circuit and then reprovision a new ExpressRoute circuit."

### PR DESCRIPTION
**Pull request by pearcec**
Reduction in bandwidth forces new resource, utilizing CustomizeDiff

Fixes #3983

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@pearcec I hope you don't mind, but I'm going to rebase this on top of master to fix the merge conflicts

**Comment by pearcec** [comment]
> @pearcec I hope you don't mind, but I'm going to rebase this on top of master to fix the merge conflicts

Go for it.

**Comment by tombuildsstuff** [comment]
@pearcec I've run the tests for this a couple of times but they appear to fail with:

```
------- Stdout: -------
=== RUN   TestAccAzureRMExpressRouteCircuit/basic/bandwidthReduction
TestAccAzureRMExpressRouteCircuit/basic/bandwidthReduction: testing.go:640: Step 1 error: errors during apply:
Error: Error Retrieving ExpressRouteCircuit "acctest-erc-200507155656319668" (Resource Group "acctestRG-200507155656319668"): network.ExpressRouteCircuitsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/expressRouteCircuits/acctest-erc-200507155656319668' under resource group 'acctestRG-200507155656319668' was not found."
on /opt/teamcity-agent/temp/buildTmp/tf-test294814256/main.tf line 11:
(source code not available)
--- FAIL: TestAccAzureRMExpressRouteCircuit/basic/bandwidthReduction (307.12s)
```

so it looks like that something may need updating here?

**Comment by pearcec** [comment]
>
> (source code not available)
> --- FAIL: TestAccAzureRMExpressRouteCircuit/basic/bandwidthReduction (307.12s)
> ```
> 
> so it looks like that something may need updating here?

I will take a look.

**Comment by pearcec** [comment]
@tombuildsstuff  I am not having the same issue:

```
$ make acctests SERVICE=network TESTARGS='-run=TestAccAzureRMExpressRouteCircuit/basic/bandwidthReduction'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
TF_ACC=1 go test -v ./azurerm/internal/services/network/tests/ -run=TestAccAzureRMExpressRouteCircuit/basic/bandwidthReduction -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMExpressRouteCircuit
=== RUN   TestAccAzureRMExpressRouteCircuit/basic
=== RUN   TestAccAzureRMExpressRouteCircuit/basic/bandwidthReduction
--- PASS: TestAccAzureRMExpressRouteCircuit (295.51s)
    --- PASS: TestAccAzureRMExpressRouteCircuit/basic (295.51s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/basic/bandwidthReduction (295.50s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/tests       297.568s
$
```

I am building in East US.  Where are you building?  Can you run it with a trace and give me the log perhaps I can see something?  So are you just running that test or running them all?

**Comment by katbyte** [comment]
I ran it a few times and looks like it's azure being flakey

**Pull request merged**
