### PR TITLE
Fixes 5583. Add support for AKS SLB outbound type

### LINKED ISSUE #5583: Support for AKS outboundType
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS is enabling a feature to skip setup of standard load balancers (public IP, backend pools) in favor of the user setup with a custom UDR. The AKS feature is here and releasing early Feb:

https://github.com/Azure/AKS/issues/1384

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/resource_arm_kubernetes_cluster.go#L346-L468

### PR DESCRIPTION
**Pull request by baboune**
Fixes #5583 .

Upgrade to github.com/Azure/azure-sdk-for-go v39.1.0+incompatible
Add support for OutboundType in resource type: "azurerm_kubernetes_cluster"

```
resource "azurerm_kubernetes_cluster" "xxx" {
  network_profile {
    network_plugin = "azure"
    network_policy = "azure"
    outbound_type = "userDefinedRouting" # Or "loadBalancer"
   }
...

```
Added support for outbound_type in data_source_kubernetes_cluster.

### CODE REVIEW

**Comment by baboune** [comment]
I tried to fix the error for mod.sum by removing go.mod and go.sum from the PR but same result.  Wont touch anything until I get a signal.

**Comment by baboune** [comment]
Any chance we could move this forward? it is quite important for us.

**Comment by wagnst** [comment]
@baboune i guess resolving the conflicts might help...

**Comment by baboune** [comment]
@wagnst  Will do on Monday.

**Comment by baboune** [comment]
replaced by #6120

**Pull request closed without merging**
