### PR TITLE
In-place update of Cosmos DB geo_location

### LINKED ISSUE #3532: Adding an additional `geo_location` to an `azurerm_cosmosdb_account` should not require replacement
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.0
+ provider.azurerm v1.28.0
+ provider.random v2.1.2
```

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "rg123"
  location = "WestUS"
}

resource "random_integer" "ri" {
  min = 10000
  max = 99999
}

resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  kind                = "MongoDB"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  location            = "${azurerm_resource_group.rg.location}"
  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 10
    max_staleness_prefix    = 200
  }
  offer_type          = "Standard"
  enable_automatic_failover = true
  geo_location {
    location          = "WestUS"
    failover_priority = 0
  }
#  geo_location {
#    location          = "EastUS"
#    failover_priority = 1
#  }
}
```

### Expected Behavior

After deploying the code above, uncommenting the second `geo_location` and rerunning `apply` should have updated the existing CosmosDB database.

### Actual Behavior

Instead, it requires a replacement.

```
  # azurerm_cosmosdb_account.db must be replaced
-/+ resource "azurerm_cosmosdb_account" "db" {
      ~ connection_strings                = (sensitive value)
        enable_automatic_failover         = true
        enable_multiple_write_locations   = false
      ~ endpoint                          = "https://tfex-cosmos-db-95504.documents.azure.com:443/" -> (known after apply)
      ~ id                                = "/subscriptions/8bafcca2-660a-4459-a503-b785cf317a3a/resourceGroups/rg123/providers/Microsoft.DocumentDB/databaseAccounts/tfex-cosmos-db-95504" -> (known after apply)
        is_virtual_network_filter_enabled = false
        kind                              = "MongoDB"
        location                          = "westus"
        name                              = "tfex-cosmos-db-95504"
        offer_type                        = "Standard"
      ~ primary_master_key                = (sensitive value)
      ~ primary_readonly_master_key       = (sensitive value)
      ~ read_endpoints                    = [
          - "https://tfex-cosmos-db-95504-westus.documents.azure.com:443/",
        ] -> (known after apply)
        resource_group_name               = "rg123"
      ~ secondary_master_key              = (sensitive value)
      ~ secondary_readonly_master_key     = (sensitive value)
      ~ tags                              = {} -> (known after apply)
      ~ write_endpoints                   = [
          - "https://tfex-cosmos-db-95504-westus.documents.azure.com:443/",
        ] -> (known after apply)

        consistency_policy {
            consistency_level       = "BoundedStaleness"
            max_interval_in_seconds = 10
            max_staleness_prefix    = 200
        }

      - geo_location { # forces replacement
          - failover_priority = 0 -> null
          - id                = "tfex-cosmos-db-95504-westus" -> null
          - location          = "westus" -> null
        }
      + geo_location { # forces replacement
          + failover_priority = 0
          + id                = (known after apply)
          + location          = "westus"
        }
      + geo_location { # forces replacement
          + failover_priority = 1
          + id                = (known after apply)
          + location          = "eastus"
        }
    }
```

### Steps to Reproduce

1. `terraform apply`
2. Uncomment the second `geo_location`
3. `terraform apply` again

#### Notes

* Additional geo locations can be added to a CosmosDB account without downtime or replacement using the API or console.

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Fixes #3532 
Removes `ForceNew` from `location` property of `geo_location`

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
@katbyte Thanks for a quick response!

There are several tests that poke with locations and validate the result:
- TestAbcAzureRMCosmosDBAccount_updatePropertiesAndLocation
- TestAccAzureRMCosmosDBAccount_geoReplicated_add_remove
- TestAccAzureRMCosmosDBAccount_geoReplicated_rename
- TestAccAzureRMCosmosDBAccount_complete

Do you think that's not enough to prevent regression? If so, do you have a suggestion for scenarios of the extra test(s)?

**Comment by mikhailshilkov** [comment]
@katbyte I'm a bit confused here. My change is related to `geo_location` sub-resource, not the top-level `location` property.

The mentioned test does add the second `geo_location`. Here is the first configuration:
```
resource "azurerm_resource_group" "test" {
          name     = "acctestRG-190917093538081830"
          location = ""
        }

        resource "azurerm_cosmosdb_account" "test" {
          name                = "acctest-190917093538081830"
          location            = "${azurerm_resource_group.test.location}"
          resource_group_name = "${azurerm_resource_group.test.name}"
          offer_type          = "Standard"

          consistency_policy {
            consistency_level = "Session"


          }

          geo_location {
            location          = "${azurerm_resource_group.test.location}"
            failover_priority = 0
          }


        }
```

here is the second one:
```
resource "azurerm_resource_group" "test" {
          name     = "acctestRG-190917093538081830"
          location = ""
        }

        resource "azurerm_cosmosdb_account" "test" {
          name                = "acctest-190917093538081830"
          location            = "${azurerm_resource_group.test.location}"
          resource_group_name = "${azurerm_resource_group.test.name}"
          offer_type          = "Standard"

          consistency_policy {
            consistency_level = "BoundedStaleness"


                max_interval_in_seconds = 373
                max_staleness_prefix    = 100001

          }

          geo_location {
            location          = "${azurerm_resource_group.test.location}"
            failover_priority = 0
          }


                geo_location {
                    prefix            = "acctest-190917093538081830-custom-id"
                    location          = "westus"
                    failover_priority = 1
                }


        }
```

The doc doesn't mention that `geo_location` causes a replace either (while it does cause a replace in the current master).

**Comment by mikhailshilkov** [comment]
Hey @katbyte thank you for coming back and for your test suggestions
I added your test + a test with three locations and swapping the priorities of the last two. The first location's priority is hard-coded deep inside the chain, so I didn't dare to touch it. Please take a look.

**Comment by mikhailshilkov** [comment]
@katbyte Did you run all tests and only the two new ones failed? Or you only ran two?

Based on the error, it sounds like we didn't wait for the update operation to complete properly.

**Comment by mikhailshilkov** [comment]
Yes, I set up the infrastructure to test locally and can reproduce the failure.

In case of `TestAccAzureRMCosmosDBAccount_geoReplicated_changeLocation`, the update code runs two operation: scale down to 1 "old" region, then scale to two "new" regions. The second operation insta-succeeds while Cosmos is still in progress of actually updating. Subsequently, the delete operation fails.

Do you remember the reason why we have this 2-step account change with old locations and new locations? Should I try removing it? Or shall we adjust the readiness check to check the number of regions?

**Comment by katbyte** [comment]
@mikenomitch,

Honestly i don't recall, most likely it was because at the time the API didn't support a single step change. I would try removing it and seeing if it is smart enough now to figure it out (hence why i believe this property used to be force new, at the time it didn't work). the API has changed a fair amount in the last year and half.

**Comment by katbyte** [comment]
Hi @mikhailshilkov,

Are you still working on this? I am looking into finishing this up and am unable to push to your branch so would need to open a new PR.

**Comment by mikhailshilkov** [comment]
@katbyte I wasn't able to find the right combination to make this reliable, and then switched to something else... It would be awesome if you could do a better job.
I have "Allow edits from maintainers" on, let me know if I can grant you access in another way. Otherwise, a new PR should be fine.

**Comment by katbyte** [comment]
Still can't push to the branch, i'll see what i can do and open a new PR if when i'm ready i still can't.

**Comment by katbyte** [comment]
Hi @mikhailshilkov, 

I wasn't able to get this working reliably either and am going to move on to other PRs. As it appears it may not be possible to reliably do this i am going to close the PR until we can figure out a solution that works in all cases. Thanks again for trying!

**Pull request closed without merging**
