### PR TITLE
Corrected Prefix Length

### PR DESCRIPTION
**Pull request by johnwildes**
The maximum IP prefix length that can be reserved (according to docs.microsoft) is `/28` or 16 usable addresses.

https://docs.microsoft.com/en-us/azure/virtual-network/public-ip-address-prefix#constraints

### CODE REVIEW

**Comment by johnwildes** [comment]
@mbfrahry I updated the module, PR is here https://github.com/terraform-providers/terraform-provider-azurerm/pull/5693

**Comment by mbfrahry** [comment]
Thanks for that @johnwildes. Can we keep the changes to a single pr though? It helps us have a single point of reference when looking at how/why a change was made. Also rebasing with master should allow the travis tests to pass.

**Comment by johnwildes** [comment]
@mbfrahry I think I understand what you're saying.  I opened this PR for the documentation, and instead of updating the actual code in this PR as well, I opened a new PR.  I'll remember this for the future and just submit one.  I don't see a way to fix this from here.

**Comment by tombuildsstuff** [comment]
The travis failures are unrelated (and have since been fixed in master) - this LGTM 👍

**Pull request merged**
