### PR TITLE
Update BotService SDK to 2021-03-01

### PR DESCRIPTION
**Pull request by neil-yechenwei**
Update BotService SDK to [2021-03-01](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/botservice/resource-manager/Microsoft.BotService/stable/2021-03-01/botservice.json). Mainly in order to support new introduced properties and resources.

I've rerun the TCs to avoid regression issue. Below is the test result and it's same with the test result which doesn't involve this PR. So although there is failed tc in test result, but I think it isn't related with this PR.

Test Result:
=== RUN   TestAccBotChannelsRegistration
=== RUN   TestAccBotChannelsRegistration/connection
=== RUN   TestAccBotChannelsRegistration/connection/basic
testcase.go:96: Step 1/2 error: Error running apply: exit status 1
Error: creating Bot Connection "acctestBc210705125304326818" (Bot "acctestdf210705125304326818" / Resource Group "acctestRG-210705125304326818"): botservice.BotConnectionClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidBotData" Message="message: connection resource with id acctestBc210705125304326818 is not found"
with azurerm_bot_connection.test,
on terraform_plugin_test.tf line 28, in resource "azurerm_bot_connection" "test":
28: resource "azurerm_bot_connection" "test" {
=== RUN   TestAccBotChannelsRegistration/connection/complete
=== RUN   TestAccBotChannelsRegistration/channel
=== RUN   TestAccBotChannelsRegistration/channel/slackBasic
bot_channel_slack_resource_test.go:23: Skipping as one of `ARM_TEST_SLACK_CLIENT_ID`, `ARM_TEST_SLACK_CLIENT_SECRET`, or `ARM_TEST_SLACK_VERIFICATION_TOKEN` was not specified
=== RUN   TestAccBotChannelsRegistration/channel/slackUpdate
bot_channel_slack_resource_test.go:41: Skipping as one of `ARM_TEST_SLACK_CLIENT_ID`, `ARM_TEST_SLACK_CLIENT_SECRET`, or `ARM_TEST_SLACK_VERIFICATION_TOKEN` was not specified
=== RUN   TestAccBotChannelsRegistration/channel/msteamsBasic
=== RUN   TestAccBotChannelsRegistration/channel/msteamsUpdate
=== RUN   TestAccBotChannelsRegistration/channel/directlineBasic
=== RUN   TestAccBotChannelsRegistration/channel/directlineComplete
=== RUN   TestAccBotChannelsRegistration/channel/directlineUpdate
=== RUN   TestAccBotChannelsRegistration/web_app
=== RUN   TestAccBotChannelsRegistration/web_app/basic
=== RUN   TestAccBotChannelsRegistration/web_app/update
=== RUN   TestAccBotChannelsRegistration/web_app/complete
=== RUN   TestAccBotChannelsRegistration/basic
=== RUN   TestAccBotChannelsRegistration/basic/complete
=== RUN   TestAccBotChannelsRegistration/basic/basic
=== RUN   TestAccBotChannelsRegistration/basic/update
--- FAIL: TestAccBotChannelsRegistration (2047.16s)
--- FAIL: TestAccBotChannelsRegistration/connection (287.38s)
--- FAIL: TestAccBotChannelsRegistration/connection/basic (100.93s)
--- PASS: TestAccBotChannelsRegistration/connection/complete (186.44s)
--- PASS: TestAccBotChannelsRegistration/channel (874.32s)
--- SKIP: TestAccBotChannelsRegistration/channel/slackBasic (0.00s)
--- SKIP: TestAccBotChannelsRegistration/channel/slackUpdate (0.00s)
--- PASS: TestAccBotChannelsRegistration/channel/msteamsBasic (131.37s)
--- PASS: TestAccBotChannelsRegistration/channel/msteamsUpdate (239.36s)
--- PASS: TestAccBotChannelsRegistration/channel/directlineBasic (129.99s)
--- PASS: TestAccBotChannelsRegistration/channel/directlineComplete (130.58s)
--- PASS: TestAccBotChannelsRegistration/channel/directlineUpdate (243.03s)
--- PASS: TestAccBotChannelsRegistration/web_app (448.31s)
--- PASS: TestAccBotChannelsRegistration/web_app/basic (123.80s)
--- PASS: TestAccBotChannelsRegistration/web_app/update (172.08s)
--- PASS: TestAccBotChannelsRegistration/web_app/complete (152.42s)
--- PASS: TestAccBotChannelsRegistration/basic (437.15s)
--- PASS: TestAccBotChannelsRegistration/basic/complete (149.00s)
--- PASS: TestAccBotChannelsRegistration/basic/basic (123.37s)
--- PASS: TestAccBotChannelsRegistration/basic/update (164.78s)

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
thanks @neil-yechenwei - looks good aside from a test failure:
image

**Comment by neil-yechenwei** [comment]
@katbyte , this failure isn't caused by this PR. As you can see, this case already failed for a long time.

**Comment by neil-yechenwei** [comment]
@katbyte , After investigated, seems currently API would fail when the [`parameters`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/64d274a7aece31e7b6051071c50991a9287562ab/azurerm/internal/services/bot/bot_connection_resource.go#L86) is `[]`. After checked, seems currently this property is optional and it would be set as `[]` when it isn't specified in tfconfig. I assume we should use `d.GetOk()` for this optional property. So I iterated a [commit](https://github.com/terraform-providers/terraform-provider-azurerm/pull/12449/commits/4e11335f5e25ec168e69a4e6b545ce6d62b0969c) in this PR to fix this issue. Please have a look. Thanks.

After fixed, the related TCs can pass now.
--- PASS: TestAccBotChannelsRegistration/connection/basic (228.15s)
--- PASS: TestAccBotChannelsRegistration/connection/complete (326.39s)

**Comment by neil-yechenwei** [comment]
@katbyte , as [PR 12500](https://github.com/terraform-providers/terraform-provider-azurerm/pull/12500) has been merged, so I rerun the TCs on TeamCity and they all passed.
image

**Review by katbyte — APPROVED** [review]
Thanks @neil-yechenwei - LGTM 🙌

**Pull request merged**
