### PR TITLE
azurerm_app_service: Adding node language support

### PR DESCRIPTION
**Pull request by ghostinthewires**
This PR introduces the ability to support node.js in Azure App Service (requested in #2183)

### CODE REVIEW

**Comment by ghostinthewires** [comment]
Hey Tom,

I can't see it mentioned as being deprecated anywhere and it is still mentioned in recent Azure docs. You can also access it via azure cli, so it might be worth supporting until MS removed it.

Let me know if you still want it in & I will sort the tests out for App Service Slot.

Thanks

**Comment by ghostinthewires** [comment]
Hi Tom,

Do you have an update on direction for this one?

Thanks

**Comment by ghostinthewires** [comment]
Thanks for closing the other issue mate,, what did you want me to do with this one?

**Comment by tombuildsstuff** [comment]
hey @ghostinthewires 

Sorry for the delayed re-review here

Taking a look into this it appears this can be configured using the `linux_fx_version` parameter, for example using the following configuration:

```hcl
resource "azurerm_app_service" "main" {
  name                = "${var.prefix}-appservice"
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
  app_service_plan_id = "${azurerm_app_service_plan.main.id}"

  site_config {
    linux_fx_version = "NODE|10.14"
  }
}
```

produces an App Service with the following settings set:

screenshot 2019-02-28 at 12 00 52

As such, since I believe this can be achieved using the existing fields I'm going to close this PR in favour of a new one which adds an example of how to achieve this to the Examples folder. Whilst we're closing this PR I'd like to thank you for this contribution :)

Thanks!

**Comment by ghostinthewires** [comment]
Awesome, thanks for the feedback as always @tombuildsstuff

**Pull request closed without merging**
