### PR TITLE
Fixing deadlock in subnet resources

### LINKED ISSUE #2489: Can create 3 subnets with NSG and Route Table associations, but no more
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.10
+ provider.azurerm v1.19.0

### Affected Resource(s)

* azurerm_subnet
* azurerm_route_table
* azurerm_subnet_network_security_group_association
* azurerm_subnet_route_table_association

### Terraform Configuration Files

```hcl
provider "azurerm" {
  subscription_id = "${var.sub_id}"
  tenant_id       = "${var.tenant_id}"
  client_id       = "${var.tf_sp_appid}"
  client_secret   = "${var.tf_sp_secret}"
}

data "azurerm_resource_group" "vnet_rg" {
  name     = "${var.vnet_rg_name}"
}

data "azurerm_virtual_network" "existing_vnet" {
  name     = "${var.existing_vnet_name}"
  resource_group_name = "${var.vnet_rg_name}"
}

data "azurerm_network_security_group" "required_nsg" {
  name     = "${var.required_nsg_name}"
  resource_group_name = "${var.vnet_rg_name}"
}
# ##
resource "azurerm_subnet" "subnet0" {
  name                 = "${var.subnet_names[0]}"
  resource_group_name  = "${var.vnet_rg_name}"
  virtual_network_name = "${var.existing_vnet_name}"
  address_prefix       = "${var.subnet_prefixes[0]}"
  network_security_group_id = "${data.azurerm_network_security_group.required_nsg.id}"
  route_table_id       = "${azurerm_route_table.routetable0.id}"
}

resource "azurerm_route_table" "routetable0" {
  name     = "${var.existing_vnet_name}-${var.subnet_names[0]}-Routetable"
  location     = "${data.azurerm_resource_group.vnet_rg.location}"
  resource_group_name     = "${var.vnet_rg_name}"
  
  tags {
    environment = "${var.tag_environment_name}"
  }
}

resource "azurerm_subnet_network_security_group_association" "nsgassociation0" {
  subnet_id                 = "${azurerm_subnet.subnet0.id}"
  network_security_group_id = "${data.azurerm_network_security_group.required_nsg.id}"
}

resource "azurerm_subnet_route_table_association" "routetableassociation0" {
  subnet_id                 = "${azurerm_subnet.subnet0.id}"
  route_table_id = "${azurerm_route_table.routetable0.id}"
}
# ##
resource "azurerm_subnet" "subnet1" {
  name                 = "${var.subnet_names[1]}"
  resource_group_name  = "${var.vnet_rg_name}"
  virtual_network_name = "${var.existing_vnet_name}"
  address_prefix       = "${var.subnet_prefixes[1]}"
  network_security_group_id = "${data.azurerm_network_security_group.required_nsg.id}"
  route_table_id       = "${azurerm_route_table.routetable1.id}"
}

resource "azurerm_route_table" "routetable1" {
  name     = "${var.existing_vnet_name}-${var.subnet_names[1]}-Routetable"
  location     = "${data.azurerm_resource_group.vnet_rg.location}"
  resource_group_name     = "${var.vnet_rg_name}"
  
  tags {
    environment = "${var.tag_environment_name}"
  }
}

resource "azurerm_subnet_network_security_group_association" "nsgassociation1" {
  subnet_id                 = "${azurerm_subnet.subnet1.id}"
  network_security_group_id = "${data.azurerm_network_security_group.required_nsg.id}"
}

resource "azurerm_subnet_route_table_association" "routetableassociation1" {
  subnet_id                 = "${azurerm_subnet.subnet1.id}"
  route_table_id = "${azurerm_route_table.routetable1.id}"
}
# ##
resource "azurerm_subnet" "subnet2" {
  name                 = "${var.subnet_names[2]}"
  resource_group_name  = "${var.vnet_rg_name}"
  virtual_network_name = "${var.existing_vnet_name}"
  address_prefix       = "${var.subnet_prefixes[2]}"
  network_security_group_id = "${data.azurerm_network_security_group.required_nsg.id}"
  route_table_id       = "${azurerm_route_table.routetable2.id}"
}

resource "azurerm_route_table" "routetable2" {
  name     = "${var.existing_vnet_name}-${var.subnet_names[2]}-Routetable"
  location     = "${data.azurerm_resource_group.vnet_rg.location}"
  resource_group_name     = "${var.vnet_rg_name}"
  
  tags {
    environment = "${var.tag_environment_name}"
  }
}

resource "azurerm_subnet_network_security_group_association" "nsgassociation2" {
  subnet_id                 = "${azurerm_subnet.subnet2.id}"
  network_security_group_id = "${data.azurerm_network_security_group.required_nsg.id}"
}

resource "azurerm_subnet_route_table_association" "routetableassociation2" {
  subnet_id                 = "${azurerm_subnet.subnet2.id}"
  route_table_id = "${azurerm_route_table.routetable2.id}"
}
# ##
resource "azurerm_subnet" "subnet3" {
  name                 = "${var.subnet_names[3]}"
  resource_group_name  = "${var.vnet_rg_name}"
  virtual_network_name = "${var.existing_vnet_name}"
  address_prefix       = "${var.subnet_prefixes[3]}"
  network_security_group_id = "${data.azurerm_network_security_group.required_nsg.id}"
  route_table_id       = "${azurerm_route_table.routetable3.id}"
}

resource "azurerm_route_table" "routetable3" {
  name     = "${var.existing_vnet_name}-${var.subnet_names[3]}-Routetable"
  location     = "${data.azurerm_resource_group.vnet_rg.location}"
  resource_group_name     = "${var.vnet_rg_name}"
  
  tags {
    environment = "${var.tag_environment_name}"
  }
}

resource "azurerm_subnet_network_security_group_association" "nsgassociation3" {
  subnet_id                 = "${azurerm_subnet.subnet3.id}"
  network_security_group_id = "${data.azurerm_network_security_group.required_nsg.id}"
}

resource "azurerm_subnet_route_table_association" "routetableassociation3" {
  subnet_id                 = "${azurerm_subnet.subnet3.id}"
  route_table_id = "${azurerm_route_table.routetable3.id}"
}
```

### Debug Output

https://gist.github.com/ewierschke/075040ee240e8c51d0ddb63e1e0779ea

### Panic Output

No Panic

### Expected Behavior

All subnets should be created against existing VNET with appropriate association of a pre-created NSG and appropriate association of a newly created route table.

### Actual Behavior

Only 3 subnets are created and terraform gets stuck in ~infinite 'Still creating...' loop.  Terrform sees one of four subnets as still creating along with 3 route table associations and 2 NSG associations.
```
azurerm_subnet.subnet2: Still creating... (6m50s elapsed)
azurerm_subnet_route_table_association.routetableassociation0: Still creating... (6m40s elapsed)
azurerm_subnet_network_security_group_association.nsgassociation3: Still creating... (6m30s elapsed)
azurerm_subnet_route_table_association.routetableassociation3: Still creating... (6m30s elapsed)
azurerm_subnet_network_security_group_association.nsgassociation1: Still creating... (6m20s elapsed)
azurerm_subnet_route_table_association.routetableassociation1: Still creating... (6m20s elapsed)
azurerm_subnet.subnet2: Still creating... (7m0s elapsed)
azurerm_subnet_route_table_association.routetableassociation0: Still creating... (6m50s elapsed)
azurerm_subnet_route_table_association.routetableassociation3: Still creating... (6m40s elapsed)
azurerm_subnet_network_security_group_association.nsgassociation3: Still creating... (6m40s elapsed)
azurerm_subnet_route_table_association.routetableassociation1: Still creating... (6m30s elapsed)
azurerm_subnet_network_security_group_association.nsgassociation1: Still creating... (6m30s elapsed)
azurerm_subnet.subnet2: Still creating... (7m10s elapsed)
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Not sure how important, but in a larger deployment am trying to create 12+ subnets at once (what is provided is what I have been able to narrow it down to).  Was able to move the subnet and associations segment into a module and more than 3 subnets get created (~8 +/-) but still gets stuck in similar loop.

If this code is executed with the subnet3 resource and association resources commented out, the run succeeds (limiting to 3 new subnets to create).

subnet_names and subnet_prefixes are lists in my variables file.
```hcl
variable "subnet_names" {
  default = [
    "subnet0", 
    "subnet1", 
    "subnet2", 
    "subnet3", 
    "subnet4", 
    "subnet5", 
    "subnet6", 
    "subnet7", 
    "subnet8", 
    "subnet9", 
    "subnet10", 
    "subnet11", 
    "subnet12", 
    "subnet13"
    ]
}

variable "subnet_prefixes" {
  default = [
    "10.7.0.0/24", 
    "10.7.1.0/24", 
    "192.168.0.0/24", 
    "192.168.1.0/24", 
    "192.168.2.0/24", 
    "192.168.3.0/24", 
    "192.168.4.0/24", 
    "192.168.5.0/24", 
    "192.168.6.0/24", 
    "192.168.7.0/24", 
    "192.168.8.0/24", 
    "192.168.9.0/24", 
    "192.168.10.0/24", 
    "192.168.11.0/24"
    ]
}
```

The VNET already exists with 0 subnets and two address spaces.  
Two subnets in one address space and one in the other address space get successfully created.  
The NSG to associate is already pre-created that is to be associated with the new subnets.

I don't appear to be hitting API rate limits per the debug output.

If the above code is executed with `-parallelism=1` the apply succeeds.

Not sure what I might be  missing here or if maybe there is a limitation on the Microsoft.Network virtualNetworks API?

### References

* #0000

### PR DESCRIPTION
**Pull request by Moeser**
This is meant to fix #2489

### CODE REVIEW

**Comment by katbyte** [comment]
this is #3405 reopened

**Comment by Moeser** [comment]
> this is #3405 reopened

Yah, 3405 somehow got stuck in a blackhole.  This is my attempt at pulling it out of the event horizon and into view :)

**Comment by katbyte** [comment]
Hey @Moeser,

Sorry for the delay in reviewing both of these PR's - the main cause of the delay here is the complexity in testing it. These locks were introduced to work around a number of bugs in the Azure API's when using multiple resources in the same Networking stack at the same time (see [one of the previous bug reports](https://github.com/hashicorp/terraform/issues/7986) for [more information](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1286)).

As a part of this work we ended up doing a ton of testing in this area to confirm that the resources were locking only on the elements they needed (at least, at that time). Unfortunately we also learnt that the test framework we use doesn't properly account for these scenarios - and as such a bunch of this testing needs to be done manually.

Unfortunately our testing framework has issues catching this - and as such (when we did this last time) we noted that this involved a bunch of manual testing to confirm this worked (and didn't introduce any deadlock), which took a substantial amount of time.

We should likely add configurations to the example folder that trigger the various scenarios so we can more quickly check for them, but unfortunately we haven't had the time to do so yet. From our side the team are currently on other tasks in preparation for the 2.0 milestone - which means that unfortunately we've had to prioritise that work over testing this. Whilst I can appreciate it's frustrating that this has been delayed/without feedback - we're working to get to this as soon as we can - in the interim thank you for your patience (and humour)

**Comment by Moeser** [comment]
Thank you for the detailed and insightful response @katbyte !  It's good to know the context around why this is a complicated change to review.  I'll continue to wait patiently as you suggest :)

**Comment by tombuildsstuff** [comment]
@Moeser just to give an update here: after talking this through internally we're going to do some testing and then push this functionality out as the only feature in a bug release (v1.33.1) shortly following the next release (v1.33.0).

Doing it this way allows users to roll back to a previous version with the same functionality should this cause any dependency issues - which also means this isn't blocked until 2.0.

Apologies for the delay with these PR's - as @katbyte mentioned unfortunately there's a ton of manual testing here, but taking this approach should allow us the best of both world (confirming this works manually, and allowing users to roll back if there's any issues)

Thanks!

**Comment by Moeser** [comment]
@tombuildsstuff Sounds good to me, thanks for the update!

**Pull request merged**
