### PR TITLE
Upgrade ContainerServices 2017-09-30 to 2018-03-31

### PR DESCRIPTION
**Pull request by lfshr**
Upgraded azurerm containerservices from 2017-09-30 to 2018-03-31. 
This is an upgrade only and does not contain any new features introduced in 2018-03-31.

### CODE REVIEW

**Comment by lfshr** [comment]
@tombuildsstuff no problem. I'll probably take something very minor in the advanced networking stuff to work on if you guys are agreeable. Wanting to dip my toes in the water without taking too much on 😏

**Comment by tombuildsstuff** [comment]
@lfshr 

> I'll probably take something very minor in the advanced networking stuff to work on if you guys are agreeable. Wanting to dip my toes in the water without taking too much on 😏

Within AKS, or another resource? That's sounds good from our end 😄 - I'd suggest commenting on an existing issue to claim it/creating a new one for it if it doesn't exist (we can assign you to it too). One word of warning specifically for the Networking API's is that the older ones can have bugs in the API around resource deletion, but I'd suggest looking into it either way :)

**Comment by lfshr** [comment]
@tombuildsstuff for now I'm looking at AKS and Google Cloud Platform. EKS is on the cards as well. ATM this has been mostly driven by the business requirements of my current employer, but I'd be open to smaller tasks being assigned to me. I've literally just started working with GO on this PR so it really does have to be "dip your toes" level issues that I work on. (Also it's very very sunny in Scotland right now which never happens so my time is being spent sunning it up) 😆

**Comment by bergerx** [comment]
> This is an upgrade only and does not contain any new features introduced in 2018-03-31.

Is this correct? I'm seeing fields for many recent AKS  features are added in this patch ( https://github.com/terraform-providers/terraform-provider-azurerm/pull/1474/files#diff-2806273e153e90addd33508a3778e6ffR1198 ), so I guess after this is merged we'll be able to use those new features introduced when AKS went GA which were not available in 2017-09-30.

Or is there still some other steps to be taken before starting use those features?

**Comment by lfshr** [comment]
@bergerx that is correct. The only thing that has been upgraded is the vendor, so what you're seeing is Microsoft's new implementations. Further steps have to be taken to add these features into the Terraform provider itself.
You can find the source of the new vendor [here.](https://github.com/Azure/azure-sdk-for-go/tree/v17.4.0/services/containerservice/mgmt/2018-03-31/containerservice)

**Comment by lfshr** [comment]
@tombuildsstuff I can't merge this 😢

**Comment by tombuildsstuff** [comment]
@lfshr I'm running the tests atm, they detected one issue I'm pushing a fix for (turns out AKS uses the same CIDR block we did, that conflicts) - but it otherwise looks good so far :)

**Comment by tombuildsstuff** [comment]
Data Source tests pass, apart from a conflict with the AKS Subnet CIDR range which is fixed in https://github.com/terraform-providers/terraform-provider-azurerm/pull/1474/commits/b1d6a214ff0e3d43186af4ef338b56d647aa2e1a:

screenshot 2018-07-02 at 15 13 15

**Comment by tombuildsstuff** [comment]
ACS Tests pass:

screenshot 2018-07-02 at 15 14 33

**Comment by tombuildsstuff** [comment]
Resource tests pass (excl. the known test above fixed in commit https://github.com/terraform-providers/terraform-provider-azurerm/commit/b1d6a214ff0e3d43186af4ef338b56d647aa2e1a)

screenshot 2018-07-02 at 15 28 37

**Comment by tombuildsstuff** [comment]
@lfshr LGTM - thanks for this 👍

**Pull request merged**
