### PR TITLE
new resource: azurerm_kusto_eventgrid_data_connection

### PR DESCRIPTION
**Pull request by njuCZ**
once PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/8626 is merged, this PR is good to be reviewed

image

### CODE REVIEW

**Comment by jrauschenbusch** [comment]
Hi @njuCZ I ask myself, if all issues of https://github.com/terraform-providers/terraform-provider-azurerm/pull/5607/files are now solved?

Previous issues summarized:
- Acceptance tests were not possible for Event Grid data connections, as an existing target table as well as an ingestion mapping were necessary upfront (required parameters).
- The addition the creation of new terraform resources for the creation of Kusto tables and ingestion mappings were not possible, as management operations were not part of the control plane. Also there were no idempotent Kusto management operations available, but `create if not exists` constraints are required for both kinds to be implemented as terraform resources (CRUD). I tried to implement terraform resources for both kinds using some workarounds (`.show` commands), but the main problem was the authentication part, as it completely differs from the one used by `azure-sdk-for-go`. In addition i needed to use unsafe operations to allow queries to be build dynamically. (see https://github.com/terraform-providers/terraform-provider-azurerm/issues/6392 for the discussion)

**Comment by njuCZ** [comment]
@jrauschenbusch sorry for late reply and thanks for your message. It seems I did a duplicate work as PR #5607, I will contact the author and see how we could cooperate and push things forward.
About the data plane resource for kusto tables and ingestions, I have figured out how to use the authentication used by `azure-sdk-for-go`, I will share with you soon. But I don't know whether or not build the query dynamically is accpetable By Hashicorp reviewer since there is no independent CURD function in the data plane sdk

**Comment by njuCZ** [comment]
@jrauschenbusch you could refer to the authentication here: https://github.com/njuCZ/terraform-provider-azurerm/compare/master...njuCZ:kusto_table and see whether or not this resource could be merged.

**Comment by jrauschenbusch** [comment]
@njuCZ Thanks for your commitment for this topic.

> It seems I did a duplicate work as PR #5607, I will contact the author and see how we could cooperate and push things forward.

Yes, it's a duplicate. But there was no real progress within the first implementation, caused by the mentioned issues. So imho it wasn't that bad to bring this topic up again.

> About the data plane resource for kusto tables and ingestions, I have figured out how to use the authentication used by azure-sdk-for-go, I will share with you soon. 

Thanks for your efforts. I will dive into you code asap.

> But I don't know whether or not build the query dynamically is accpetable By Hashicorp reviewer since there is no independent CURD function in the data plane sdk

I don't know either whether they will accept a solution like this. Of course a real CRUD API for ingestion tables and mappings would be much better, but there isn't one. And I also think there won't be any in the next few months. To be honest, I don't think they'll ever provide such an API as [this ticket](https://github.com/Azure/azure-sdk-for-go/issues/7916) isn't getting that much attention either. Hence to make Kusto data connection resources usable from Terraform we need to search for other ways.

**Comment by CarlosSardo** [comment]
@njuCZ  Thanks for going forward with this New Resource: `azurerm_kusto_eventgrid_data_connection` and reference it back to the [closed one](https://github.com/terraform-providers/terraform-provider-azurerm/pull/5607). 

Would be great to have this new resource available. Thanks!

**Pull request closed without merging**
