### PR TITLE
new data source - `azurerm_consumption_budget`

### PR DESCRIPTION
**Pull request by gro1m**

### CODE REVIEW

**Comment by gro1m** [comment]
TEST SUMMARY:
```bash
=== RUN   TestAccDataSourceBudget_current
=== PAUSE TestAccDataSourceBudget_current
=== CONT  TestAccDataSourceBudget_current
--- PASS: TestAccDataSourceBudget_current (124.88s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/consumption 137.188s
```

**Comment by gro1m** [comment]
@marc-sensenich As you implemented the budget resource, I would like to ask if you could review this PR. Especially, I am asking myself if I could reuse this function: https://github.com/terraform-providers/terraform-provider-azurerm/pull/9201/files#diff-ad9eaf5260e152231bd9e02e61c4a688abec719d5e57638c6288efa6ec092464R15-R40. I defined "my own" read function, as I was missing a line setting the ID which I added in that function: https://github.com/terraform-providers/terraform-provider-azurerm/pull/12150/files#diff-028c6406d0f2efaaedf3ed340cbc530aa1a1fccd9f37b46031e7826e6813d0e7R154. Could you maybe resolve my confusion there?

**Comment by marc-sensenich** [comment]
@gro1m, I'll provide you with some historical context around #9201 and then how that can tie into this PR.

For the Consumption Budget resources, the design decision for multiple resources was based on @tombuildsstuff informing me of the issues that the maintainers have faced in the past of validating IDs for single resources that have multiple scopes and also allows for a better access control story; see this (thread in the contributors Slack for more details)[https://terraform-azure.slack.com/archives/CJD3VK9Q9/p1604659414205600] for more details. Therefore, when implementing the resource I abstracted as much of the shared CRUD resource logic into https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/consumption/consumption_budget_common.go. Then the implementations of the resources utilize that logic to create a simple implementation; e.g. https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/consumption/consumption_budget_subscription_resource.go.

For this PR specifically, I'd make a few recommendations based on the context I have, but the final calls would come from the maintainers
- Create a data source for each consumption budget scope to match the resources; e.g. `azurerm_consumption_budget_resource_group` and `azurerm_consumption_budget_subscription`. 
- You should be able to utilize https://github.com/terraform-providers/terraform-provider-azurerm/blob/25b076d578ebc4144357177b3a8e25699ead94c2/azurerm/internal/services/consumption/consumption_budget_common.go#L15 as is for reading and then set the ID outside of `resourceArmConsumptionBudgetRead` similar to https://github.com/terraform-providers/terraform-provider-azurerm/blob/25b076d578ebc4144357177b3a8e25699ead94c2/azurerm/internal/services/consumption/consumption_budget_resource_group_resource.go#L45. As this is the new pattern from what I've seen in recent implementations of data sources; e.g. https://github.com/terraform-providers/terraform-provider-azurerm/pull/12297/files#diff-0cb2af178b825dab362bea92448d9655fe5bf632292c2a2487d69413ea16a9ce.

**Comment by gro1m** [comment]
@tombuildsstuff, @katbyte: WDYT - should I split this into two datasources? Thanks for your feedback.

**Comment by jackofallops** [comment]
> @tombuildsstuff, @katbyte: WDYT - should I split this into two datasources? Thanks for your feedback.

Hi @gro1m - Given that there are discrete resources, with different ID structures this should also be two separate Data Source, this should also make it more clear to users when in use.

**Comment by gro1m** [comment]
Hi @jackofallops @marc-sensenich 
Ok, I will split into two data sources, then I can also reuse more of Marc's code and the changes would be smaller.

**Comment by katbyte** [comment]
@gro1m - is this superseded by #12538 and #12540?

**Comment by gro1m** [comment]
Hi @katbyte Yes it is. But would be great to keep it for reference until the others can be merged :)

**Comment by katbyte** [comment]
closing as its been superseded, it'll still be linked/available for reference afterwards :)

**Pull request closed without merging**
