### PR TITLE
resource/app_service: Add support for running Containers

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #580

Used the examples provided in #580 to get this working

Test results in the comments below thanks to @tombuildsstuff

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Tests pass:

screenshot 2018-07-15 at 23 24 06

**Comment by tombuildsstuff** [comment]
Tests pass after a rebase:

screenshot 2018-07-16 at 11 38 44

**Comment by jgmchan** [comment]
Hey folks, thanks for the great terraform provider! I've just given this new feature a test and I can't seem to get it to work properly.

As far as I understand, Web App for Containers only works on Linux but the App Service I end up with seems to be running Windows (I'm not entirely sure about this but I do get a `Console` option in the GUI, instead of an `SSH` option which is what I see when I provision it through the Azure console). I am also unable to download the logs to work out what is happening on the App Service that was provisioned.

I've created 2 App Services, 1 using the Terraform provider and another just through the Azure console and when I run `az webapp list`, the only meaningful difference I can see is that the `kind` value for the Azure console provisioned instance is set to `app,linux,container`, while the terraform provisioned instance is set to only `app`.

Here are both of them for reference:
Terraform provisioned instance
```
{
  "appServicePlanId":
    "/subscriptions/XXXXXXX/resourceGroups/test-rg/providers/Microsoft.Web/serverfarms/terraform-test-jeff",
  "availabilityState": "Normal",
  "clientAffinityEnabled": true,
  "clientCertEnabled": false,
  "cloningInfo": null,
  "containerSize": 0,
  "dailyMemoryTimeQuota": 0,
  "defaultHostName": "terraform-test-jeff.azurewebsites.net",
  "enabled": true,
  "enabledHostNames": [
    "terraform-test-jeff.azurewebsites.net",
    "terraform-test-jeff.scm.azurewebsites.net"
  ],
  "hostNameSslStates": [
    {
      "hostType": "Standard",
      "ipBasedSslResult": null,
      "ipBasedSslState": "NotConfigured",
      "name": "terraform-test-jeff.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "toUpdateIpBasedSsl": null,
      "virtualIp": null
    },
    {
      "hostType": "Repository",
      "ipBasedSslResult": null,
      "ipBasedSslState": "NotConfigured",
      "name": "terraform-test-jeff.scm.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "toUpdateIpBasedSsl": null,
      "virtualIp": null
    }
  ],
  "hostNames": ["terraform-test-jeff.azurewebsites.net"],
  "hostNamesDisabled": false,
  "hostingEnvironmentProfile": null,
  "httpsOnly": true,
  "id":
    "/subscriptions/XXXXXXX/resourceGroups/test-rg/providers/Microsoft.Web/sites/terraform-test-jeff",
  "identity": null,
  "isDefaultContainer": null,
  "kind": "app",
  "lastModifiedTimeUtc": "2018-07-19T06:24:24.673333",
  "location": "Australia Southeast",
  "maxNumberOfWorkers": null,
  "name": "terraform-test-jeff",
  "outboundIpAddresses":
    "52.255.35.249,52.255.39.26,52.255.38.183,52.255.37.221,52.255.32.203",
  "possibleOutboundIpAddresses":
    "52.255.35.249,52.255.39.26,52.255.38.183,52.255.37.221,52.255.32.203,52.255.39.71,52.255.33.39,52.255.42.223",
  "repositorySiteName": "terraform-test-jeff",
  "reserved": false,
  "resourceGroup": "test-rg",
  "scmSiteAlsoStopped": false,
  "siteConfig": null,
  "slotSwapStatus": null,
  "snapshotInfo": null,
  "state": "Running",
  "suspendedTill": null,
  "tags": {},
  "targetSwapSlot": null,
  "trafficManagerHostNames": null,
  "type": "Microsoft.Web/sites",
  "usageState": "Normal"
}
```

Azure Console provisioned instance
```
{
  "appServicePlanId":
    "/subscriptions/XXXXXXX/resourceGroups/test-rg/providers/Microsoft.Web/serverfarms/test-jeff",
  "availabilityState": "Normal",
  "clientAffinityEnabled": true,
  "clientCertEnabled": false,
  "cloningInfo": null,
  "containerSize": 0,
  "dailyMemoryTimeQuota": 0,
  "defaultHostName": "test-jeff.azurewebsites.net",
  "enabled": true,
  "enabledHostNames": [
    "test-jeff.azurewebsites.net",
    "test-jeff.scm.azurewebsites.net"
  ],
  "hostNameSslStates": [
    {
      "hostType": "Standard",
      "ipBasedSslResult": null,
      "ipBasedSslState": "NotConfigured",
      "name": "test-jeff.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "toUpdateIpBasedSsl": null,
      "virtualIp": null
    },
    {
      "hostType": "Repository",
      "ipBasedSslResult": null,
      "ipBasedSslState": "NotConfigured",
      "name": "test-jeff.scm.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "toUpdateIpBasedSsl": null,
      "virtualIp": null
    }
  ],
  "hostNames": ["test-jeff.azurewebsites.net"],
  "hostNamesDisabled": false,
  "hostingEnvironmentProfile": null,
  "httpsOnly": false,
  "id":
    "/subscriptions/XXXXXXX/resourceGroups/test-rg/providers/Microsoft.Web/sites/test-jeff",
  "identity": null,
  "isDefaultContainer": null,
  "kind": "app,linux,container",
  "lastModifiedTimeUtc": "2018-07-19T05:56:15.736666",
  "location": "West Europe",
  "maxNumberOfWorkers": null,
  "name": "test-jeff",
  "outboundIpAddresses":
    "52.178.92.96,51.144.224.93,52.232.70.142,52.232.4.132,52.232.64.246,52.169.1.210",
  "possibleOutboundIpAddresses":
    "52.178.92.96,51.144.224.93,52.232.70.142,52.232.4.132,52.232.64.246,52.169.1.210,51.145.159.13,52.136.236.15",
  "repositorySiteName": "test-jeff",
  "reserved": true,
  "resourceGroup": "test-rg",
  "scmSiteAlsoStopped": false,
  "siteConfig": null,
  "slotSwapStatus": null,
  "snapshotInfo": null,
  "state": "Running",
  "suspendedTill": null,
  "tags": {
    "hidden-related:/subscriptions/XXXXXXX/resourcegroups/test-rg/providers/Microsoft.Web/serverfarms/test-jeff":
      "empty"
  },
  "targetSwapSlot": null,
  "trafficManagerHostNames": null,
  "type": "Microsoft.Web/sites",
  "usageState": "Normal"
}
```

Is this something missing from the provider, or have I missed a configuration for `azurerm_app_service` somewhere? I can't seem to find anywhere in the docs where I can set the `kind` value.

**Comment by tombuildsstuff** [comment]
hi @jgmchan 

Linux App Services need to be running within a Reserved App Service Plan [as shown here](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html#example-usage-linux-) - can you take a look and see if that solves this issue for you?

Thanks!

**Comment by jgmchan** [comment]
Thanks for the quick response :)

I'll give it a quick test but I'm not sure this is reason because the service plan for the Azure console provisioned instance is not a reserved instance either:

Result from `az appservice plan list`
```
{
  "adminSiteName": null,
  "hostingEnvironmentProfile": null,
  "id":
    "/subscriptions/XXXXXXX/resourceGroups/test-rg/providers/Microsoft.Web/serverfarms/test-jeff",
  "isSpot": null,
  "kind": "linux",
  "location": "Australia Southeast",
  "maximumNumberOfWorkers": 10,
  "name": "test-jeff",
  "numberOfSites": 0,
  "perSiteScaling": null,
  "provisioningState": null,
  "reserved": null,
  "resourceGroup": "test-rg",
  "sku": {
    "capabilities": null,
    "capacity": 1,
    "family": "S",
    "locations": null,
    "name": "S1",
    "size": "S1",
    "skuCapacity": null,
    "tier": "Standard"
  },
  "spotExpirationTime": null,
  "status": "Ready",
  "tags": null,
  "targetWorkerCount": null,
  "targetWorkerSizeId": null,
  "type": "Microsoft.Web/serverfarms",
  "workerTierName": null
}
```

**Comment by jgmchan** [comment]
I just tested with the reserved instance set to true and it works! Thanks very much for that.

It is a little confusing that it doesn't show up when running `azure-cli` though and I think it may be nice to validate that the service plan is linux and reserved before allowing the `linux_fx_version` to be set.

Thanks very much for your help!

**Pull request merged**
