### PR TITLE
Add missing advanced filtering operators for Event Grid subscriptions

### LINKED ISSUE #12162: Support for missing advanced filtering operators for Event Grid subscriptions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Azure Event Grid filtering has some advanced filtering operators which aren't supported by the current event subscription resource e.g. StringNotContains, StringNotBeginsWith or StringNotEndsWith.
It would be great if those operators could be added.

### New or Affected Resource(s)

* azurerm_eventgrid_event_subscription

### Potential Terraform Configuration

```hcl
resource "azurerm_eventgrid_event_subscription" "example" {
  [...]
  advanced_filter {
    string_not_ends_with {
      key    = "subject"
      values = ["_thumb"]
    }
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/event-grid/event-filtering?WT.mc_id=Portal-Microsoft_Azure_EventGrid#operators

### PR DESCRIPTION
**Pull request by oraum**
Currently the azurerm_eventgrid_event_subscription does not implement all supported advanced filters from Event Grid subscriptions. 
This PR is intended to add the missing `NumberInRage`, `NumberNotInRange`, `StringNotBeginsWith`, `StringNotEndsWith`, `StringNotContains`, `IsNotNull` and `IsNullOrUndefined` filtering operators.

Fixes #12162

### CODE REVIEW

**Comment by manicminer** [comment]
Hi @oraum, thanks for this PR! I've pushed test and docs updates for the `azurerm_eventgrid_system_topic_event_subscription` resource. This mostly looks good, however I am getting a panic when running the acceptance test - could you take a look and I'll be happy to review further? Thanks!

```
=== RUN   TestAccEventGridEventSubscription_advancedFilter
=== PAUSE TestAccEventGridEventSubscription_advancedFilter
=== CONT  TestAccEventGridEventSubscription_advancedFilter
panic: interface conversion: interface {} is []interface {}, not [][]interface {}

goroutine 592 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid.expandAdvancedFilter(0x6bafb3c, 0x13, 0xc003163200, 0x8, 0x9, 0xc002552000, 0x8)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid/event_subscription.go:1032 +0x1a15
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid.expandEventGridEventSubscriptionFilter(0xc002c851f0, 0x7370908, 0xc002ac0330, 0xc002290300)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid/event_subscription.go:962 +0x512
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid.resourceEventGridEventSubscriptionCreateUpdate(0xc002c851f0, 0x6364260, 0xc003106380, 0x0, 0x0)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid/eventgrid_event_subscription_resource.go:177 +0x1dc
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0022acfa0, 0xc002528f00, 0xc0022851e0, 0x6364260, 0xc003106380, 0x6395301, 0xc00248f058, 0xc003044690)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:320 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0018dfd00, 0xc00278ba38, 0xc002528f00, 0xc0022851e0, 0xc0026e3288, 0xc003763440, 0x6398620)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000ec7ec0, 0x73291d0, 0xc001e55d40, 0xc00201a2a0, 0xc000ec7ec0, 0xc001e55d40, 0xc001adcba0)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:895 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x688a300, 0xc000ec7ec0, 0x73291d0, 0xc001e55d40, 0xc002350420, 0x0, 0x73291d0, 0xc001e55d40, 0xc00169d000, 0xeef)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001e82e00, 0x7372138, 0xc003439380, 0xc003710500, 0xc0032ad860, 0xa876ee0, 0x0, 0x0, 0x0)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc001e82e00, 0x7372138, 0xc003439380, 0xc003710500, 0x0)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001628230, 0xc001e82e00, 0x7372138, 0xc003439380, 0xc003710500)
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/tom/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:857 +0x1fd


Process finished with the exit code 1
```

**Comment by oraum** [comment]
Hi @manicminer, thanks for considering my PR! I'm facing some problems running the acceptance tests but nevertheless could reproduce and fix the panic. So you review the code now. Thanks!

**Review by manicminer — APPROVED** [review]
Hi @oraum, thanks for fixing that crash. I've taken a look over and ran the tests, and this LGTM. I had an issue where the API limit of 25 advanced filter values was hit by the test configs after adding the new fields, so I split it into two resources per test (also removing the individual value checks since those are caught by the import step). I also added a CustomizeDiff func to catch that at plan time. Awaiting final test results before merging.

**Comment by katbyte** [comment]
looks like there is still one last test failure:
```
------- Stdout: -------
=== RUN   TestAccEventGridSystemTopicEventSubscription_advancedFilter
=== PAUSE TestAccEventGridSystemTopicEventSubscription_advancedFilter
=== CONT  TestAccEventGridSystemTopicEventSubscription_advancedFilter
    testcase.go:89: Step 1/2 error: Check failed: Check 1/2 error: "azurerm_eventgrid_system_topic_event_subscription.test" was not found in the state
--- FAIL: TestAccEventGridSystemTopicEventSubscription_advancedFilter (181.19s)
FAIL
```

**Review by manicminer — APPROVED** [review]
Ah I missed that. All fixed, looks good to go

Screenshot 2021-07-01 at 13 32 52

**Pull request merged**
