### PR TITLE
`azurerm_key_vault` - persist change for `network_acls`  when allowing `AzureServices`

### LINKED ISSUE #2164: azurerm_key_vault - does not persist change for network_acls on terraform site and reapplies same change on every run
azurerm_key_vault - do not persist change for network_acls on terraform site and reapplies same change on every run 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.azurerm v1.17.0

### Affected Resource(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
# Configure the Azure Provider
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
  alias           = "default"
}

resource "azurerm_resource_group" "test_rg" {
  name     = "kvtest"
  location = "${var.azurerm_location}"
  provider = "azurerm.default"
}

resource "azurerm_virtual_network" "test_vnet" {
  name                = "test-vnet"
  address_space       = ["10.103.12.0/22"]
  location            = "${var.azurerm_location}"
  resource_group_name = "${azurerm_resource_group.test_rg.name}"
  provider            = "azurerm.default"
}

resource "azurerm_subnet" "test_subnet" {
  name                 = "test-subnet"
  address_prefix       = "10.103.14.0/24"
  virtual_network_name = "${azurerm_virtual_network.test_vnet.name}"
  resource_group_name  = "${azurerm_resource_group.test_rg.name}"
  provider             = "azurerm.default"
  #service_endpoints    = ["Microsoft.KeyVault"]
}

###############################################
# Key Vault
###############################################

resource "azurerm_key_vault" "test_kv" {
  name                = "test-raf-kv"
  location            = "${var.azurerm_location}"
  tenant_id           = "${var.tenant_id}"
  resource_group_name = "${azurerm_resource_group.test_rg.name}"
  provider            = "azurerm.default"

# ROLLBACK - NEVER PERSISTED - APPLIES ON EVERY RUN
  network_acls {
    default_action             = "Allow"
    bypass                     = "AzureServices"
  }

# RELEASE - WORKS FINE AFTER CHANGE TERRAFORM INDICATES 0 CHANGES ON EACH RUN
/*
  network_acls {
    default_action             = "Deny"
    bypass                     = "AzureServices"
    ip_rules                   = ["${var.ip_rules}"]
    virtual_network_subnet_ids = ["${azurerm_subnet.test_subnet.id}"]
  }
*/

lifecycle {
  prevent_destroy = true
}

  sku {
    name = "standard"
  }

  access_policy {
    tenant_id = "${var.tenant_id}"
    object_id = "<some object id>"

    certificate_permissions = [
      "list"
    ]

    key_permissions = [
      "list"
    ]

    secret_permissions = [
      "list"
    ]
  }

  enabled_for_disk_encryption     = true
  enabled_for_deployment          = true
  enabled_for_template_deployment = true
}

resource "azurerm_key_vault_key" "test_key" {
  name      = "generated-certificate"
  vault_uri = "${azurerm_key_vault.test_kv.vault_uri}"
  key_type  = "RSA"
  key_size  = 2048
  provider  = "azurerm.default"

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

```

### Debug Output

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_key_vault.test_kv
      network_acls.#:                "0" => "1"
      network_acls.0.bypass:         "" => "AzureServices"
      network_acls.0.default_action: "" => "Allow"

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_key_vault.test_kv: Modifying... (ID: /subscriptions/<MY SUSBSCRIPTION>../Microsoft.KeyVault/vaults/test-raf-kv)
  network_acls.#:                "0" => "1"
  network_acls.0.bypass:         "" => "AzureServices"
  network_acls.0.default_action: "" => "Allow"
azurerm_key_vault.test_kv: Modifications complete after 1s (ID: /subscriptions/<MY SUSBSCRIPTION>.../Microsoft.KeyVault/vaults/test-raf-kv)

### Expected Behavior

Once applied terraform should indicate that there will be 0 changes.

### Actual Behavior

 it applies this change et every run even tough its already reflected on azure site.

### Important Factoids

When I comment out network_acls { block the terraform stops reapplying it but it must be done after I run following at least once

  network_acls {
    default_action             = "Allow"
    bypass                     = "AzureServices"
  }

Ideally to remove all my network acl change I would like to simply comment out network_acls { but its currently not the case as terraform doesn't perform any change at that point.

### PR DESCRIPTION
**Pull request by richardzone**
This commit fix #2164. 

How to reproduce the bug:

1. `terraform apply` the following Terraform configuration:
  ```hcl
  resource "azurerm_key_vault" "test_kv" {
    name                = "test-kv"
    ...
  
    network_acls {
      default_action             = "Allow"
      bypass                     = "AzureServices"
    }
  }
  ```
2. Do a `terraform plan` with the same above configuration. It will incorrectly shows changes - Terraform trys to re-add the network_acls.

### CODE REVIEW

**Comment by richardzone** [comment]
@tombuildsstuff  Hi Tom, I wonder if you have some time to help review the PR?

**Comment by mbfrahry** [comment]
Hey @richardzone, this looks good at a glance but could you add tests so we can confirm that this works/will continue to work

**Comment by katbyte** [comment]
@richardzone,

It sounds like this is a bug in the API not returning the values? Would it make sense to open an issue on the SDK and link to it in a comment here explaining why this is required?

**Comment by tombuildsstuff** [comment]
hey @richardzone 

Thanks for this PR - apologies for the delayed review here!

After spending some time with this Pull Request and playing with the API to confirm the behaviour we believe it'd be better to return a default object matching the API behaviour for the `network_acls` block (e.g. defaulted to `Allow`, as the API behaves) - rather than omiting this from the diff. In order to achieve this we'd need to also make this block Computed - since this behaviour would be configured by default unless a user opted to change it.

As such whilst I'd like to thank you for this contribution - since these are fairly substantial changes, I hope you don't mind but I'm going to close this PR in favour of #5207 which implements this.

Thanks!

**Comment by richardzone** [comment]
No worries @tombuildsstuff , thanks for fixing this!

**Pull request closed without merging**
