### PR TITLE
Datasource for storage_table

### PR DESCRIPTION
**Pull request by srigi**
Hello,

in our company we need data source like this - store some values in Azure Table (under storage account) and read them via TF data source.

I finished working DS for this usecase with documentation & tests.

### CODE REVIEW

**Comment by srigi** [comment]
To any maintainer - I resolved all issues with tests, all are passing. Also I rebased to tag `v2.0.0`. Please give me feedback if anything else is needed to be done.

**Comment by magodo** [comment]
@srigi Thank you for this PR. I looked through it and it almost LGTM :+1: 

While there may be some design issues we need to address before we can move on. Taking AWS S3 Object as a reference, it splits in 2 DS(s):

1. [s3_bucket_object](https://www.terraform.io/docs/providers/aws/d/s3_bucket_object.html): access object contet via key
2. [s3_bucket_objects](https://www.terraform.io/docs/providers/aws/d/s3_bucket_objects.html): return a list of keys, used as input to **s3_bucket_object**

FWIW, the benefit of this design is, if we return either a value or a list of values, it can error if none/more then 1 is found. You can add some checks in terraform configuration, while that is something we shall avoid at the begining.

Hence, shall we split this data source into:

- **storage_table_entity**: access entity via `partition_key` and `row_key` (and we can just ignore the use case of querying via entity id)
- **storage_table_entities**: run the query and return a list of `(partition_key, row_key)` pairs, which can be used as input to **storage_table_entity**

**Comment by jackofallops** [comment]
Hi @srigi 
Just checking in to see if you are able to address the items @magodo highlighted of splitting this into the single and collection data sources? or if I should close this PR for now?

In addition to @magodo 's comments, we'd need this resource to be able to support environments other than just Azure Public, so we'd need to have the resource id URL built from the provider metadata, rather than hard coded to `.table.core.windows.net`.  (There's a `GetResourceId` helper function that should be useful there)

Lastly, there's been an update to the version of Giovanni in use since this was opened, so there's a merge conflict to resolve also.

Thanks!

**Comment by srigi** [comment]
Hi guys. I prepared this PR in the company which I don't work anymore. I hoped that they push things forward regarding this PR. I have no intention to finish this now.

**Comment by jaygridley** [comment]
Hello, I will pick this up.

**Comment by jackofallops** [comment]
> Hello, I will pick this up.

Hi @jaygridley - Do you have access to the fork on which this PR was raised?  If not, would you mind opening a fresh PR on a branch on your own fork and I'll close this one?

**Comment by jaygridley** [comment]
@jackofallops I have access to it. I believe I can continue here.

**Comment by jackofallops** [comment]
Hi @jaygridley 
Since there's been no activity here in almost a month I'm going to close this PR for the time being until you have chance to update it, at which time we can either re-open or create a new PR as appropriate.

Thanks

**Pull request closed without merging**
