### PR TITLE
frontdoor: updating to use a generated Resource ID Formatter/Parser/Validator

### LINKED ISSUE #8208: Azurerm_frontdoor with v2.24.0 breaks when azure frontdoor is edited in portal.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.21
+ provider.azurerm v2.24.0
```

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.24.0"
  features {} # https://www.terraform.io/docs/providers/azurerm/index.html#features
}

resource "azurerm_resource_group" "example" {
  name     = "andreastester"
  location = "norway east"
}

resource "azurerm_frontdoor" "example" {
  name                                         = "andreastester"
  resource_group_name                          = azurerm_resource_group.example.name
  enforce_backend_pools_certificate_name_check = false

  routing_rule {
    name               = "exampleRoutingRule1"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["exampleFrontendEndpoint1"]
    forwarding_configuration {
      forwarding_protocol = "MatchRequest"
      backend_pool_name   = "exampleBackendBing"
    }
  }

  backend_pool_load_balancing {
    name = "exampleLoadBalancingSettings1"
  }

  backend_pool_health_probe {
    name = "exampleHealthProbeSetting1"
    
  }

  backend_pool {
    name = "exampleBackendBing"
    backend {
      host_header = "www.bing.com"
      address     = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name = "exampleLoadBalancingSettings1"
    health_probe_name   = "exampleHealthProbeSetting1"
  }

  frontend_endpoint {
    name                              = "exampleFrontendEndpoint1"
    host_name                         = "andreastester.azurefd.net"
    custom_https_provisioning_enabled = false
  }
}
```

### Debug Output

https://gist.github.com/andrstor/0aa07440e0a01befb23351db3257340f

### Expected Behavior

Terraform identifies that no changes are required or tries to recover its state.

### Actual Behavior

Error: flattening `backend_pool`: ID was missing the `healthProbeSettings` element

### Steps to Reproduce

1. `terraform apply`
2. Do anything in the azure portal that trigges a change. For instance add a rule engine rule to the routing rule. 
3. `terraform plan`

You can also undo the manual change again, the resource is still broken for azurerm v2.24.0. This works with v2.23.0

### Important Factoids

None

### References

* #8046

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR works around a series of bugs in the FrontDoor API - by parsing these Resource ID's case insensitively and then rewriting them within Terraform, ensuring that these are consistent from Terraform's point of view.

Whilst this works when the `key` of the key-value pair is returned in the incorrect case, unfortunately we can't workaround the value being incorrect - ultimately the FrontDoor Team needs to fix the API to comply with the ARM/HTTP Spec.. but this is the best we can do at this point in time 🤷

Fixes #8208

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2020-12-08 at 15 05 32

**Review by jackofallops — APPROVED** [review]
Thanks @tombuildsstuff - LGTM 👍

**Review by WodansSon — APPROVED** [review]
@tombuildsstuff Thanks for the PR, this LGTM as well! 🚀

**Comment by erte12** [comment]
Does it fix [#8039](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8039#issuecomment-707956952) too?

**Pull request merged**
