### PR TITLE
azurerm_route - add validation to routing table name and route name (#6053)

### LINKED ISSUE #6053: azurerm_route fails if name attribute contains a slash
### Terraform (and AzureRM Provider) Version

Terraform v0.12.21

### Affected Resource(s)

* `azurerm_v1.44.0_x4`

### Terraform Configuration Files

If you create a route which includes a slash character in its name, the API call gets corrupted.

```hcl
resource "azurerm_route" "example_route" {
      + address_prefix         = "10.255.16.24/32"
      + id                     = (known after apply)
      + name                   = "10.255.16.24/32"
      + next_hop_in_ip_address = "192.168.2.44"
      + next_hop_type          = "VirtualAppliance"
      + resource_group_name    = "example"
      + route_table_name       = "example"
    }
```

### Debug Output

> Error: Error Creating/Updating Route "10.255.16.24/32" (Route Table "example" / Resource Group "example"): network.RoutesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"No HTTP resource was found that matches the request URI 'https://westeurope.network.azure.com:30071/**redacted**/**redacted**/subscriptions/**redacted**/resourceGroups/example/providers/Microsoft.Network/routeTables/main/routes/10.255.16.24/32?api-version=2019-09-01'."}]

### Expected Behavior

If the name attribute is used, it should be safely URL encoded. 

### Actual Behavior

Due to missing encoding, the attribute name could lead to wrong URL components (e.g. a slash in its value is interpreted as path separator. Maybe that could be an injection issue, too.

### PR DESCRIPTION
**Pull request by yves-vogl**
Hi,

I'm trying to fix the issue I stumbled upon (#6053). Hope that helps.

Yves

Edit: Fixes #6053

### CODE REVIEW

**Comment by yves-vogl** [comment]
Alright, now there're some linting issues introduced from outside. I'll check this later.

**Comment by yves-vogl** [comment]
Thanks for the suggestions! I really appreciate them. I accepted the suggestions and now are waiting for tests to complete.

**Comment by yves-vogl** [comment]
Please do not close the PR - I encountered the same issue for SecurityGroupRules and we'd like to fix it, too.

```
Error: Error Creating/Updating Network Security Rule "80/TCP" (NSG "proxy" / Resource Group "****-infrastructure"): network.SecurityRulesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"No HTTP resource was found that matches the request URI 'https://westeurope.network.azure.com:30056/<guid>subscriptions/<guid>/resourceGroups/<resourcegroup>/providers/Microsoft.Network/networkSecurityGroups/proxy/securityRules/80/TCP?api-version=2019-09-01'."}]
```

**Comment by jackofallops** [comment]
> Please do not close the PR - I encountered the same issue for SecurityGroupRules and we'd like to fix it, too.

Hi @yves-vogl - Probably best to PR that change separately.  I'll check this over and try to get it merged for the the 2.7 release later today.

**Comment by jackofallops** [comment]
Associated resource tests pass:
image

**Comment by KishoriPatil03062605** [comment]
I encountered the same issue for Subnet.

Error: Error Creating/Updating Subnet "1.0.1.0/24-subnet" (Virtual Network "web-server-vnet" / Resource Group "web-rg"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"No HTTP resource was found that matches the request URI 'https://southindia.network.azure.com:30114/**redacted**/**redacted**/subscriptions/**redacted**/resourceGroups/web-rg/providers/Microsoft.Network/virtualNetworks/web-server-vnet/subnets/1.0.1.0/24-subnet?api-version=2019-09-01'."}]

**Pull request merged**
