### PR TITLE
tooling: adding a generator for Resource ID Formatters and Parsers

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR introduces a new tool for generating Resource ID Formatters and Parsers, which allows these to be generated via `go:generate`. At this time this only implements this for the "analysisservices" package - but I'll push a subsequent PR to add this for other service packages too.

There's one important design decision with this tool: it intentionally doesn't import the Provider and it's parsing func - to avoid a dependency on the codebase which would slow down execution when we don't really need it.

New Service Packages can adopt this by adding a `resourceids.go` in the service package, containing the ID's to generate:

```
//go:generate go run ../../tools/generator-resource-id/main.go -path=./ -name=Server -id=/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.AnalysisServices/servers/Server1
```

### CODE REVIEW

**Review by jackofallops — APPROVED** [review]
LGTM 👍

**Comment by AdamCoulterOz** [comment]
@tombuildsstuff - I'm getting build errors on some generated files where the strings include is being removed?

```sh
go generate ./azurerm/internal/services/...
go install

# OUPUT:
# github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/desktopvirtualization/parse
# azurerm/internal/services/desktopvirtualization/parse/application_group.go:89:6: undefined: strings
# azurerm/internal/services/desktopvirtualization/parse/host_pool.go:89:6: undefined: strings
```

**Comment by tombuildsstuff** [comment]
@AdamCoulterOz if you run `make tools` that should resolve it, upon regeneration?

**Comment by AdamCoulterOz** [comment]
> @AdamCoulterOz if you run `make tools` that should resolve it, upon regeneration?

@tombuildsstuff ... tired that on a fresh clone of main:

```sh
go version
# go version go1.14.13 darwin/amd64

make tools
# ==> installing required tooling...
# GO111MODULE=off go get -u github.com/client9/misspell/cmd/misspell
# GO111MODULE=off go get -u github.com/bflad/tfproviderlint/cmd/tfproviderlint
# GO111MODULE=off go get -u github.com/bflad/tfproviderdocs
# GO111MODULE=off go get -u github.com/katbyte/terrafmt
# GO111MODULE=off go get -u golang.org/x/tools/cmd/goimports
# GO111MODULE=off go get -u mvdan.cc/gofumpt
# curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH || $GOPATH)/bin v1.32.0
# golangci/golangci-lint info checking GitHub for tag 'v1.32.0'
# golangci/golangci-lint info found version: 1.32.0 for v1.32.0/darwin/amd64
# golangci/golangci-lint info installed /Users/adam/go/bin/golangci-lint

make build
# ==> Checking that code complies with gofmt requirements...
# ==> Checking that Custom Timeouts are used...
# ==> Checking that acceptance test packages are used...
# go generate ./azurerm/internal/services/...
# go generate ./azurerm/internal/provider/
# # github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/desktopvirtualization/parse
# ../services/desktopvirtualization/parse/application_group.go:89:6: undefined: strings
# ../services/desktopvirtualization/parse/host_pool.go:89:6: undefined: strings
# azurerm/internal/provider/services.go:89: running "go": exit status 2
# make: *** [generate] Error 1
```

**Pull request merged**
