### PR TITLE
Support for tags on azurerm_subscription resource #11103

### PR DESCRIPTION
**Pull request by crkg**
- The code is tested and works as expected.

### CODE REVIEW

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @crkg - Many thanks for this PR.  If this does work as described, I think this should be added as an enhancement to the existing `azurerm_subscription` resource, rather than a separate resource for users to manage. I noticed this is your first contribution, is this something that you feel comfortable to do?

**Comment by crkg** [comment]
@Steve, thanks for your feedback, let me contribute to the subscription resource.

**Comment by katbyte** [comment]
I think we support it in the resource currently (https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/subscription/subscription_resource.go#L114) but i don't think that would work with existing subscriptions which this would @jackofallops ?

**Comment by crkg** [comment]
The tags from this resource never works for a new subscription or update the existing subscription. the error received is field cannot be set. hence i created a separate resource with createorupdateatscope . the supported API i found for scope specific  - https://docs.microsoft.com/en-us/rest/api/resources/tags/createorupdateatscope

**Comment by jackofallops** [comment]
Hi @katbyte - @crkg is correct, the Subscriptions APIs (in both the Subscription and Resource RP's) do not support writing tags, and they are currently read-only on this resource.  I was previously unaware that the API noted in this PR could be leveraged to perform the necessary update to the tags on Subscriptions (I've not had chance to test it does actually successfully do so, however).

**Comment by crkg** [comment]
Hi @jackofallops  ( Steve), all the checks have passed, would it be possible for you to review and merge the code to master? for community availability.

**Comment by jackofallops** [comment]
> Hi @jackofallops ( Steve), all the checks have passed, would it be possible for you to review and merge the code to master? for community availability.

Hi @crkg - My earlier feedback was to include this in the existing resource as an enhancement, and this PR is still introducing a new one? We shouldn't have discrete resources for tagging as users would expect to tag the resource at creation time. Since we can leverage the tagsClient to this end, it should be possible to create this experience in-line with the `azurern_subscription` resource. Apologies if I was unclear previously.

**Comment by favoretti** [comment]
Also when looking through the code I see you're attempting to reactivate disabled/deleted subs on tags update - I'm not sure we want this implicit behavior. Enabling/Disabling subscriptions is a very lengthy process and I wouldn't want mine to be re-activated by accident if I made a coding error in TF, I'd rather have TF fail.

**Comment by crkg** [comment]
> Also when looking through the code I see you're attempting to reactivate disabled/deleted subs on tags update - I'm not sure we want this implicit behavior. Enabling/Disabling subscriptions is a very lengthy process and I wouldn't want mine to be re-activated by accident if I made a coding error in TF, I'd rather have TF fail.

I am working on adding the tags to azurerm_subscription so we dont have discrete resource. point noted, did you test it if it enables? i am not sure as i did not had a disabled subscription to test. also why would one make such human error.

**Comment by jackofallops** [comment]
Hi @crkg - Just quickly checking in to see if you are still looking to implement this feature? No worries if not, I can make some time in the next couple weeks to add it if that would be your preference?
Thanks!

**Comment by crkg** [comment]
> Hi @crkg - Just quickly checking in to see if you are still looking to implement this feature? No worries if not, I can make some time in the next couple weeks to add it if that would be your preference?
> Thanks!

Hi Steve,  i am middle of completion since the helper functions changed. i got stuck in an error where delete tags wasnt working as expected.. i will let you know if fixing the error takes little longer should not take longer then a day or two.

**Comment by katbyte** [comment]
@crkg to going to close this in favour of the new PR #11347

**Pull request closed without merging**
