### PR TITLE
fix/use parser for user assigned identity

### PR DESCRIPTION
**Pull request by sharebear**
First attempt at quickly adding parsing of user assigned identities when reading function apps,  app service and "new" virtual machine resources

This fixes my immediate problem with differences in case causing changes in the plan for function_apps that were created before the new id parser was applied to user_assigned_identity.

If there are no objections I would be happy to add the necessary changes to also support the other resource types mentioned in #10029, #10098 and #10099

I think the total list of resources that should be touched are;

* [x] azurerm_app_service
* [x] azurerm_app_service_slot
* [x] azurerm_function_app
* [x] azurerm_function_app_slot
* [x] azurerm_windows_virtual_machine
* [x] azurerm_linux_virtual_machine
* [x] azurerm_api_management
* [x] azurerm_blueprint_assignment
* [x] azurerm_virtual_machine_scale_set
* [x] azurerm_virtual_machine
* [x] azurerm_container_group
* [x] azurerm_kubernetes_cluster
* [x] azurerm_kusto_cluster
* [x] azurerm_application_gateway (change handled in #10031)

### CODE REVIEW

**Comment by sharebear** [comment]
Hi @tombuildsstuff, I see you approved #10031 should I take that as a sign that I should continue distributing the same fix to the other resources mentioned in the description here?

**Comment by tombuildsstuff** [comment]
@sharebear 

>  I see you approved #10031 should I take that as a sign that I should continue distributing the same fix to the other resources mentioned in the description here?

Sure that'd be great if you don't mind 👍

**Comment by sharebear** [comment]
@tombuildsstuff  Is this looking ok now?

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Pull request merged**
