### PR TITLE
AKS: add psp back

### PR DESCRIPTION
**Pull request by t3mi**
Fixes [#9336](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9336)

make acctests SERVICE='containers' TESTARGS='-run=TestAccAzureRMKubernetesCluster_enablePodSecurityPolicy' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/containers/tests/ -run=TestAccAzureRMKubernetesCluster_enablePodSecurityPolicy -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMKubernetesCluster_enablePodSecurityPolicy
=== PAUSE TestAccAzureRMKubernetesCluster_enablePodSecurityPolicy
=== CONT  TestAccAzureRMKubernetesCluster_enablePodSecurityPolicy
--- PASS: TestAccAzureRMKubernetesCluster_enablePodSecurityPolicy (575.44s)

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hey @t3mi 

Thanks for this PR.

As mentioned in #9336 since we've removed this functionality to match the upcoming breaking change the AKS API - and this functionality is end-of-life and being removed in the near future - unfortunately we won't accept a PR to re-introduce this functionality, since it'd need to be pulled out again in the near future.

Unfortunately we feel that re-introducing this field to remove it again would cause further confusion - and since it's deprecated/end-of-life anyway, it's not likely to be adopted by newer users during the deprecation period. Whilst it's unfortunate that the AKS team have opted to extend this deprecation period, that doesn't change the fact that we'd need to remove this - and as such unfortunately we have no plans to reintroduce this functionality, since we'd still need to remove it in a couple of months.

As such, whilst I'd like to thank you for this contribution - I'm going to close this PR for the moment, however as mentioned in #9336 I believe you should be able to pin to version `2.34.0` of the Azure Provider until this is removed by AKS in the not-too-distant future.

Thanks!

**Comment by r-t-m** [comment]
@tombuildsstuff the date was shifted again to May 31. Could you please reconsider this again?

**Comment by t3mi** [comment]
@tombuildsstuff date shifted again to May 31. Could your please reconsider?

**Comment by tombuildsstuff** [comment]
@t3mi as mentioned above, even though the dates been extended by a few months this doesn't change the problem, that we'd be introducing functionality we've removed for a few months to ultimately remove it again - so unfortunately this isn't something we plan to re-introduce.

Whilst we appreciate that's unfortunate for your use-case, should you wish to continue managing this with Terraform, you can pin to version 2.34 of the Azure Provider which includes support for this deprecated preview feature, until it's removed in the not-too-distant future.

That said, it's surprising that the AKS Team have deprecated this without a replacement available - as such I'm going to suggest [reaching out to the AKS Team](https://github.com/Azure/AKS) to get further information on migration options here?

**Comment by t3mi** [comment]
@tombuildsstuff they didn't deprecate it fully and we've already reached them after initial announcement and they aware of no replacement exist yet that's why the dates are shifting. Ok, thanks, will live with the forks then.

**Pull request closed without merging**
