### PR TITLE
Upgrade Go-SDK to v55.5.0

### PR DESCRIPTION
**Pull request by yupwei68**
For Postgresql Flexible Server version upgrade and apim version upgrade.

### CODE REVIEW

**Comment by dylan-asos** [comment]
This is also needed by #7667 for the workspace model update in the new insights package

**Comment by jackofallops** [comment]
Hi @yupwei68 - could you resolve the conflicts please? It appears that a minor bump to the SDK made it in yesterday as part of another PR. I'll review asap after that. Thanks!

**Comment by yupwei68** [comment]
Thanks @jackofallops . Please continue reviewing.

**Comment by jackofallops** [comment]
Hi @yupwei68 - Is there any value in this change now since the flexible server part was unintentionally already included in an earlier PR, and there appears to be no meaningful difference here?

**Comment by yupwei68** [comment]
Hi @jackofallops I have to upgrade the sdk version to do the api management version upgrade to fix https://github.com/terraform-providers/terraform-provider-azurerm/pull/12125 setting `PublicIpAddress` in vnet.

**Review by katbyte — APPROVED** [review]
LGTM 👍

**Pull request merged**
