### PR TITLE
azurerm_azuread_application urls are now required to be https

### LINKED ISSUE #1953: azurerm_azuread_application's default value for the homepage field is no longer valid
As the documentation states, the `azurerm_azuread_application` resource defaults the `homepage` field to `http://[name]`. This used to work fine, but as of today, it seems that the Azure API no longer accepts the `http` scheme. I can work around the bug by providing the `homepage` field myself with the `https` scheme.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.15.0
+ provider.kubernetes v1.1.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.random v1.3.1

### Affected Resource(s)

* azurerm_azuread_application

### Terraform Configuration Files

```hcl
resource "azurerm_azuread_application" "kubernetes" {
  name = "dev-kubernetes"
}
```

### Expected Behavior

Terraform creates an Azure AD Application.

### Actual Behavior

Terraform returned an error from the Azure API

```
azurerm_azuread_application.kubernetes: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2018-09-20T06:33:08","message":{"lang":"en","value":"Url is malformed paramName: WwwHomepage, paramValue: dev-kubernetes, objectType: Microsoft.Online.DirectoryServices.Application"},"requestId":"1ab56632-e57b-476b-82a1-0cb0bd88c111","values":[{"item":"PropertyName","value":"homepage"},{"item":"PropertyErrorCode","value":"NotAWellFormedUrl"}]}}]
```

I can work around the issue by specifying the `homepage` field with the `https` scheme.

```hcl
resource "azurerm_azuread_application" "kubernetes" {
  name     = "dev-kubernetes"
  homepage = "https://dev-kubernetes"
}
```

### Steps to Reproduce

Simply try to create an `azurerm_azuread_application` resource by providing only the name.

1. `terraform apply`

### PR DESCRIPTION
**Pull request by katbyte**
fixes #1953

existing tests are failing:

```
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccAzureRMActiveDirectoryApplication -timeout 180m
=== RUN   TestAccAzureRMActiveDirectoryApplication_basic
--- PASS: TestAccAzureRMActiveDirectoryApplication_basic (25.68s)
=== RUN   TestAccAzureRMActiveDirectoryApplication_availableToOtherTenants
--- PASS: TestAccAzureRMActiveDirectoryApplication_availableToOtherTenants (28.07s)
=== RUN   TestAccAzureRMActiveDirectoryApplication_complete
--- FAIL: TestAccAzureRMActiveDirectoryApplication_complete (9.09s)
	testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:

		* azurerm_azuread_application.test: 1 error(s) occurred:

		* azurerm_azuread_application.test: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2018-09-20T23:06:55","message":{"lang":"en","value":"The URI scheme in property  is invalid or unsupported."},"requestId":"c859cdd5-633a-47d1-86c9-32f5bd47214b","values":null}}]
=== RUN   TestAccAzureRMActiveDirectoryApplication_update
--- FAIL: TestAccAzureRMActiveDirectoryApplication_update (36.61s)
	testing.go:513: Step 1 error: Error applying: 1 error(s) occurred:

		* azurerm_azuread_application.test: 1 error(s) occurred:

		* azurerm_azuread_application.test: Error patching Azure AD Application with ID "076b47b2-ede2-491b-a188-aa108714116a": graphrbac.ApplicationsClient#Patch: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2018-09-20T23:07:21","message":{"lang":"en","value":"The URI scheme in property  is invalid or unsupported."},"requestId":"11689938-958c-4262-af80-c8fc4ac55f90","values":null}}]
FAIL
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm	99.494s
make: *** [testacc] Error 1
```

### CODE REVIEW

**Comment by katbyte** [comment]
tests pass:

```
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccAzureRMActiveDirectoryApplication -timeout 180m
=== RUN   TestAccAzureRMActiveDirectoryApplication_basic
--- PASS: TestAccAzureRMActiveDirectoryApplication_basic (34.13s)
=== RUN   TestAccAzureRMActiveDirectoryApplication_availableToOtherTenants
--- PASS: TestAccAzureRMActiveDirectoryApplication_availableToOtherTenants (35.62s)
=== RUN   TestAccAzureRMActiveDirectoryApplication_complete
--- PASS: TestAccAzureRMActiveDirectoryApplication_complete (29.10s)
=== RUN   TestAccAzureRMActiveDirectoryApplication_update
--- PASS: TestAccAzureRMActiveDirectoryApplication_update (43.48s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	142.373s
```

**Comment by tomasaschan** [comment]
Hi!

I'm wondering if the root cause of this behavior was incorrectly diagnosed, or if maybe Azure have changed their API again. If i peg my `azurerm` provider version to `= 1.15` (i.e. the latest release before this change was merged) I can apply the following template without problems:
```
provider "azurerm" {
  version = "= 1.15"
}

resource "azurerm_azuread_application" "ad_app" {
  name = "tomas-testing"
}
```
In other words, I cannot reproduce the original issue (#1953).

However, as of this PR and version `1.16`, no URLs on the application can be `http`, which disallows something like this:
```
resource "azurerm_azuread_application" "ad_app" {
  name = "tomas-testing"

  reply_urls = ["http://localhost:8080"]
}
```
Again, this template applies successfully with 1.15 but fails on 1.16. This effectively makes impossible to e.g. set reply urls for AzureAD applications that enable local testing of OAuth flows (without configuring your local development environment to run https).

Is there any chance this PR could be reverted for 1.17, to re-enable this configuration?

**Comment by tomasaschan** [comment]
Ping @katbyte @tombuildsstuff - just making sure this didn't fall under the radar because the issue is already closed :)

**Comment by tombuildsstuff** [comment]
@tomasaschan since this issue is closed - would you open a separate issue about that? Thanks!

**Comment by tomasaschan** [comment]
@tombuildsstuff No probs - see #2130 :)

**Pull request merged**
