### PR TITLE
CDN Endpoint Delivery Rules

### PR DESCRIPTION
**Pull request by r0bnet**
Didn't see a request for that yet but we personally have some use cases for it. It implements the CDN rules engine that `Standard_Microsoft` CDN profiles offer.

Documentation: https://docs.microsoft.com/en-us/rest/api/cdn/endpoints/create#deliverypolicy

### CODE REVIEW

**Comment by andymac4182** [comment]
Any chance this could make it into the next release?

**Comment by tombuildsstuff** [comment]
Ignoring quota issues in Azure, the tests pass 👍

**Comment by krzyszt0fd** [comment]
Thank you! I was waiting for this feature. I found one small issue when working with it. Terraform plan always shows that a request_header_condition is about to be added even if it has been added previously and there were no changes in between. I used some other actions and conditions and they work fine.

**Comment by r0bnet** [comment]
Hey @krzyszt0fd,
can you please create an issue for your problem with an example? I'll have a look at it and hopefully fix it asap. Thanks.

**Comment by krzyszt0fd** [comment]
#6539

**Pull request merged**
