### PR TITLE
Allowed larger numbers for azurerm_shared_image_version name

### LINKED ISSUE #2283: Shared_Image _Gallery_Version only takes single digit integers
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
sdccdev01rgp78 git:(master) ✗ terraform -v
Terraform v0.11.10
+ provider.aws v1.43.0
+ provider.azurerm v1.18.0
```

### Affected Resource(s)

*azurerm_shared_image_version

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

data "azurerm_image" "dev" {
  name_regex		= "${var.vm_image}-dev-\\d+\\.\\d+\\.\\d+"
  resource_group_name	= "${data.azurerm_resource_group.rgp.name}"
  sort_descending	= "true"
}

module "image_definition" {
  source		= "mysource"
  image_name		= "${var.image_name}"
  gallery_name		= "${data.azurerm_shared_image_gallery.gallery.name}"
  resource_group_name	= "${data.azurerm_resource_group.rgp.name}"
  os_type		= "${var.image_os_type}"
  image_offer		= "${var.image_offer}"
  image_sku		= "${var.image_sku}"
}

module "image_version_dev" {
  source                = "mysource"
  resource_group_name   = "${data.azurerm_resource_group.rgp.name}"
  gallery_name		= "${data.azurerm_shared_image_gallery.gallery.name}"
  image_name            = "${var.image_name}"
  image_id		= "${data.azurerm_image.dev.id}"
  image_version		= "0.0.111"
  azure_region		= "${var.image_regions}"
}
```
### Expected Behavior
Image Version is created using the Rest API with version 0.0.111

Rest API definition
```
galleryImageVersionName | path | True | string | The name of the gallery Image Version to be created. Needs to follow semantic version name pattern: The allowed characters are digit and period. Digits must be within the range of a 32-bit integer. Format: ..
-- | -- | -- | -- | --
```

### Actual Behavior
```
Error: module.image_version_dev.azurerm_shared_image_version.version: Expected name to be in the format `1.2.3` but got "0.0.111".
```

### Steps to Reproduce

Use a Version of anything that is more than a single digit ex 1.18.0

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by katbyte**
fixes #2283

### CODE REVIEW

**Comment by katbyte** [comment]
Tests pass:

```
==> Fixing source code with gofmt...
gofmt -s -w ./azurerm
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccAzureRMSharedImageVersion_basic -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMSharedImageVersion_basic
=== PAUSE TestAccAzureRMSharedImageVersion_basic
=== CONT  TestAccAzureRMSharedImageVersion_basic
--- PASS: TestAccAzureRMSharedImageVersion_basic (1958.02s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	1959.705s
```

**Comment by whytoe** [comment]
Thanks you guys are the best! @tombuildsstuff @katbyte . This was causing a bunch of issues because it looks like Azure isnt updating the source -> managedImage -> id within our pipeline(below json put parameter from Azure Rest Browser). Terraform says it updated the Shared_image_version but when the image was provisioned it was the old image. 

We had 0.0.1 Hard-coded until this issue was fixed but it may require more investigating, if its you or them on the update function.
```
"source": {
        "managedImage": {
          "id": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Compute/images/{imageName}"
```

**Comment by tombuildsstuff** [comment]
@whytoe is this within a VM Scale Set? if so there's an explicit `upgrade` API endpoint/method that can be called which cycles the machines in the Scale Set

**Comment by whytoe** [comment]
@tombuildsstuff no this is just to commit a new Source Managed Image ID to the same version number in the shared gallery

```Terraform apply 

Example 
ID 
"id": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Compute/images/ImageName1"

```

Then I update the ID but I keep the same image version number "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Compute/images/ImageName2"

```
Terraform Apply
```

Terraform will state that it has updated the shared image version in 2 minutes (first time it takes about 10-15 minutes). But the Image will not actually update.

**Comment by tombuildsstuff** [comment]
@whytoe mind opening a separate issue about that?

**Pull request merged**
