### PR TITLE
Replaced 'count' to 'node_count' in kubernetes datasource

### PR DESCRIPTION
**Pull request by jnehlt**

### CODE REVIEW

**Comment by jnehlt** [comment]
[ISSUE URL](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6350)

**Comment by jnehlt** [comment]
Fixes: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6094

**Comment by tombuildsstuff** [comment]
hi @jnehlt 

Thanks for this PR :)

Taking a look through here unfortunately renaming the field being returned from the data source won't fix this, as the underlying `count` error being tracked in #6094 is due to a change in the behaviour of the SDK in the 2019-11-01 version of the AKS API.

We've been trying to consolidate this behaviour for the last couple of weeks - however unfortunately there's been several breaking changes to the AKS API during this time. As such we've been trying to consolidate the breaking changes to the API and the necessary changes needed to fix this (and several other) open AKS bugs and PR's.

After syncing up with the AKS Team earlier in the week, I've got a branch locally which fixes #6094 and some of the other issues/consolidates some of the other PR's, since unfortunately this requires a rather significant refactor).

Since this branch is nearly feature complete - our intention is to merge and ship this for the v2.5 release of the Azure Provider. As such, whilst I'd like to thank you for this contribution I'm going to close this PR for the moment.

Thanks!

**Comment by jnehlt** [comment]
Ok thanks @tombuildsstuff.

**Pull request closed without merging**
