### PR TITLE
r/azurerm_web_application_firewall_policy support OWASP 3.2 rule set

### LINKED ISSUE #11243: Support for OWASP 3.2 in azurerm_web_application_firewall_policy
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for OWASP 3.2 rule set in the web application firewall policy.

### New or Affected Resource(s)

* azurerm_web_application_firewall_policy

### PR DESCRIPTION
**Pull request by anderius**
Fixes #11243

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
Thanks @anderius - LGTM 👍

**Review by katbyte — CHANGES_REQUESTED** [review]
@anderius - looks like there is a conflict with the changelog - we encourage contributors to not modify it for this reason. COuld we remove that change and i'll get this merged for this weeks release? thanks

**Comment by anderius** [comment]
@katbyte: Sorry about that! I have removed the change from the changelog now.

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @anderius

**Pull request merged**
