### PR TITLE
removed unnecessary force deletes from Service Fabric

### PR DESCRIPTION
**Pull request by steve-hawkins**
removed the force delete from Service Fabric cluster node types and diagnostic storage account

added more testing around the ability to update / delete Service Fabric cluster configuration

### CODE REVIEW

**Comment by steve-hawkins** [comment]
please let me know if there is anything else I can do to get this merged into the 1.31.0 release

**Comment by katbyte** [comment]
Hi @steve-hawkins,

It looks like there are no changed files or lines in this PR? 🤔

**Comment by steve-hawkins** [comment]
@katbyte please close this PR as the changes are included in the following merged PR #3652

**Comment by katbyte** [comment]
Thanks for confirming @steve-hawkins! closing

**Pull request closed without merging**
