### PR TITLE
`azurerm_automation_job_schedule` needs to be recreated after `azurerm_automation_runbook` is updated

### PR DESCRIPTION
**Pull request by yupwei68**
Fix: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7130

Local test the issue scenario with pass. 

Job_schedule is a link from runbook to schedule. Once runbook has been updated, all its related job_schedule will update all linked job schedule id.
First terraform apply, one change to update runbook, terraform apply with success.
Second terraform apply, one create to create job_schedule, (Because job schedule id has been updated, the job schedule reading from its elder job schedule id doesn't exist any more. Here we delete its linked job schedule and recreate this job schedule ), terraform apply with success.

### CODE REVIEW

**Comment by yupwei68** [comment]
Hi @manicminer , it seems that Terraform doesn't have `replace_on_change` lifecycle , according to https://github.com/hashicorp/terraform/issues/8099, to make this resource `azurerm_autoamtion_job_schedule` forcenew when there are updates in `azurerm_automation_runbook`. Thus, this scenario can't be written in acctest. Because it needs 2 terraform apply.  When updating `azurerm_automation_runbook` at the first tf apply, the resource `azurerm_autoamtion_job_schedule` will not exist.(it reads its job schedule id, it set itself empty id when api returns not exist) On fact, runbook has changed the job schedule id. The second tf apply, this resource will be created.

**Comment by manicminer** [comment]
Ah I see, thanks for clarifying. Attempting consistency across a single apply is important and this approach doesn't feel right to me. Given that there can only be one `job_schedule` per `runbook`, and the schedule seems to be a child resource, would it make sense to have this as an optional block on the `runbook` resource rather than a standalone resource?

**Comment by yupwei68** [comment]
Hi @manicminer Thanks for your comments. Corresponding changes have been pushed. Please continue reviewing. 
=== RUN   TestAccAzureRMAutomationRunbook_PSWorkflow
=== PAUSE TestAccAzureRMAutomationRunbook_PSWorkflow
=== CONT  TestAccAzureRMAutomationRunbook_PSWorkflow
--- PASS: TestAccAzureRMAutomationRunbook_PSWorkflow (133.85s)
=== RUN   TestAccAzureRMAutomationRunbook_requiresImport
=== PAUSE TestAccAzureRMAutomationRunbook_requiresImport
=== CONT  TestAccAzureRMAutomationRunbook_requiresImport
--- PASS: TestAccAzureRMAutomationRunbook_requiresImport (146.93s)
=== RUN   TestAccAzureRMAutomationRunbook_PSWorkflowWithHash
=== PAUSE TestAccAzureRMAutomationRunbook_PSWorkflowWithHash
=== CONT  TestAccAzureRMAutomationRunbook_PSWorkflowWithHash
--- PASS: TestAccAzureRMAutomationRunbook_PSWorkflowWithHash (134.25s)
=== RUN   TestAccAzureRMAutomationRunbook_PSWithContent
=== PAUSE TestAccAzureRMAutomationRunbook_PSWithContent
=== CONT  TestAccAzureRMAutomationRunbook_PSWithContent
--- PASS: TestAccAzureRMAutomationRunbook_PSWithContent (134.12s)
=== RUN   TestAccAzureRMAutomationRunbook_withJobSchedule
=== PAUSE TestAccAzureRMAutomationRunbook_withJobSchedule
=== CONT  TestAccAzureRMAutomationRunbook_withJobSchedule
--- PASS: TestAccAzureRMAutomationRunbook_withJobSchedule (307.08s)


=== RUN   TestAccAzureRMAutomationJobSchedule_basic
=== PAUSE TestAccAzureRMAutomationJobSchedule_basic
=== CONT  TestAccAzureRMAutomationJobSchedule_basic
--- PASS: TestAccAzureRMAutomationJobSchedule_basic (137.11s)
=== RUN   TestAccAzureRMAutomationJobSchedule_complete
=== PAUSE TestAccAzureRMAutomationJobSchedule_complete
=== CONT  TestAccAzureRMAutomationJobSchedule_complete
--- PASS: TestAccAzureRMAutomationJobSchedule_complete (138.11s)
=== RUN   TestAccAzureRMAutomationJobSchedule_update
=== PAUSE TestAccAzureRMAutomationJobSchedule_update
=== CONT  TestAccAzureRMAutomationJobSchedule_update
--- PASS: TestAccAzureRMAutomationJobSchedule_update (219.72s)
=== RUN   TestAccAzureRMAutomationJobSchedule_requiresImport
=== PAUSE TestAccAzureRMAutomationJobSchedule_requiresImport
=== CONT  TestAccAzureRMAutomationJobSchedule_requiresImport
--- PASS: TestAccAzureRMAutomationJobSchedule_requiresImport (152.57s)

**Comment by manicminer** [comment]
Thanks @yupwei68, this looks great!

**Comment by manicminer** [comment]
Test results:

Screen Shot 2020-07-23 at 23 40 45
Screen Shot 2020-07-23 at 23 40 56

**Pull request merged**
