### PR TITLE
azurerm_logic_app_trigger_recurrence - adapt timeZone values to match azure schema and make start_time optional

### LINKED ISSUE #12442: time_zone is not working for azurerm_logic_app_trigger_recurrence without start_time
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
on darwin_amd64
provider registry.terraform.io/hashicorp/azurerm v2.65.0

### Affected Resource(s)

* `azurerm_logic_app_trigger_recurrence`

### Terraform Configuration Files

```hcl
resource "azurerm_logic_app_trigger_recurrence" "testapp {
  name         = "testapp-trigger"
  logic_app_id = azurerm_logic_app_workflow.testapp.id
  frequency    = "Week"
  interval     = 1
  time_zone    = "W Europe Standard Time"

  schedule {
    at_these_minutes = [
      0
    ]
    at_these_hours = [
      8,
      9
    ]
    on_these_days = [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
    ]
  }
}
```

### Expected Behaviour

The time zone should be set in the logic app workflow like this, even without specifying the start_time variable:

```json
"timeZone": "W. Europe Standard Time"
```

I would also expect to use "W. Europe Standard Time" but it only allows "W Europe Standard Time" which does not conform to this list from Microsoft: https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11)

### Actual Behaviour

No time zone is set even though it runs through successfully.

If i set the time zone manually via the Portal it is then overwritten, set to nothing, by terraform, especially when using "W. Europe Standard Time".

Setting "W Europe Standard Time" in combination with the start_time variable leads to a 400 error as this time zone is not valid: 

```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_logic_app_trigger_recurrence.testapp will be updated in-place
  ~ resource "azurerm_logic_app_trigger_recurrence" "testapp" {
        id           = "/subscriptions/<SUBSCRIPTION-ID>>/resourceGroups/<RESOURCE-GROUP>/providers/Microsoft.Logic/workflows/testapp/triggers/testapp-trigger"
        name         = "testapp-trigger"
        start_time = "2021
      ~ time_zone    = "W. Europe Standard Time" -> "W Europe Standard Time"
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_logic_app_trigger_recurrence.testapp: Modifying... [id=/subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE-GROUP>/providers/Microsoft.Logic/workflows/testapp/triggers/testapp-trigger]
╷
│ Error: Error updating Logic App Workspace "testapp" (Resource Group "<RESOURCE-GROUP>") for Trigger "testapp-trigger": logic.WorkflowsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidWorkflowTriggerRecurrence" Message="The recurrence of trigger 'testapp-trigger' has an invalid time zone 'W Europe Standard Time'."
│ 
│   with azurerm_logic_app_trigger_recurrence.testapp,
│   on logicapp-wvdautoscaler.tf line 7, in resource "azurerm_logic_app_trigger_recurrence" "testapp":
│    7: resource "azurerm_logic_app_trigger_recurrence" "testapp" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

* #8829

### PR DESCRIPTION
**Pull request by al-lac**
This PR update the timeZone values to match the ones from the azure schema here: https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11)

Using `W Europe Standard Time` leads to a 400 error without the adaptations. 

Also allow setting the `time_zone` variable without having to add `start_time`. 

Configurations can then look like this:
```hcl
resource "azurerm_logic_app_trigger_recurrence" "testapp {
  name         = "testapp-trigger"
  logic_app_id = azurerm_logic_app_workflow.testapp.id
  frequency    = "Week"
  interval     = 1
  time_zone    = "W. Europe Standard Time"

  schedule {
    at_these_minutes = [
      0
    ]
    at_these_hours = [
      8,
      9
    ]
    on_these_days = [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
    ]
  }
}
```

Fixes #12442

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the PR @al-lac - this looks good but are you sure those are the correct values? running the tests and i'm seeing:
```
------ Stdout: -------
=== RUN   TestAccLogicAppTriggerRecurrence_timeZone
=== PAUSE TestAccLogicAppTriggerRecurrence_timeZone
=== CONT  TestAccLogicAppTriggerRecurrence_timeZone
    testcase.go:88: Step 1/4 error: Error running apply: exit status 1
        
        Error: Error updating Logic App Workspace "acctestlaw-210730032930016377" (Resource Group "acctestRG-210730032930016377") for Trigger "frequency-trigger": logic.WorkflowsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidWorkflowTriggerRecurrence" Message="The recurrence of trigger 'frequency-trigger' has an invalid time zone 'U.S. Eastern Standard Time'."
        
          with azurerm_logic_app_trigger_recurrence.test,
          on terraform_plugin_test.tf line 17, in resource "azurerm_logic_app_trigger_recurrence" "test":
          17: resource "azurerm_logic_app_trigger_recurrence" "test" {
        
--- FAIL: TestAccLogicAppTriggerRecurrence_timeZone (111.00s)
FAIL
```

**Comment by al-lac** [comment]
Hi @katbyte, i fixed something in the Test. But i do not think this fixes the issue. I tried it with a built provider as i do not have an azure account for testing. Here only using `U.S. Eastern Standard Time` worked. Not sure how we can test this further.

**Comment by katbyte** [comment]
huh, maybe it depends on the region you run in how it validates this which means there is an API issue that needs to be solves 😞

**Comment by al-lac** [comment]
Ok i think i found the issue. The API seems to only accept **"US Eastern Standard Time"**, even though that is not the correct name according to the [schema](https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11)).

Then i tested **"W Europe Standard Time"** which did not work, but **"W. Europe Standard Time"** worked. Will test some more time zones and update the code accordingly.

**Comment by al-lac** [comment]
@katbyte can you please check it again now? 

I got a test account and managed to test pretty much all scenarios of the time zones.

The problems really seems to be that for the **"U.S."** time zones the API only accepts **"US"**. While for the Directions of **West** and **East** it only accepts **"W."** instead of just **"W"**.

**Review by manicminer — APPROVED** [review]
@al-lac Thanks for the changes! I made one more change to the tests where there was still an occurrence of "U.S. Eastern Standard Time", and rebased onto main. The tests pass for me and this looks good to merge :)

Screenshot 2021-08-09 at 10 03 13

**Pull request merged**
