### PR TITLE
azurerm_synapse_workspace: Adding sql_identity_control_enabled

### PR DESCRIPTION
**Pull request by allantargino**
`sql_identity_control_enabled` allows Synapse pipelines (running as workspace's system assigned identity) to access SQL pools.

References:
* https://docs.microsoft.com/en-us/azure/synapse-analytics/security/how-to-grant-workspace-managed-identity-permissions#grant-managed-identity-permissions-to-the-dedicated-sql-pool

### CODE REVIEW

**Comment by allantargino** [comment]
The acceptance test is failing due to a HTTP 201 (created) not being accepted as success by the SDK.
The fix was recently release on v49.1.0.
So this PR is depended on #9683.

**Comment by allantargino** [comment]
BTW not sure if `workspace_identity_control_for_sql_enabled` is a good property name 🤔

**Comment by katbyte** [comment]
We can probably drop workspace and go with `sql_identity_contorl_enabled`?

**Comment by allantargino** [comment]
Agreed 👍

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @allantargino, looks like we have some test failures now to fix up, thenn this should be good to merge:

```
------- Stdout: -------
=== RUN   TestAccSynapseWorkspace_complete
=== PAUSE TestAccSynapseWorkspace_complete
=== CONT  TestAccSynapseWorkspace_complete
    testing.go:684: Step 0 error: errors during apply:
        
        Error: Granting workspace identity control for SQL pool: synapse.WorkspaceManagedIdentitySQLControlSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=201 -- Original Error: autorest/azure: Service returned an error. Status=201 Code="Unknown" Message="Unknown service error" Details=[{"id":"subscriptions/*******/resourceGroups/acctest-Synapse-210105203011780445/providers/Microsoft.Synapse/workspaces/acctestsw210105203011780445/managedIdentitySqlControlSettings/default","name":"default","properties":{"grantSqlControlToManagedIdentity":{"actualState":"Enabling","desiredState":"Enabled"}},"type":"Microsoft.Synapse/workspaces/managedIdentitySqlControlSettings"}]
        
          on /opt/teamcity-agent/temp/buildTmp/tf-test832164172/main.tf line 27:
          (source code not available)
        
        
--- FAIL: TestAccSynapseWorkspace_complete (972.51s)
```

**Comment by allantargino** [comment]
It was failing due a problem in azure sdk v48.x, after merging master it worked well. Thanks @katbyte !

**Review by katbyte — APPROVED** [review]
Thanks @allantargino - this LGTM 👍

**Pull request merged**
