### PR TITLE
`azurerm_storage_share`: Fix ID for `resource_manager_id`

### LINKED ISSUE #11624: Wrong value returned for azurerm_storage_share attribute resource_manager_id
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.57.0

### Affected Resource(s)

*`azurerm_storage_share`

### Terraform Configuration Files

```hcl
# Create a resourcegroup for our storage account
resource "azurerm_resource_group" "sa_rg" {
  name     = "test-rg"
  location = "norwayeast"
}

# create a storage account for the standard tier
resource "azurerm_storage_account" "standard_sa" {
  name                     = "testshares"
  resource_group_name      = azurerm_resource_group.sa_rg.name
  location                 = azurerm_resource_group.sa_rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

# Create a share
resource "azurerm_storage_share" "share" {
  name                 = "share-name"
  storage_account_name = azurerm_storage_account.standard_sa.name
}

# Get an AAD group
data "azuread_group" "group" {
  display_name = "Some group name"
  security_enabled = true
}

# Grant group members "Storage File Data SMB Share Contributor" on the share
resource "azurerm_role_assignment" "contributor_assignment" {
  principal_id         = data.azuread_group.group.id
  role_definition_name = "Storage File Data SMB Share Contributor"
  scope = azurerm_storage_share.share.resource_manager_id
  # Ideally scope should be the above but there seem to be a bug with the resource_manager_id value as it returns ".../default/shares/..." instead of ".../default/fileshares/..."
  #scope = "${azurerm_storage_account.standard_sa.id}/fileServices/default/fileshares/${azurerm_storage_share.share.name}"
}
```

### Expected Behaviour

When applying the above configuration a new role assignment is expected to be created for the fileshare.

### Actual Behaviour

We don't get a new role assignment for the fileshare.
We can work around the issue with by using the commented out `scope = ...`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by favoretti**
@tombuildsstuff Wonder if we need a state migration here too?

Fixes #11624

### CODE REVIEW

**Comment by magodo** [comment]
@favoretti I suppose yes, we need to migrate the state as the ID has changed.

**Comment by favoretti** [comment]
@magodo as discussed with @tombuildsstuff offline just now, we should be fine without a state migration here. Please do call the ID change for the computed value of `resource_manager_id` in `azurerm_storage_share` resource in the CHANGELOG when merging.

Thanks!

**Comment by tombuildsstuff** [comment]
+1 yeah this shouldn't need a state migration since this is a computed field - but as mentioned above we do need to document that this is changing. The question here is _why_ this changed in the API, was this incorrect in the first place - or is this a breaking change to the API?

**Comment by favoretti** [comment]
I might have just shot this one in the head by adding sdkv2 shim to storage, but if/when that one gets in, I'll rebase this.

**Review by mbfrahry — APPROVED** [review]
LGTM!

**Pull request merged**
