### PR TITLE
Fix/workaround for #7470 and #6041

### LINKED ISSUE #6041: Changes to azurerm_traffic_manager_profile destroys endpoints
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_traffic_manager_profile`
* `azurerm_traffic_manager_endpoint`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "azurerm_traffic_manager_profile" "api" {
  name                = "my-api"
  resource_group_name = var.resource_group_name
  traffic_routing_method = "Priority"

  dns_config {
    relative_name = "my-api.example.com"
    ttl           = 15
  }

  monitor_config {
    protocol                     = "https"
    port                         = 443
    path                         = "/health"
    interval_in_seconds          = 30
    timeout_in_seconds           = 5
    tolerated_number_of_failures = 3
    expected_status_code_ranges  = ["100-403"]
  }
}


resource "azurerm_traffic_manager_endpoint" "api_blue_endpoint" {
  name                = "my-api-blue"
  resource_group_name = var.resource_group_name
  profile_name        = azurerm_traffic_manager_profile.api.name

  target_resource_id = var.blue_ip_resource_id
  type               = "azureEndpoints"
  priority           = 10
  endpoint_status    = var.enable_blue == true ? "Enabled" : "Disabled"

  custom_header {
    name  = "Host"
    value = "my-apu."
  }
}
```

### Expected Behavior

Changes to values in the `azurerm_traffic_manager_profile` should not affect the `azurerm_traffic_manager_endpoint`.

### Actual Behavior
Changes to values in the `azurerm_traffic_manager_profile` like `monitor_config.path` or `dns_config.ttl` causes all the `azurerm_traffic_manager_endpoint` to disappear. You basically have to run terraform twice to reprovision them.

### Steps to Reproduce

1. `terraform apply`
2. Change `monitor_config.path` from `/health` to `/healthz`.
3. `terraform apply`

Your endpoints are now gone.

### References

* #0000

### PR DESCRIPTION
**Pull request by nitzanm**
#7470 happens because Traffic Manager Profile update is a PUT request. PUT, by definition, replaces the entire object. Since the list of Endpoints is part of the Profile object in Azure, it is cleared because the provider doesn't specify it in the PUT request.

Since our schema specifies Endpoints as separate objects than the Profile, we shouldn't be touching the endpoints when updating a Profile. There are two ways to do that:

1. Replace the PUT with a PATCH. I don't like this because that allows for config drift, especially if Traffic Manager Profiles have new attributes in the future that the provider doesn't know about yet.
2. Retrieve all endpoints and copy them into the PUT request so that they aren't affected.  Is this beautiful? Absolutely not, but I don't see a better solution given the restrictions.

(fixes #6041)

### CODE REVIEW

**Comment by nitzanm** [comment]
@tombuildsstuff could you possibly re-trigger the build? Looks like it failed with an error unrelated to my changes (while installing tooling), but I don't have permission to re-run it.

**Comment by IvanKirianov** [comment]
Hi guys, 
When you are plan to merge this bugfix? 
Thanks!

**Comment by nitzanm** [comment]
@ArcturusZhang I don't have a strong opinion on it either way; I'm OK with changing it to use PATCH instead. I'll try to get to it next week.

BTW: any idea why the CI build is failing? It looks to me like an environment error rather than something introduced by my code changes, but perhaps you have some insight?

**Comment by ArcturusZhang** [comment]
Hi @ArcturusZhang actually you can ignore that CI failure since it is caused by some random connection issues. When you make a new commit, the CI could automatically get triggered again.

**Comment by rohinz** [comment]
> Hi @ArcturusZhang actually you can ignore that CI failure since it is caused by some random connection issues. When you make a new commit, the CI could automatically get triggered again.

@nitzanm Can you give it a try?

**Comment by katbyte** [comment]
Hi @nitzanm, thanks for this PR. As comments have been addressed by #7846 i'm going to close this in favour of it

**Pull request closed without merging**
