### PR TITLE
apimanagement upgrade from `2019-12-01` to `2020-12-01`

### PR DESCRIPTION
**Pull request by MattiasAng**
Requires go sdk v52.6.0 like #11108

Dependency to be able to implement #10138 and probably a couple of more issues.
Need some help with the tests since it is incredibly slow and my MSDN subscription is running out of money. Ran tests for those resources where changes were required.

### CODE REVIEW

**Comment by manicminer** [comment]
@MattiasAng Thanks for this PR! Do you need to upgrade v52.5.0 to v52.6.0? SDK version upgrades usually affect a lot of services and we will normally do this in a standalone PR.

**Comment by MattiasAng** [comment]
@manicminer SDK update was merged yesterday, see #11108

**Comment by manicminer** [comment]
@MattiasAng Sorry about that, misread the diff there! I'm running through the acctests for this and will hopefully be able to review it tomorrow (API management takes awhile).

**Comment by manicminer** [comment]
Hi @MattiasAng, sorry for the delay on reviewing this, could you resolve the conflicts and I'll get to it asap. Thanks!

**Comment by MattiasAng** [comment]
@manicminer Should be fixed now

**Comment by manicminer** [comment]
Awaiting acceptance test results

**Comment by manicminer** [comment]
@MattiasAng I've run these a few times to average out the failures. I'm getting a consistent failure for `TestAccApiManagementAuthorizationServer_complete` with a persistent diff:

```
          # azurerm_api_management_authorization_server.test will be updated in-place
          ~ resource "azurerm_api_management_authorization_server" "test" {
                api_management_name          = "acctestAM-210419125530427842"
                authorization_endpoint       = "https://azacctest.hashicorptest.com/client/authorize"
                authorization_methods        = [
                    "GET",
                    "POST",
                ]
                bearer_token_sending_methods = [
                    "authorizationHeader",
                ]
                client_id                    = "42424242-4242-4242-4242-424242424242"
                client_registration_endpoint = "https://azacctest.hashicorptest.com/client/register"
                client_secret                = (sensitive value)
                default_scope                = "read write"
                display_name                 = "Test Group"
                grant_types                  = [
                    "authorizationCode",
                ]
                id                           = "/subscriptions/1a6092a6-137e-4025-9a7c-ef77f76f2c02/resourceGroups/acctestRG-210419125530427842/providers/Microsoft.ApiManagement/service/acctestAM-210419125530427842/authorizationServers/acctestauthsrv-210419125530427842"
                name                         = "acctestauthsrv-210419125530427842"
                resource_group_name          = "acctestRG-210419125530427842"
              + resource_owner_password      = (sensitive value)
              + resource_owner_username      = "rick"
                support_state                = true
                token_endpoint               = "https://azacctest.hashicorptest.com/client/token"
            }
```

Could you look into that?

**Comment by MattiasAng** [comment]
Thanks for doing the integration tests.

Did a quick test and it seems like it is not being set at all so need to do some API testing to see if there are issues there first.
Will try to get to it next week.

**Comment by MattiasAng** [comment]
Unfortunately this seems to be an API bug. Rest specifications looks correct.

````
GET /subscriptions/redacted/resourceGroups/acctestRG-redacted/providers/Microsoft.ApiManagement/service/acctestAM-redacted/authorizationServers/acctestauthsrv-redacted?api-version=2020-12-01

{
    "id": "/subscriptions/redacted/resourceGroups/acctestRG-redacted/providers/Microsoft.ApiManagement/service/acctestAM-redacted/authorizationServers/acctestauthsrv-redacted",
    "type": "Microsoft.ApiManagement/service/authorizationServers",
    "name": "acctestauthsrv-redacted",
    "properties": {
        "displayName": "Test Group",
        "description": "",
        "clientRegistrationEndpoint": "https://azacctest.hashicorptest.com/client/register",
        "authorizationEndpoint": "https://azacctest.hashicorptest.com/client/authorize",
        "authorizationMethods": [
            "GET",
            "POST"
        ],
        "clientAuthenticationMethod": [],
        "tokenBodyParameters": [],
        "tokenEndpoint": "https://azacctest.hashicorptest.com/client/token",
        "supportState": true,
        "defaultScope": "read write",
        "grantTypes": [
            "authorizationCode"
        ],
        "bearerTokenSendingMethods": [
            "authorizationHeader"
        ],
        "clientId": "42424242-4242-4242-4242-424242424242"
    }
}
````

vs

````
GET /subscriptions/redacted/resourceGroups/acctestRG-redacted/providers/Microsoft.ApiManagement/service/acctestAM-redacted/authorizationServers/acctestauthsrv-redacted?api-version=2019-12-01

{
    "id": "/subscriptions/redacted/resourceGroups/acctestRG-redacted/providers/Microsoft.ApiManagement/service/acctestAM-redacted/authorizationServers/acctestauthsrv-redacted",
    "type": "Microsoft.ApiManagement/service/authorizationServers",
    "name": "acctestauthsrv-redacted",
    "properties": {
        "displayName": "Test Group",
        "description": "",
        "clientRegistrationEndpoint": "https://azacctest.hashicorptest.com/client/register",
        "authorizationEndpoint": "https://azacctest.hashicorptest.com/client/authorize",
        "authorizationMethods": [
            "GET",
            "POST"
        ],
        "clientAuthenticationMethod": [],
        "tokenBodyParameters": [],
        "tokenEndpoint": "https://azacctest.hashicorptest.com/client/token",
        "supportState": true,
        "defaultScope": "read write",
        "grantTypes": [
            "authorizationCode"
        ],
        "bearerTokenSendingMethods": [
            "authorizationHeader"
        ],
        "clientId": "42424242-4242-4242-4242-424242424242",
        "resourceOwnerUsername": "rick",
        "resourceOwnerPassword": "C-193P"
    }
}````

**Comment by manicminer** [comment]
@MattiasAng I've opened an issue at https://github.com/Azure/azure-rest-api-specs/issues/14128 referencing the example responses you posted.

We can potentially work around this by examining the values in configuration using `d.Get()` in the Read function, and re-setting that same value in state. It's not ideal since we can't detect service-side drift, but we can accept this for the time being. If you can get that working, just add a TODO comment linking to the upstream issue. Thanks!

**Comment by MattiasAng** [comment]
@manicminer Should be good to go now.

**Comment by manicminer** [comment]
@MattiasAng Great, thanks for circling back. Running the `TestAccApiManagementAuthorizationServer_complete` test now.

**Review by manicminer — APPROVED** [review]
LGTM 👍 

Test results (failures are present on master):

Screenshot 2021-04-29 at 13 38 39
Screenshot 2021-04-29 at 13 36 24

**Pull request merged**
