### PR TITLE
AKS: Support outbound IPs when using standard loadbalancer

### LINKED ISSUE #4322: AKS: support setting cluster outbound IPs when using standard loadbalancer
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In June, Azure added preview support for using Standard sku load balancers in AKS clusters. Support for configuring load balancer sku was added to this provider in 73f6b2bf7f2b44bdf3fa9a081fe37a87a2a6a7d8.

The feature is now in GA, and Azure has added the additional possibility of configuring what LoadBalancerProfile to use (what IPs or IP prefixes to use for outbound traffic) in the latest version of the containerservice API (github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2019-08-01/containerservice). 

Support for setting IPs or IP prefixes should therefor be added to this provider.      

While at it, one should also add the possibility to just configure the number of managed outbound IPs the cluster should provision.   

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "default" {
...
 network_profile {
    load_balancer_sku = "standard"
    # one of the following
    load-balancer-outbound-ips = [ip1, ip2] 
    load-balancer-outbound-ip-prefixes = [ippref1, ippref2]
    load-balancer-managed-outbound-ip-count = 4
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#optional---provide-your-own-public-ips-or-prefixes-for-egress

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Re-basing #4400 - originally by @evenh 

Fixes #4322

### CODE REVIEW

**Comment by evenh** [comment]
We need this functionality urgently. Is there anything we can do to help out @tombuildsstuff?

**Comment by landro** [comment]
Hi @tombuildsstuff , any chance we can have this feature merged any time soon?

**Comment by landro** [comment]
Hi @tombuildsstuff - is there anything we can do to help move this PR forward?

**Comment by ekarlso** [comment]
@tombuildsstuff can we get this expedited for a release soon? We're having fun with duplicate ips on all our clusters that has Standard SKU.

**Comment by seboss666** [comment]
Hello,
I've just ran into the problem of "duplicate IP" when switching to standard LB SKU (to activate [API Server authorized IP ranges](https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges) . Any update on conflict resolution ?

**Comment by ekarlso** [comment]
@tombuildsstuff any idea on this?

**Comment by landro** [comment]
Hi @tombuildsstuff !
this PR has been pushed from milestone to milestone for the past few months. Do you think it will make it this time? Is there anything we can do to help out?

**Comment by tombuildsstuff** [comment]
@landro unfortunately this isn't something we've got time to rebase at the moment - we're hoping that we can come back to this once the remaining bits of 2.0 have come together.

From our side if someone has time to rebase/fix this up/send a new PR we're more than happy to close this PR in favour of another one - however I don't believe we're going to get a chance to do this in the next couple of weeks unfortunately.

**Comment by rubbish** [comment]
just as an FYI, @evenh has rebased this into a new PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/5394

**Comment by katbyte** [comment]
thanks @rubbish, closing in favour of #5394.

**Pull request closed without merging**
