### PR TITLE
azurerm_container_group - support `volume.empty_dir`

### PR DESCRIPTION
**Pull request by afdezl**
This PR adds the `emptyDir` volume type for ACI.
Note that because Azure requires this to be empty, it is passed as a bool and then turned into an empty object.

### CODE REVIEW

**Comment by afdezl** [comment]
References: #1860

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the PR @afdezl - overall this looks great but we will need to set the value for empty dir on read to prevent this a failing test:

`container.0.volume.0.empty_dir:                      "false" => "true" (forces new resource)`

**Comment by afdezl** [comment]
> Thanks for the PR @afdezl - overall this looks great but we will need to set the value for empty dir on read to prevent this a failing test:
> 
> `container.0.volume.0.empty_dir: "false" => "true" (forces new resource)`

Thanks @katbyte. Just implemented.

**Review by katbyte — APPROVED** [review]
Thanks @afdezl - this LGTM now 🚀

**Pull request merged**
