### PR TITLE
[WIP] Added JitNetworkAccessPolicy basic implementation

### PR DESCRIPTION
**Pull request by PaulDFoster**
Adds the Azure just-in-time network access policy setting capability for virtual machine ports documented in issue [#3661 ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3661)

Implemented as part of the Security Center resources. The acceptance test demonstrates the implementation of the JIT network access policies on the required Network Security Group (NSG) associated with a subnet used by the target virtual machine.  The JIT Network Access Policy REST API creates a new security rule on the NSG which currently trips up Terraform state management. 

Expert guidance would be appreciated on how to best resolve this. E,G, Make functionality part of the NSG resource provider

Implemented in this draft PR for the JIT Network Access Policy:
1. Custom client to accommodate the passing of a location parameter (default client is hardcoded to Global)
2. Parse functionality
3. Basic acceptance test
4. Example Terraform including the *required* virtual machine, subnet, network security group dependency
5. Resource implementation using simple schema:

```
resource "azurerm_jit_network_access_policies" "test-jit-network-access" {
	name = "default-test"
	asc_location = "northeurope"
	resource_group_name = "test-jit"
	kind = "Basic"
	virtual_machines {
		name = "test-jit-vm-1"
		ports {
			port = 22
			protocol = "*"
			allowed_source_address_prefix = "*"
			max_request_access_duration = "PT3H"
		}	
	}
  }

### CODE REVIEW

**Comment by njuCZ** [comment]
@PaulDFoster May I ask the current status of this PR? Is there anything I could help?

**Comment by njuCZ** [comment]
@PaulDFoster since long time no replies, May I ask whether it's ok for me to take over this work? Of course I will make it based on what you have done.

**Comment by PaulDFoster** [comment]
> @PaulDFoster since long time no update, May I ask whether it's ok for me to take over this work? Of course I will make it based on what you have done.

@njuCZ sorry for my delay. There are some unanswered questions regarding this design. The artefact of setting a policy is set on the NSG. If the NSG is created within Terraform, applying a JitNetworkAccessPolicy results in untracked state. Should the JitNetworkAccesPolicy therefore be implemented on the NSG provider? This is a common issue for TF, I don't have the experience to determine best way forward. I'm happy for you to take over this work. Ty!

**Comment by njuCZ** [comment]
Thanks for your reply, I will have an investigation first and then share my thoughts

**Comment by tombuildsstuff** [comment]
hey @PaulDFoster 

Thanks for this PR - apologies for the delayed review here!

Since #10326 includes and has built upon these changes, rather than having two PR's open for the same thing I hope you don't mind but I'm going to close this in favour of #10326

Thanks!

**Comment by PaulDFoster** [comment]
Hi Tom.

Yes of course. Njucz and I discussed stuff. Pleased to see a solution moved forward.

Cheers
Paul

PAUL FOSTER
Commercial Software Engineering
Senior Software Engineer | Microsoft UK
t: +44 (0)118 909 3838| m: +44 (0)7802 881926  e:paulfo@microsoft.com
____________________________________________________________________________________
Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading. RG6 1WG
[MSLogo]<http://www.microsoft.com/en-gb/default.aspx>

Pause for thought: If you're not failing every now and again, it's a sign you're not doing anything very innovative.

**Pull request closed without merging**
